### ISSUE TITLE
Remove merged-up deprecations from 5.0

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#10]
Searching the codebase for `@deprecated` and `Deprecation::` showed multiple results.  Likely these slipped in from the recent 4 -> 5.0 merge-ups

### ACs
- [ ] All relevant `@deprecated` and `Deprecation::` notices are removed from all the code in sink

### New issues created
- https://github.com/silverstripe/silverstripe-framework/issues/10718
- https://github.com/silverstripe/.github/issues/11

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10719
- https://github.com/silverstripe/silverstripe-subsites/pull/512

**Comment by GuySartorelli** [comment]
PRs merged, other cards are their own thing. Couldn't find any other references in our code.
