### ISSUE TITLE
Broken graphql test on silverstripe/installer 4.13

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#101]
InheritanceBuilderTest::testFillAncestryInjectorSubclass

https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/5953679735/job/16148509886

It'll probably start breaking in other branches after it auto merge-ups

## PRs
- https://github.com/silverstripe/silverstripe-graphql/pull/551

**Comment by GuySartorelli** [comment]
PR merged
