### ISSUE TITLE
Update logo everywhere

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#102]
We need to update a bunch of things to use the new logo. It's not a secret, but I would rather we update the logo on the doc closer to the CMS 5.1 release ... or at least post StripeCon.

## Acceptance criteria
- [x] The new logo is used in our GitHub organisation (see https://github.com/silverstripe)
- [x] The new logo is used in any "Social Preview" in GitHub repository settings (e.g. https://github.com/silverstripe/silverstripe-framework/settings)
- [x] The new logo is on the doc.
- [x] The new logo is on the userhelp.
- [x] The new logo is on the forum
- [x] The new logo is on our GitHub org.
- [x] The new logo is on the public Slack.
- [x] Those changes are done around the end of September.
- [x] DotOrg top image and footer are updated to use the new logo, favicon.
- [x] Marketing team is aware of the logo change and are in a position to update DotCom.

## Note
- https://github.com/silverstripe/silverstripe-admin/issues/1542
- Addons and API sites don't have logo
- The logo probably appears in a lot of places in DotORG, but we will only be updating the most prominent ones.

## PRs
- https://github.com/silverstripe/doc.silverstripe.org/pull/272
- https://github.com/silverstripeltd/silverstripe.org/pull/183
- https://github.com/silverstripe/doc.silverstripe.org/pull/273
- https://github.com/silverstripeltd/silverstripe.org/pull/184
- https://github.com/silverstripe/silverstripe-installer/pull/362

**Comment by GuySartorelli** [comment]
@maxime-rainville How much do we care about externally controlled web content, e.g:
- https://en.wikipedia.org/wiki/Silverstripe_CMS
- https://www.catalyst.net.nz/silverstripe

**Comment by GuySartorelli** [comment]
I've moved the AC for the demo favicon to https://github.com/silverstripeltd/product-issues/issues/813 since it makes more sense to do as part of the stable release.

**Comment by GuySartorelli** [comment]
NOTE: I am explicitly not updating images in the userhelp and developer docs themselves (e.g. screenshots of the CMS) because that would be a lot more work than is probably worthwhile.
If the peer reviewer disagrees, I can go through and do that - but I'd really rather not.

**Comment by GuySartorelli** [comment]
@maxime-rainville I either don't have access to update the logos on the forum or I don't know where to look.
The logos on the forum that I've identified are:
- horizontal logo in the header
- vertical logo in the header (when you scroll down)
- favicon

**Comment by GuySartorelli** [comment]
@maxime-rainville Still needs to be done, but I don't have access:

- Deploy changed to silverstripe.org
- Logo changes for the forum

**Comment by maxime-rainville** [comment]
I'm deploying the DotOrg changes to UAT.

I updated the logo on the forum as well.

I have some beef with the padding on the GitHub Org avatar.

![image](https://github.com/silverstripeltd/silverstripe.org/assets/1168676/2256aa4e-d6ac-4a6f-a5c0-10a491377b42)

I'll double check all of those with James and see what he thinks.

**Comment by maxime-rainville** [comment]
Updated changes have been deployed to https://ssorg-test.sites.silverstripe.com

Everything looks fine.

I did use a slight different favicon on the forum.
- DotOrg 
![image](https://github.com/silverstripe/.github/assets/1168676/0085729c-db5a-49c4-b837-e44af78f67b3)
- Forum
![favicon](https://github.com/silverstripe/.github/assets/1168676/f31c2b35-c944-4298-8d43-cc5912f32f5d)

I don't know that it any difference, but I'll let James be the judge of that.

**Comment by GuySartorelli** [comment]
I personally think it's sensible to use the different favicon for the forum, since the forum is so far detached from the rest of dotorg in terms of its styling, content, and purpose - the fact that it's a subdomain is barely noticable as is and frankly that separation is better served by having a different favicon.

**Comment by maxime-rainville** [comment]
## Questions for the design team

- Here's all the context where the new logo appears. Let us know if you are happy with them.
  - [Public Slack ](https://silverstripe-users.slack.com/) 
![image](https://github.com/silverstripe/.github/assets/1168676/86b6de77-04b5-4bc6-a332-113a4e89868f)
  - [Silverstripe CMS Forum](https://forum.silverstripe.org/)
  - [Silverstripe.org](https://ssorg-test.sites.silverstripe.com/) (test environment - you'll need to be on Silverstripe network to see this)
    - ![image](https://github.com/silverstripe/.github/assets/1168676/d0f18df8-8d5e-4edc-9431-50e24918956f)
    - ![image](https://github.com/silverstripe/.github/assets/1168676/17e11409-37c2-4b72-a391-c54547ccfe08)
    - ![image](https://github.com/silverstripe/.github/assets/1168676/7f335bbb-3f17-43a2-90de-e7ea55967867)
  - [Developer doc](https://docs.silverstripe.org/) and [user doc](https://userhelp.silverstripe.com)
  - [GitHub org](https://github.com/silverstripe)
- We have slightly different favicon for the forum and for everything else. Does it matter?
- The Github Org avatar doesn't have any horizontal padding, which makes it look a bit weird to my eye. Also consider that GitHub has a light and a dark theme. Let us know how you would want us to handle this.
  - ![image](https://github.com/silverstripe/.github/assets/1168676/4ec64e01-f319-484a-90fc-90285b9a3f63)
  - ![image](https://github.com/silverstripe/.github/assets/1168676/2d31a6c9-d016-48fd-a408-2aa97423ed07)

**Comment by maxime-rainville** [comment]
Feedback from James:
- Slack icon needs more padding
- The Dot Org title logo is nice
- The dot org Mega menu should be using the Silverstripe logo
- The DotOrg footer logo should be using the Silverstripe logo
- The GitHub logo should have more padding
- User help and dev doc logos are nice
- The favicons everywhere need more padding (that [icons](https://github.com/silverstripe/silverstripe-installer/blob/5.1/public/favicon.ico) are in the installer, so it probably needs to be updated there as well.)

James provided the following images for the extra padding
![image](https://github.com/silverstripe/.github/assets/1168676/a16875cb-8322-4bcc-a3e9-5a8f6f701cd5) ![image](https://github.com/silverstripe/.github/assets/1168676/dfbe27b0-6807-4592-b2bb-214e3010c4c4)

I've updated the GitHub icon, the Slack Icon and the forum icons.

What is left:
- DotOrg Megamenu to Silverstripe
- DotOrg footer to silverstripe
- DotOrg favIcon
- User help favicon
- Dev doc favicon

**Comment by maxime-rainville** [comment]
Pretty logo is out everywhere.
