### ISSUE TITLE
phpunit validation failure on exclude

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#109]
When running phpunit tests on installer, getting the following validation error
  - Element 'exclude': Element content is not allowed, because the type definition is simple.

![image](https://github.com/silverstripe/.github/assets/4809037/3395d1f5-f5b7-4cf3-afa6-1e61038a5ea3)

https://github.com/silverstripe/silverstripe-installer/blob/5/phpunit.xml.dist#L32

Looks like exclude is only for code-coverage reports https://docs.phpunit.de/en/9.6/configuration.html#the-exclude-element

Was introduced here
https://github.com/silverstripe/silverstripe-installer/pull/356
and here
https://github.com/silverstripe/recipe-kitchen-sink/pull/45

### PRs
- https://github.com/silverstripe/silverstripe-installer/pull/361
- https://github.com/silverstripe/recipe-kitchen-sink/pull/47

**Comment by GuySartorelli** [comment]
PRs merged
