### ISSUE TITLE
Remove Serializable from asyncphp/doorman

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#11]
asyncphp/doorman was previously moved to the [silverstripe/doorman](https://github.com/silverstripe/doorman) repo

doorman is used by symbiote/silverstripe-queuedjobs

doorman still uses the Serializable interface which requires the implementation of the deprecated serialize() and unserialize() methods.

For the rest of our code base that interface and those methods have since been removed and replicated with __serialize() and __unserialize() methods.

There is a unreleased `4` branch for doorman for CMS 5. 

### ACs
- [ ] Remove Serialize() from doorman
- [ ] Implement __serialize() / __unserialize() if required
- [ ] Create a 4.0 branches from 4 post merge
- [ ] Update the CMS 5 version of symbiote/silverstripe-queuejobs to use ^4 of doorman
- [ ] Remove serialize() / unserialize() from queuedjobs
- [ ] Release doorman 4.0.0-beta1
- [ ] Add doorman 4.x-dev/4.0.x-dev to the root of silverstripe/recipe-kitchen sink so that it gets released as part of 5.0
- [ ] Deprecate serialise() / unserialise() in doorman 3

### PRs
- https://github.com/silverstripe/closure/pull/1
- https://github.com/silverstripe/doorman/pull/46
- https://github.com/symbiote/silverstripe-queuedjobs/pull/399
- https://github.com/silverstripe/recipe-kitchen-sink/pull/42
- https://github.com/silverstripe/doorman/pull/47
- https://github.com/silverstripe/developer-docs/pull/200

**Comment by maxime-rainville** [comment]
I would be keen to better understand why we didn't pick this up when we first tag the CMS 5 Sink and how we found it later on.
