### ISSUE TITLE
CMS 5.1.0-beta1. Regression testing: Maori (New Zealand) is not available in a list of Locales 

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/.github#111]
#### Environment: SC PHP8.1 Firefox Sink

Maori (New Zealand) is not available in a list of Locales 

- https://studio.cucumber.io/projects/301855/test-runs/835224/folder-snapshots/8880177/scenario-snapshots/30498416/test-snapshots/41412688

### Note
- It looks like work with macrons on SC. On SCPS "Maori" spelling is wrong. I can find it without macrons.
- We should update test case as well.

## PR
- https://github.com/silverstripe/cwp-core/pull/126
- https://github.com/silverstripe/silverstripe-framework/pull/10951

**Comment by sabina-talipova** [comment]
There doesn't seem to be any problem in the code here.
`Locale::getDisplayName($locale, i18n::get_locale())` returns a different value depending on the value of `i18n::default_local`. This value may change depending on the current user's Locals setting.
  But for some reason, on SCPS we pass the second value to this method either `en_US` or `en_GB`, but in the SC we use the correct value `en_NZ`

**Comment by GuySartorelli** [comment]
You're looking at the default_locale - but cwp-core explicitly sets the locale (not default, but the actual current locale) here:
https://github.com/silverstripe/cwp-core/blob/9891120027088e077ab8af8497d890e8dea911bb/_config.php#L19C1-L19C27

**Comment by sabina-talipova** [comment]
There are several reasons for the unstable operation of Locales section of the CMS.
- since we have a locale setting set in the `_config` file in cwp module, which is applied after the configuration `.yml` files.
- cwp configuration settings are applied in priority
- if the user who creates another user has a locale installed, then this locale will be applied to the created user by default. But since we cannot change this setting to “en_NZ” in the long-range, this affects how the language “Maori” or "Māori " will be displayed in the list of locales.
- if the user who creates another user for some reason did not have a locale set (empty string or NULL), but at the same time the `default_local` for which there is no additional translation file (for example, some specific dialect or one language that has its own specifics in different countries (en_NZ)), then when creating a new user, the first in the list Locale (af_ZA) will be applied to it, since there is no such locale as English (New Zealand) in the list.

Plus [Fluent module]((https://github.com/tractorcow-farm/silverstripe-fluent/blob/master/docs/en/configuration.md)) requires `REMOVE any `i18n::set_locale` calls from your `_config.php` file, as it
will interfere with locale bootstrapping in certain situations (such as `Security` controller actions)`.

So we still need to make some changes and clarify our documantation.

**Comment by GuySartorelli** [comment]
PR merged. Reassigning to Sabina in case any documentation needs to be changed as per this comment:

> So we still need to make some changes and clarify our documentation.

**Comment by sabina-talipova** [comment]
I'll update(clarify) our regression test steps.
