### ISSUE TITLE
Failed Merge-ups

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#113]
Rhino is reporting some failed merge up jobs. They'll need to be looked at manually.

## PRs
- https://github.com/silverstripe/gha-merge-up/pull/27
- https://github.com/silverstripe/silverstripe-behat-extension/pull/251
- https://github.com/silverstripe/gha-trigger-ci/pull/5

**Comment by emteknetnz** [comment]
PRs have been merged, reassigned back to confirm that things work as intended

**Comment by GuySartorelli** [comment]
Moved to awaiting until there are some changes to see being merged up

**Comment by GuySartorelli** [comment]
Working as expected
