### ISSUE TITLE
BROKEN BUILDS

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#114]
Please validate why those are broken.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaiszIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3ca53ac2e3bb4caf0831db12eb806e8becff14d5/image.png)

This kitchen sink failure is also legitimate and needs to be looked into: https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/6229049722/job/16945104415

## PR
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/157

**Comment by sabina-talipova** [comment]
PR fixes the following broken builds:
- [silverstripe-webauthn-authenticator](https://github.com/silverstripe/silverstripe-webauthn-authenticator/actions/runs/6207781381)
- [recipe-kitchen-sink](https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/6229049722)
- [recipe-kitchen-sink](https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/6250446274)

**Comment by GuySartorelli** [comment]
PR merged.
