### ISSUE TITLE
Remove all TODO comments in the code

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#116]
There are a _ton_ of TODO comments in the code. It's a bad look, and it makes it a lot harder to find temporary TODO comments that are added during development, since a simple search for TODO is polluted by the existing ones.
What's more, a TODO comment in the codebase is never going to be actioned, so they should be replaced with GitHub issues we can track.

## Acceptance criteria
- Any TODO comment that _should_ be actioned has an issue in the appropriate repository
- All TODO comments are removed from the codebase for all supported and core modules

## PRs
- https://github.com/silverstripe/silverstripe-versionfeed/pull/92
- https://github.com/silverstripe/silverstripe-versioned/pull/418
- https://github.com/silverstripe/vendor-plugin/pull/70
- https://github.com/silverstripe/silverstripe-userforms/pull/1247
- https://github.com/silverstripe/silverstripe-segment-field/pull/92
- https://github.com/silverstripe/silverstripe-mfa/pull/515
- https://github.com/silverstripe/silverstripe-ldap/pull/63
- https://github.com/silverstripe/silverstripe-errorpage/pull/92
- https://github.com/silverstripe/silverstripe-contentreview/pull/215
- https://github.com/silverstripe/silverstripe-cms/pull/2898
- https://github.com/silverstripe/silverstripe-blog/pull/730
- https://github.com/silverstripe/silverstripe-behat-extension/pull/252
- https://github.com/silverstripe/silverstripe-assets/pull/577
- https://github.com/silverstripe/silverstripe-tagfield/pull/264
- https://github.com/silverstripe/silverstripe-subsites/pull/546
- https://github.com/silverstripe/silverstripe-securityreport/pull/70
- https://github.com/silverstripe/silverstripe-graphql/pull/556
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/176
- https://github.com/silverstripe/silverstripe-elemental/pull/1112
- https://github.com/silverstripe/cwp-core/pull/129
- https://github.com/silverstripe/silverstripe-restfulserver/pull/114
- https://github.com/silverstripe/silverstripe-admin/pull/1608
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1413
- https://github.com/silverstripe/silverstripe-framework/pull/11032
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/283
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/312

**Comment by sabina-talipova** [comment]
I plan to create a separate epic task for these purposes. This will make it easier to group and track the process of how TODO is performed.

**Comment by sabina-talipova** [comment]
TODO tickets list:
- https://github.com/silverstripe/silverstripe-versionfeed/issues/90
- https://github.com/silverstripe/silverstripe-versionfeed/issues/91
- https://github.com/silverstripe/silverstripe-versioned/issues/413
- https://github.com/silverstripe/silverstripe-versioned/issues/414
- https://github.com/silverstripe/silverstripe-versioned/issues/415
- https://github.com/silverstripe/silverstripe-versioned/issues/416
- https://github.com/silverstripe/silverstripe-versioned/issues/417

**Comment by GuySartorelli** [comment]
^ Note that a link to that line of code should use the "permanent" link, so that when your PRs to remove the todo comments are merged, we can still see the context that is required for the issue.

**Comment by GuySartorelli** [comment]
I have added comments requesting clarification on the following new issues:

- https://github.com/silverstripe/silverstripe-versioned/issues/413
- https://github.com/silverstripe/silverstripe-mfa/issues/514
- https://github.com/silverstripe/silverstripe-admin/issues/1601
- https://github.com/silverstripe/silverstripe-admin/issues/1598
- https://github.com/silverstripe/silverstripe-admin/issues/1596
- https://github.com/silverstripe/silverstripe-asset-admin/issues/1407
- https://github.com/silverstripe/silverstripe-campaign-admin/issues/281
- https://github.com/silverstripe/silverstripe-framework/issues/10996
- https://github.com/silverstripe/silverstripe-framework/issues/10997
- https://github.com/silverstripe/silverstripe-framework/issues/10998
- https://github.com/silverstripe/silverstripe-framework/issues/11028
- https://github.com/silverstripe/silverstripe-framework/issues/11027
- https://github.com/silverstripe/silverstripe-subsites/issues/543

**Comment by sabina-talipova** [comment]
@GuySartorelli , I updated the following issues and PRs:
- https://github.com/silverstripe/silverstripe-blog/pull/730
- https://github.com/silverstripe/silverstripe-subsites/pull/546
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1413
- https://github.com/silverstripe/silverstripe-framework/pull/11032
- https://github.com/silverstripe/silverstripe-admin/pull/1608
- https://github.com/silverstripe/cwp-core/pull/129
- https://github.com/silverstripe/silverstripe-subsites/pull/546
- https://github.com/silverstripe/silverstripe-graphql/pull/556
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/283
- https://github.com/silverstripe/silverstripe-subsites/issues/543
- https://github.com/silverstripe/silverstripe-admin/issues/1601
- https://github.com/silverstripe/silverstripe-framework/issues/11028
- https://github.com/silverstripe/silverstripe-framework/issues/10998
- https://github.com/silverstripe/silverstripe-framework/issues/10997
- https://github.com/silverstripe/silverstripe-framework/issues/10996
- https://github.com/silverstripe/silverstripe-framework/issues/10995
- https://github.com/silverstripe/silverstripe-asset-admin/issues/1407
- https://github.com/silverstripe/silverstripe-admin/issues/1596
- https://github.com/silverstripe/silverstripe-admin/issues/1598
-

**Comment by sabina-talipova** [comment]
And one new ticket for CMS6, probably.
- https://github.com/silverstripe/silverstripe-framework/issues/11036

**Comment by sabina-talipova** [comment]
New ticket:
- https://github.com/silverstripe/silverstripe-ldap/issues/64

**Comment by GuySartorelli** [comment]
PRs merged and new issues triaged
