### ISSUE TITLE
Some supported modules (e.g. colymba/gridfield-bulk-editing-tools) aren't in transifex

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#12]
Ran tx-translator on `4` sink using TX_PUSH=1 and TX_DEV_MODE=0

```
Finished generating 537 files
Pushing updated sources to transifex
Running tx push -s
Running tx push -s
PHP Fatal error:  Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command "tx push -s" failed.

Exit Code: 1(General error)

Working directory: /home/myuser/Sites/mylocalsite/vendor/colymba/gridfield-bulk-editing-tools

Output:
================
# Getting info about resources

gridfieldbulkeditingtools.js - Getting info
gridfieldbulkeditingtools.yml - Getting info
gridfieldbulkeditingtools.yml - Resource does not exist; creating
gridfieldbulkeditingtools.js - Resource does not exist; creating
gridfieldbulkeditingtools.js - Error while creating resource, 400, invalid: 'o::p:gridfieldbulkeditingtools' does not match '^o:[a-zA-Z0-9._-]+:p:[a-zA-Z0-9_-]+$'
gridfieldbulkeditingtools.yml - Error while creating resource, 400, invalid: 'o::p:gridfieldbulkeditingtools' does not match '^o:[a-zA-Z0-9._-]+:p:[a-zA-Z0-9_-]+$'


Error Output:
================
 in /home/myuser/Sites/mylocalsite/vendor/silverstripe/tx-translator/src/Translator.php:461
Stack trace:
#0 /home/myuser/Sites/mylocalsite/vendor/silverstripe/tx-translator/src/Translator.php(344): SilverStripe\TxTranslator\Translator->exec()
#1 /home/myuser/Sites/mylocalsite/vendor/silverstripe/tx-translator/src/Translator.php(63): SilverStripe\TxTranslator\Translator->transifexPushSource()
#2 /home/myuser/Sites/mylocalsite/vendor/silverstripe/tx-translator/scripts/translate.php(17): SilverStripe\TxTranslator\Translator->run()
#3 {main}
  thrown in /home/myuser/Sites/mylocalsite/vendor/silverstripe/tx-translator/src/Translator.php on line 461
```

.tx/config for colymba/gridfield-bulk-editing-tools had the old schema i.e. it's like `tx migrate` was never run on it
```
[main]
host = https://www.transifex.com

[gridfieldbulkeditingtools.yml]
file_filter = lang/<lang>.yml
minimum_perc = 0
source_file = lang/en.yml
source_lang = en
type = YML

[gridfieldbulkeditingtools.js]
file_filter = client/src/lang/<lang>.json
minimum_perc = 0
source_file = client/src/lang/en.json
source_lang = en
type = JSON
```

Attempting to manually run `tx migrate` on colymba/gridfield-bulk-editing-tools had the following error

```
tx migrate
Could not migrate resource `js`

Could not migrate resource `yml`

Migration ended! We have also created a backup file for your previous config file `/home/myuser/Sites/mylocalsite/vendor/colymba/gridfield-bulk-editing-tools/.tx/config_20230306174541.bak`.
```

## Notes
- It seems like the problem is caused by the module _not_ being in transifex
- We have other supported modules that are also not in transifex. These didn't cause problems because they lack the tx config, but they should be added as well.

## Acceptance criteria
- [x] All supported modules are in transifex
- [x] All supported modules have transifex config in the repository
- [x] All supported modules have their translations updated appropriately using the translations tool
- [x] UI strings are translatable for modules newly being added to transifex
- [x] Translation tool has been run against the newly translatable modules

## PRs
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/68
- https://github.com/silverstripe/cwp-agencyextensions/pull/86
- https://github.com/dnadesign/silverstripe-elemental-userforms/pull/68
- https://github.com/silverstripe/silverstripe-crontask/pull/76
- https://github.com/silverstripe/silverstripe-fulltextsearch/pull/343
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/87
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/188
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/359
- https://github.com/colymba/GridFieldBulkEditingTools/pull/232

**Comment by emteknetnz** [comment]
Only colymba/gridfield-bulk-editing-tools is an issue

gridfield-bulk-editing-tools is NOT listed in my transifex account, while other non-silverstripe modules are such as silverstripe-maintenance (bringyourownideas)

I think we should simply exclude colymba/gridfield-bulk-editing-tools from having translations run on it.  I tried this manually and every other module in sink worked fine.

**Comment by michalkleiner** [comment]
I'd say it might be worth figuring out what is wrong with the colymba module (it looks like the o:*:p* pattern is missing the o part), rather than introducing a whole new exclusion mechanism for things and throwing it under the bus.

**Comment by maxime-rainville** [comment]
We want to add the colymba module to transifex so it can be translated as well.

**Comment by GuySartorelli** [comment]
@maxime-rainville For `colymba/gridfield-bulk-editing-tools` specifically, it turns out this _is_ in transifex, but it's not under our account so we can't use the translation tool to update it:
https://explore.transifex.com/colymba/gridfieldbulkeditingtools/

Options:
1. Explicitly don't update translations for this module
2. Migrate the existing translations into a new transifex project in our organisation and update the `.tx/config` file in the repo
    - Not sure if there's some way to do this from transifex itself or if we'd have to just `tx push` the translations up
    - Probably have to check with colymba first - but given the repo readme has a call for maintainers I suspect they'd be okay with it

**Comment by GuySartorelli** [comment]
The following supported modules are missing `.tx/config` according to https://github.com/silverstripe/supported-modules/blob/gh-pages/modules.json
(note: I've crossed out any that just blatantly obviously shouldn't go in there)
- bringyourownideas/silverstripe-composer-update-checker
- ~composer/installers~
- cwp/agency-extensions
- cwp/cwp-pdfexport
- dnadesign/silverstripe-elemental-userforms
- silverstripe/auditor
- ~silverstripe/behat-extension~
- silverstripe/config
- silverstripe/content-widget
- silverstripe/crontask
- ~silverstripe/developer-docs~
- silverstripe/environmentcheck
- silverstripe/fulltextsearch
- silverstripe/graphql
- silverstripe/graphql-devtools
- silverstripe/html5
- silverstripe/hybridsessions
- ~silverstripe/installer~
- ~silverstripe/recipe-authoring-tools~
- ~silverstripe/recipe-blog~
- ~silverstripe/recipe-ccl~
- ~silverstripe/recipe-cms~
- ~silverstripe/recipe-collaboration~
- ~silverstripe/recipe-content-blocks~
- ~silverstripe/recipe-core~
- ~silverstripe/recipe-form-building~
- ~silverstripe/recipe-plugin~
- ~silverstripe/recipe-reporting-tools~
- ~silverstripe/recipe-services~
- ~silverstripe/recipe-solr-search~
- silverstripe/restfulserver
- silverstripe/sharedraftcontent
- silverstripe/tagfield
- silverstripe/textextraction
- ~silverstripe/vendor-plugin~
- symbiote/silverstripe-gridfieldextensions
- tijsverkoyen/akismet
- tractorcow/classproxy
- tractorcow/silverstripe-proxy-db
