### ISSUE TITLE
Rhino reports broken builds for PRs in some scenarios

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#120]
Rhino is reporting a broken build for the `5` branch of silverstripe/userforms. The link for that broken build is:
https://github.com/silverstripe/silverstripe-userforms/actions/runs/6242509675

That broken build is for a pull request, not for the actual `5` branch of silverstripe/userforms - so we need to update Rhino to explicitly ignore PRs/forks for any scenario where it's looking at broken GitHub Actions

**Comment by emteknetnz** [comment]
Have made code changes and deployed, will have a look tommorow morning to see if things worked as expected

**Comment by emteknetnz** [comment]
Seems to all be working now as intended
