### ISSUE TITLE
Use new prefix for translation commits

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#135]
We decided in [a retrospective](https://silverstripe.atlassian.net/wiki/spaces/CMS/pages/3007315988/2023-09-28+Retro) that translation commits (i.e. commits that explicitly update translations, usually done via [tx-translator](https://github.com/silverstripe/silverstripe-tx-translator/)) should have their own section in the changelog.

## Acceptance Criteria
- [x] All future translation commits use the `TLN` prefix.
- [x] tx-translator uses the new prefix when it makes commits
- [x] Cow is updated to put any commits with that prefix into a new section of the changelog
- [x] [The CMS 4 and CMS 5 docs](https://docs.silverstripe.org/en/5/contributing/code/#commit-messages) are updated to include the new prefix

## PRs
- https://github.com/silverstripe/silverstripe-tx-translator/pull/20
- https://github.com/silverstripe/cow/pull/248
- https://github.com/silverstripe/developer-docs/pull/395

**Comment by michalkleiner** [comment]
How about `LANG`?

**Comment by michalkleiner** [comment]
TRN would be better than TLN from my perspective. LNG would also be better and 3 characters. But yeah, let's move on 🤷.

**Comment by GuySartorelli** [comment]
PRs merged, translator tagged.
