### ISSUE TITLE
tx-translator - fix blank translation strings

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#14]
When the first run of tx-translator was done on this issue https://github.com/silverstripeltd/product-issues/issues/702 - there were a handful of PRs where there were blank strings for translations, e.g.

![image.png](https://images.zenhubusercontent.com/5dcb6f9e3c55460001028c42/b68f5d7e-71b8-4f1d-b54e-d02b94a44580)

These were spotted in the pull-requests for:
- ckan-registry
- session-manager
- versioned-admin
- silverstripe-fluent

However, when running a script to detect blank strings (see comment below) blanks strings were detected in 12 modules in kitchen-sink

This is bad because it means that the blank strings will be used for translations, rather than the original english source used as a fallback

Presumably in transifex there are blank strings for translations

### ACs
- [ ] Failing that, update silverstripe/tx-translator so that it won't output blank strings
- [ ] Create PRs to remove the blank strings - see comment below that has code start

## NOTE
- We'll have a stop gap measure just to remove the blank translation CMS side. We'll have a follow up card to handle cleaning up blank strings straight in transifex.
- We should consider whether to give the same treatment to "translated" strings that are identical to the English strings, which is also something that seems to happen a lot and ends up showing as 100% translated in transifex even though they're still in English.

## PRs - note all translation PRs were generated using the tx-translator PR
- https://github.com/silverstripe/silverstripe-tx-translator/pull/7
- https://github.com/silverstripe/silverstripe-ckan-registry/pull/286
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/102
- https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/36
- https://github.com/silverstripe/silverstripe-login-forms/pull/133
- https://github.com/silverstripe/silverstripe-mfa/pull/489
- https://github.com/silverstripe/silverstripe-security-extensions/pull/53
- https://github.com/silverstripe/silverstripe-session-manager/pull/138
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/114
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/278
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/131
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/789

**Comment by emteknetnz** [comment]
The following code makes a good start to identify where the blank strings are, you'll still need to actually delete the blank strings and create pull-requests

Install silverstripe/tx-translator first so that you have all the required symfony components

```php
<?php

use SilverStripe\Dev\BuildTask;
use GuzzleHttp\Client;
use Symfony\Component\Process\Process;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Console\Formatter\OutputFormatter;
use Symfony\Component\Yaml\Yaml;

class YmlCleanerTask extends BuildTask
{
    private array $modulePaths = [];
    private ?OutputFormatter $outputFormatter = null;
    private bool $versboseLogging = false;
    private array $hasBlank = [];

    public function run($request)
    {
        $this->outputFormatter = new OutputFormatter(true);
        $this->setModulePaths();
        foreach ($this->modulePaths as $modulePath) {
            $this->log("Scanning yml in $modulePath");
            foreach (glob("$modulePath/lang/*.yml") as $path) {
                $yaml = Yaml::parse(file_get_contents($path));
                $this->recurse($modulePath, $yaml);
            }
        }
        print_r(array_keys($this->hasBlank));
    }

    private function recurse(string $modulePath, array &$arr) {
        foreach ($arr as $k => $v) {
            if (is_array($v)) {
                $this->recurse($modulePath, $v);
            } else {
                if ($v == '') {
                    // $this->log("$k is blank");
                    $this->hasBlank[$modulePath] = true;
                }
            }
        }
    }

    private function setModulePaths(): void
    {
        $client = new Client();
        $url = 'https://raw.githubusercontent.com/silverstripe/supported-modules/gh-pages/modules.json';
        $body = (string) $client->request('GET', $url)->getBody();
        $supportedVendors = [];
        $supportedModules = [];
        foreach ($this->jsonDecode($body) as $data) {
            $supportedModules[] = $data['composer'];
            $supportedVendors[] = explode('/', $data['composer'])[0];
        }
        $vendorDir = dirname(dirname(__DIR__)) . '/vendor';
        foreach ($this->scandir($vendorDir) as $vendor) {
            if (!in_array($vendor, $supportedVendors)) {
                continue;
            }
            foreach ($this->scandir("$vendorDir/$vendor") as $module) {
                $modulePath = "$vendorDir/$vendor/$module";
                if (!in_array("$vendor/$module", $supportedModules)) {
                    continue;
                }
                if (!file_exists("$modulePath/.tx/config")) {
                    continue;
                }
                if (strpos($modulePath, 'colymba') !== false) {
                    continue;
                }
                $branch = $this->exec('git rev-parse --abbrev-ref HEAD', $modulePath);
                if (!preg_match('#^pulls/#', $branch)) {
                    throw new RuntimeException("Branch $branch in $modulePath is not a pr branch");
                }
                $this->modulePaths[] = $modulePath;
            }
        }
    }

    private function exec(string $command, ?string $cwd = null): string
    {
        $this->log("Running $command");
        $process = Process::fromShellCommandline($command, $cwd);
        // set a timeout of 5 minutes - tx pull operations may take a long time
        $process->setTimeout(300);
        $process->run();
        if (!$process->isSuccessful()) {
            throw new ProcessFailedException($process);
        }
        $output = trim($process->getOutput());
        $this->log($output, true);
        return $output;
    }

    private function log(string $message, bool $isVerbose = false): void
    {
        if ($isVerbose && !$this->versboseLogging) {
            return;
        }
        echo $this->outputFormatter->format($message) . "\n";
    }

    private function jsonDecode(string $str): array
    {
        $json = json_decode($str, true);
        if (json_last_error()) {
            $message = json_last_error_msg();
            throw new LogicException("Error json decoding $str: {$message}");
        }
        return $json;
    }

    private function scanDir(string $dir): array
    {
        return array_diff(scanDir($dir), ['.', '..']);
    }


}
```

**Comment by GuySartorelli** [comment]
Merged all

**Comment by GuySartorelli** [comment]
Oops reopening pending the fluent one being merged. Assigning to @maxime-rainville for that.

**Comment by GuySartorelli** [comment]
That's merged now
