### ISSUE TITLE
Set up permissions/protections for new community roles

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#143]
In order to introduce the new reviewer and refiner roles, we need to have some permissions and protections in place.

## Epic
- https://github.com/silverstripe/.github/issues/141

## Notes
- We need to decide if we will initially provide access to one repo, multiple repos, or _all_ repos.
  - We only need to add protection rules to the repo(s) we will initially be granting access to. Therefore it might make sense to try it out on a single repo first, make sure the rules work the way we want, and then grant more access when we're happy with it.
- We may decide to hold off on the refiner role for now and only proceed with the reviewer role until we've seen how that goes. In that case, we only need to do this for the one role for now.

## Acceptance Criteria
- A new group is created for the "refiner" role, with appropriate permissions and access to relevant repos
    - They must have "Triage" access only. See [the permissions matrix](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization)
- A new group is created for the "reviewer" role, with appropriate permissions and access to relevant repos
    - They must have "Write" access only. See [the permissions matrix](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization)
- The permission for all roles are documented in our official documentation and are in-line with our Risk Accessement.
- ~~Branch protection rules are added to relevant repos as rules set forth in the [proposal document](https://docs.google.com/document/d/187_CpvucX4cAa1uQZnzWoR5zAzfWC_I91D4KhsHsBiI/)~~
- ~~The new branch protections only restrict actions for the new roles~~
  - ~~If any rule can be demonstrated to meaningfully impact the CMS Squad workflow, a conversation is held to decide how to proceed.~~
- Any confluence pages or public doc that need to be updated are updated (e.g. steps for creating new repos might need to include adding access for these new groups)

## Related card
- https://github.com/silverstripe/.github/issues/198

## Note
- #144 needs to be done first.
- ACs related to branch protections are crossed off because those rules are handled in https://github.com/silverstripe/.github/issues/198

**Comment by maxime-rainville** [comment]
We concluded those are the branch and tag protection that should be enabled on all our supported repos.

## Branch protection
![image](https://github.com/silverstripe/.github/assets/1168676/8b85a9be-8faf-4a25-863a-3cff29de2331)

## Tag protection
![image](https://github.com/silverstripe/.github/assets/1168676/0838119f-73cb-4322-b23e-0df2e0ef754e)

**Comment by GuySartorelli** [comment]
Note that I won't be adding these roles to the recipes - changes to recipes should really be reviewed by the CMS Squad and/or core committers.

**Comment by GuySartorelli** [comment]
New groups made:
- [Peer Reviewers](https://github.com/orgs/silverstripe/teams/peer-reviewers) - added to all supported modules which aren't recipes
- [Contribution Refiners](https://github.com/orgs/silverstripe/teams/contribution-refiners) - added to all supported modules _including_ recipes

Docs updated in [setting up a new github repository](https://silverstripe.atlassian.net/wiki/spaces/CMS/pages/3030679981/Setting+up+a+new+GitHub+repository) page in confluence to reflect the need to add these new groups
