### ISSUE TITLE
Perform a risk analysis on the process for the new community roles

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#144]
Perform a risk analysis on the process for the new community roles.

We are thinking of granting more users some write access to our repos. We need to put in place controls to avoid compromising our security standards 

## Acceptance criteria
- Risk identified
- Risk are evaluated
- Controls are identified

## Epic
- https://github.com/silverstripe/.github/issues/141

## Helpful links
- [Maintainer guidelines](https://docs.silverstripe.org/en/5/project_governance/maintainer_guidelines/)
- [Original proposal for the new roles](https://docs.google.com/document/d/187_CpvucX4cAa1uQZnzWoR5zAzfWC_I91D4KhsHsBiI/edit#heading=h.4hnrvkz8c0lh)

## Risk assessment
Note that due to the vague language in the supporting documentation for these evaluations, my impact and likelihood assessments are fairly arbitrary at this stage.
- https://docs.google.com/spreadsheets/d/1uxP2FYRKb-0uxac_o4EnGWcqXc4op1iF3OlR9aAQb4k/ (Silverstripe employees only)

**Comment by GuySartorelli** [comment]
Requested changes made - also added "Automated testing" as an existing control

**Comment by emteknetnz** [comment]
Looks good to me - assigning to @maxime-rainville to have a look

**Comment by michalkleiner** [comment]
Can I get read access to the doc, please?

**Comment by maxime-rainville** [comment]
@michalkleiner I just granted you access.

**Comment by maxime-rainville** [comment]
@GuySartorelli I'm happy with the outcome. I would bump down the impact of XXX-YYY-R01 and XXX-YYY-R02.

They are other controls that should be considered like:
- requiring 2FA
- security audit
- regression testing.

**Comment by maxime-rainville** [comment]
Looks good. Can you create cards for the new controls that have not been implemented and add links in the spreadsheet for future reference.

**Comment by GuySartorelli** [comment]
As far as I can tell only the one issue is required, which already exists - I've added the link, and a note about why the other controls don't need issues.

**Comment by maxime-rainville** [comment]
Me happy.
