### ISSUE TITLE
Decommisson Addons

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#146]
We don't currently have the time to properly support Addons. The site currently has several broken features, report incorrect information for many module and is running outdated dependencies. The queued jobs running the site appear to be mostly broken.

We are in the process of a DotOrg rebuild, which may include equivalent functionality. In the mean time, the current addon website is actively armful.

## Alternative
VETOED
~Reduce complexity and storage by removing unnecessary stuff and only storing modules with versions compatible with supported versions of Silverstripe CMS.~
- ~https://github.com/silverstripe/addons.silverstripe.org/pull/288~

## Note
We should probably draft and approve the copy for the page we'll be redirecting to before doing any of the decommission steps.

## Acceptance criteria
- [x] addons.silverstripe.org redirect to a page on DotOrg.
- [x] The page explains why the site has been decommissioned and provide alternative means of searching for Silverstripe CMS module.
- [x] Addon site is decommissioned.
- [x] Addon stack is decommission.
- [x] This repo is archived with a notice on the readme.
- [ ] Addons is removed from the Silverstripe asset register (Max will do)
- [x] Removed from zenhub
- [x] Removed from elvis ([was never in it](https://github.com/silverstripe/github-issue-search-client/blob/master/src/repos.json))
- [x] Removed from rhino ([was never in it](https://github.com/silverstripe/rhino/blob/main/app/src/DataFetcher/Misc/Consts.php))

## PRs
- https://github.com/silverstripe/addons.silverstripe.org/pull/289
- https://github.com/silverstripeltd/silverstripe.org/pull/185
- https://github.com/silverstripe/developer-docs/pull/389

## Draft page on silverstripe.org (for peer review)
- Go to the admin section of silverstripe.org and search for "Composer installed modules"

**Comment by GuySartorelli** [comment]
I think instead of adding a whole new page, we should just replace the search box on https://www.silverstripe.org/software/addons with the new copy.

I also recommend this change to the copy:
```diff
- If you are looking for composer installed modules for Silverstripe CMS then you can search for them directly on Packagist using [this link](https://packagist.org/packages/silverstripe/admin?query=silverstripe).
+ If you are looking for composer installed modules for Silverstripe CMS then you can search for them [directly on Packagist](https://packagist.org/packages/silverstripe/admin?query=silverstripe).
```
Plus, of course, make it an actual link since markdown doesn't get evaluated.

**Comment by michalkleiner** [comment]
Is it actively harmful? Do people report that?
Can we just wait until the DotOrg rebuild is done and make a call after that?

**Comment by maxime-rainville** [comment]
For full context, we're in the process of rebuilding the DotOrg website. This feature will be reimplemented on the new website in some shape or form.

Analytics on the site is broken so I don't know how many people are actually using it. A lot of the features either don't work or give you misleading information e.g.: We don't use Travis for CI any more, but the Addons site is still looking for it as a marker of quality.

We got a warning that the broken queued jobs were consuming too much resources and would increased our hosting bill. We concluded fixing the broken jobs could be achieved by pulling back on the Addons feature set ... but that it would take at least a few days of dev time.

Given that the feature is meant to be reimplemented in a new site in a few month (:crossed_fingers:) and I didn't have clear indications that the site was actively useful to many people, I concluded it wasn't worth spending a few days of dev time fixing this.

**Comment by GuySartorelli** [comment]
(a few months is probably overly optimistic fyi)

**Comment by michalkleiner** [comment]
How much effort do you think it would be to throw a temporary CSS over things to hide what's misleading (or remove it from the template/components) and disable the queued jobs (what are they doing, do we know?) and trigger whatever needs triggered e.g. once a day or once a week from e.g. pingdom or such?

Just trying to see if there's a simple middle ground way where we won't shut this down for a a few months to a year+ without a replacement.

I'd be willing to spend a bit of time to look into this, I find the search there quite useful even without all the metrics and rating based on the obsolete module quality criteria.

I'm not saying we should keep this around forever if we think it's past its death, but it feels like a one of the "we don't know, we don't like it, we don't have data, so let's close it" decisions.

Obviously who funds it has the last say here, but my gut feel is it might be jumping the gun too quickly. For sure I don't have the visibility on what other priorities is this competing with etc.

Note - this is nothing against the squad obviously, I might be missing internal info/context or missed discussions on this etc., just trying to understand it more and not throw the baby out that easily.

**Comment by maxime-rainville** [comment]
The sad reality is we don't have the time to look after this properly ... which is why it's been sitting there in a half broken state for so long. Even if we decide to spend a couple days putting together a temporary half baked solution to bridge us over, we would still be stuck maintaining it. There's a non-trivial chance that we would have to spend more time patching Addons before the new DotOrg is ready.

Any time we spend fixing the current Addons site just look like we're throwing good money after bad to me.

The minimalist functionality is still there with Packagist search. At this stage, we're just arguing about whether we want a Silverstripe skin on top of the Packagist search. Pointing people at Packagist sounds like better bridging solution to me.

I would be fine with updating the [vanilla search box](https://www.silverstripe.org/software/addons/) to point to Packagist and make it clear we're sending you to another site. If we have a couple days of dev time to throw at this, I would rather spend it styling a simplified relay to the Packagist Search.

**Comment by GuySartorelli** [comment]
> I would be fine with updating the [vanilla search box](https://www.silverstripe.org/software/addons/) to point to Packagist and make it clear we're sending you to another site. If we have a couple days of dev time to throw at this, I would rather spend it styling a simplified relay to the Packagist Search.

The main advantage of the addons site is it has some search capability (i.e. searching based on the compatibility with given versions fo Silverstripe CMS) which just isn't possible with packagist's search. It wouldn't make sense to just point our search box at Packagist's search functionality.

I would support doing the search on our end and then all search results link to packagist to display the individual packages - that was essentially what the vetoed alternative was.

**Comment by maxime-rainville** [comment]
Got the internal Addons Space on our internal 

@emteknetnz I had a look at [the draft page](https://www.silverstripe.org/admin/pages/edit/show/3293). I find it a bit underwhelming.

I'm thinking we can probably repurpose big chunk of the page and point the Links to GitHub or Packagist. I'll have a quick go at it.

**Comment by maxime-rainville** [comment]
I created an updated Addons page in our Test environment:
- Applied this PR https://github.com/silverstripeltd/silverstripe.org/pull/185
- Updated the list of feature modules.
  - Replace SQLite3 with Elemental
  - Replace PostgreSQL with Focus Point
  - Replace Gridfield extensions with Queued Job
- Pointed all the links to GitHub, Packagist or business websites
- Updated the bottom "Learn more about Addons" to point relevant pages in the Doc.

**Comment by maxime-rainville** [comment]
@emteknetnz Maybe have a look at the extra PRs I've added. Once the changes are made tot he main DotOrg site, we can look at opening a service desk ticket.

**Comment by GuySartorelli** [comment]
> Replace Gridfield extensions with Queued Job

You should keep gridfield extensions, and remove sortable gridfield in favour of queued jobs.

**Comment by maxime-rainville** [comment]
@GuySartorelli Happy to make those adjustments when I replicate the changes on the prod site.

**Comment by emteknetnz** [comment]
@maxime-rainville has assigned back to you for deployment

**Comment by maxime-rainville** [comment]
Deployed the updated addons page. Contacted the service desk to redirect the URL and kill the old stack.

**Comment by GuySartorelli** [comment]
@maxime-rainville I've just realised there's almost certainly some docs pointing at the addons site. We should probably remove or replace those links.

**Comment by baukezwaan** [comment]
Don't know how familiar everyone is with https://ssmods.com/ which provides more-or-less the same functionality. 
Maybe useful for people who were relying on the search features of addons-website, which cannot be emulated in packagist.

**Comment by maxime-rainville** [comment]
Site has been decommissioned. CMS Squad members can [download an archive of the DB from GDrive](https://drive.google.com/file/d/1alYkVkwKmelW9LDDQvkkzvhvsZshsYW9/view?usp=sharing).
