### ISSUE TITLE
Broken Builds

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#148]
## [silverstripe/framework 4.13 (and 4) phpunit](https://github.com/silverstripe/silverstripe-framework/actions/runs/6645630539)

Also broken [in kitchen sink](https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/6656710867), and various other builds which run framework CI.

> 1) SilverStripe\Forms\Tests\HTMLEditor\HTMLEditorFieldTest::testFieldConfigSanitization
> Table is removed
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> ```diff
> -'<p>standard text</p><table><th><tr><td>Header</td></tr></th><tbody></tbody></table>'
> +'<p>standard text</p><table><th></th><tr><td>Header</td></tr><tbody></tbody></table>'
> ```
> 
> /home/runner/work/silverstripe-framework/silverstripe-framework/tests/php/Forms/HTMLEditor/HTMLEditorFieldTest.php:268
> /home/runner/work/silverstripe-framework/silverstripe-framework/vendor/bin/phpunit:122

## PR
- https://github.com/silverstripe/silverstripe-framework/pull/11038

**Comment by GuySartorelli** [comment]
PR merged. Reassigning back to Sabina to ensure builds go green.

**Comment by sabina-talipova** [comment]
All broken builds fixed, except one https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/6727627699/job/18285709977, but it looks like a new issue. 
I opened new tickets for this https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/6727627699/job/18285709977
