### ISSUE TITLE
Broken builds

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/.github#156]
## Description
There was 1 failure:

> 1) SilverStripe\Forms\Tests\HTMLEditor\HTMLEditorFieldTest::testFieldConfigSanitization
> Table is removed
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> ```diff
> -'<p>standard text</p><table><th></th><tr><td>Header</td></tr><tbody></tbody></table>'
> +'<p>standard text</p><table><tbody><tr><th></th></tr><tr><td>Header</td></tr></tbody><tbody></tbody></table>'
> ```
> /home/runner/work/recipe-kitchen-sink/recipe-kitchen-sink/vendor/silverstripe/framework/tests/php/Forms/HTMLEditor/HTMLEditorFieldTest.php:268
> phpvfscomposer:///home/runner/work/recipe-kitchen-sink/recipe-kitchen-sink/vendor/phpunit/phpunit/phpunit:106
/home/runner/work/recipe-kitchen-sink/recipe-kitchen-sink/vendor/bin/phpunit:118

## PR
- https://github.com/silverstripe/silverstripe-framework/pull/11040

**Comment by GuySartorelli** [comment]
Reassigning to Sabina to check the build goes green.

**Comment by sabina-talipova** [comment]
Broken build is green. 
- https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/6737794018

Close.
