### ISSUE TITLE
Broken merge-ups

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#159]
https://rhino.silverstripe.org/?t=merge-ups

The following broke as part of a merge-up, needs to be fixed
- https://github.com/silverstripe/silverstripe-admin/actions/runs/6845950895/job/18611924881

**Comment by sabina-talipova** [comment]
These two broken behat tests require some last updates for versioned module. They are related to this ticket: https://github.com/silverstripe/silverstripe-admin/issues/1544

**Comment by emteknetnz** [comment]
Perfect thanks, I ran merge-up action on silverstripe/versioned then reran linked build above, it went green
