### ISSUE TITLE
Add `@method` PHPDoc annotations for relations

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#163]
Currently there are no `@method` annotations for most relations in the Silverstripe CMS codebase. This means there is nothing telling developers which methods they can call to get those lists of relations, let alone what the type of list and items are for those relations. Developers have to refer to the source code to see what relations exist, and for which classes.

We should add `@method` annotations for all relations added on classes. [`Member` already has some of these](https://github.com/silverstripe/silverstripe-framework/blob/26c8c0f4f63783d8d1968941a388cc9e78726c1a/src/Security/Member.php#L44-L63) as an example.

We should add these using an automated tool, and add a CI component to validate that they are present. That way, as new relations are added, we will see if we've forgotten to add the `@method` annotations through failed CI jobs, and be able to add them at the time the new relation is added.

## Related
- https://github.com/silverstripe/silverstripe-framework/issues/11066

## Acceptance criteria
- `@method` annotations are added to class PHPDoc comments for all relations directly added on that class
  - This applies for all relations (`has_one`, `has_many`, `many_many`)
  - The return type for the method is correct for all `@method` annotations, including generics (e.g. `ManyManyList<SiteTree>` for a non-through type `many_many` to `SiteTree`, or `Image` for a `has_one` to `Image`)
- For relations added via extensions, the `@method` annotation is added to the extension class's PHPDoc
- ~~Missing `@method` annotations are picked up by CI (e.g. using phpstan or psalm)~~
- ~~Extra `@method` annotations that don't relate to anything on the class are picked up by CI (e.g. using phpstan or psalm)~~
- ~~Update PHP Codding standards to mentioned `@method` annotation.~~

## Notes
- Once this is merged, we should look at how the [API documentation](https://api.silverstripe.org/4/SilverStripe.html) is rendering annotation and do a follow card if needed.
- https://github.com/silverleague/silverstripe-ideannotator is one tool that can be used to add the `@method` annotations automagically.

## New issues created
- https://github.com/silverstripe/.github/issues/171

## Code writer
- https://github.com/emteknetnz/silverstripe-docblock-writer

## PRs
- ~~https://github.com/silverstripe/silverstripe-framework/pull/11092~~
- https://github.com/silverstripe/silverstripe-framework/pull/11093
- https://github.com/silverstripe/cwp-agencyextensions/pull/107
- https://github.com/silverstripe/cwp/pull/335
- https://github.com/silverstripe/silverstripe-elemental/pull/1125
- https://github.com/dnadesign/silverstripe-elemental-userforms/pull/84
- https://github.com/silverstripe/silverstripe-assets/pull/581
- https://github.com/silverstripe/silverstripe-blog/pull/734
- https://github.com/silverstripe/silverstripe-cms/pull/2909
- https://github.com/silverstripe/silverstripe-contentreview/pull/217
- https://github.com/silverstripe/silverstripe-documentconverter/pull/64
- https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/46
- https://github.com/silverstripe/silverstripe-externallinks/pull/114
- https://github.com/silverstripe/silverstripe-ldap/pull/65
- https://github.com/silverstripe/silverstripe-mfa/pull/521
- https://github.com/silverstripe/silverstripe-session-manager/pull/174
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/218
- https://github.com/silverstripe/silverstripe-siteconfig/pull/150
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/180
- https://github.com/silverstripe/silverstripe-subsites/pull/551
- https://github.com/silverstripe/silverstripe-taxonomy/pull/99
- https://github.com/silverstripe/silverstripe-userforms/pull/1257
- https://github.com/silverstripe/silverstripe-versioned/pull/428
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/509
- https://github.com/symbiote/silverstripe-queuedjobs/pull/413

**Comment by emteknetnz** [comment]
I've linked a PR for a new module, this will need to be merged before setting up the CI side of things

**Comment by emteknetnz** [comment]
Have added just one PR to framework for peer review for now, if this is OK will do all the other modules on sink

**Comment by GuySartorelli** [comment]
All linked PRs merged
