### ISSUE TITLE
PHP_CodeSniffer moved - we need to update our dependencies

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#168]
See https://github.com/squizlabs/PHP_CodeSniffer/issues/3932

tl;dr: We need to update our dependencies from `squizlabs/php_codesniffer` to `phpcsstandards/php_codesniffer`

There is one note in that issue that's relevant beyond just change the dependency:
> Note: I would recommend waiting to make the switch until the 3.8.0 release has been tagged. Watch releases on the new repo to automatically get notified of this. The changelog will contain the relevant information for making the switch.

## Notes
- The original maintainer of codesniffer has not commented on that issue at the time of creating this issue. There is a chance it's some elaborate phishing ploy or similar, though that seems unlikely.

**Comment by jrfnl** [comment]
Thank you for your support and your enthousiasm embracing the take-over of the PHP_CodeSniffer package.

In contrast to earlier information, arrangements are now being made to allow the package to continue under its original name on Packagist. The commit (in the new repo) to rename the package [has been reverted](https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/135).

Sorry for the confusion and thank you for understanding. I hope you'll enjoy the 3.8.0 release, which I expect to release this Friday.

P.S.: and no, this is not a phishing attempt, the repo change for PHP_CodeSniffer is real (and the original maintainer has confirmed this in the ticket now as well)

**Comment by GuySartorelli** [comment]
Awesome, thank you for that information. I'll close this issue as there's no longer any action for us to take.
