### ISSUE TITLE
tx-translator - run for fluent 7

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#17]
We did translations for fluent 4 - https://github.com/tractorcow-farm/silverstripe-fluent/pull/786 for CMS 4.13

However this won't get merged up to fluent 7 for CMS 5, so we'll need to run the translations just for this module only

We should be able to do this fairly easily after merging and merging up the other translation PRs https://github.com/silverstripeltd/product-issues/issues/702 to 5.0. Run tx-translator and you should automatically create a PR to fluent 7 (along with maybe a few other PRs if any new translations have been done)

## Acceptance criteria
- Run tx-translator and make sure all the Frluent 7 translation are working.

## PRs
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/790
- https://github.com/silverstripe/silverstripe-tx-translator/pull/8

**Comment by GuySartorelli** [comment]
merged
