### ISSUE TITLE
Validate @method docblock tag in CI

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#171]
Split off from https://github.com/silverstripe/.github/issues/163

## Acceptance criteria
- [x] Missing @method annotations are picked up by CI (e.g. using phpstan or psalm)
- [x] Extra @method annotations that don't relate to anything on the class are picked up by CI (e.g. using phpstan or psalm)
- [x] Update PHP Codding standards to mentioned @method annotation.
- [x] All supported modules run this new check in CI for their CMS 5 compatible versions (not CMS 4)

## Notes
- This will need to handle `get_extra_config()` in extensions (see https://github.com/silverstripe/silverstripe-framework/pull/11092#discussion_r1424737200)
- https://github.com/syntro-opensource/silverstripe-phpstan has some useful code to take inspiration from
- I've created https://github.com/silverstripe/silverstripe-standards for this to live in
- There's an error running phpstan against some classes in framework - see https://github.com/phpstan/phpstan/issues/10509

## PRs
**Note:** After merging the below, reassign to Guy so they can add this to packagist and roll it out to all the CMS 5 supported modules
- https://github.com/silverstripe/gha-generate-matrix/pull/76
- https://github.com/silverstripe/silverstripe-standards/pull/1
- https://github.com/silverstripe/rhino/pull/11
- https://github.com/silverstripe/module-standardiser/pull/31
- https://github.com/silverstripe/github-issue-search-client/pull/131
- https://github.com/silverstripe/developer-docs/pull/448
- https://github.com/silverstripe/module-standardiser/pull/33
- https://github.com/silverstripe/gha-ci/pull/101

## Module Standardiser PRs
**Note:** For any PR that had outstanding PHPLint issues, I've manually fixed whatever needed to be fixed as a _separate_ commit.
Note that these had to be run against the `5` (or equivalent) branches because the `@method` annotation rule doesn't work correctly against the codebase if the generic types aren't available - and those were merged into the `5` (or equivalent) branches.
- https://github.com/silverstripe/silverstripe-framework/pull/11121
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/210
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/80
- https://github.com/colymba/GridFieldBulkEditingTools/pull/265
- https://github.com/silverstripe/cwp-agencyextensions/pull/112
- https://github.com/silverstripe/cwp-starter-theme/pull/242
- https://github.com/silverstripe/developer-docs/pull/453
- https://github.com/silverstripe/cwp-watea-theme/pull/178
- https://github.com/silverstripe/silverstripe-elemental/pull/1141
- https://github.com/dnadesign/silverstripe-elemental-userforms/pull/87
- https://github.com/silverstripe/silverstripe-admin/pull/1669
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1438
- https://github.com/silverstripe/silverstripe-assets/pull/589
- https://github.com/silverstripe/silverstripe-auditor/pull/69
- https://github.com/silverstripe/silverstripe-blog/pull/741
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/293
- https://github.com/silverstripe/silverstripe-cms/pull/2919
- https://github.com/silverstripe/silverstripe-config/pull/109
- https://github.com/silverstripe/silverstripe-contentreview/pull/222
- https://github.com/silverstripe/silverstripe-crontask/pull/85
- https://github.com/silverstripe/silverstripe-documentconverter/pull/68
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/133
- https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/49
- https://github.com/silverstripe/silverstripe-environmentcheck/pull/98
- https://github.com/silverstripe/silverstripe-errorpage/pull/97
- https://github.com/silverstripe/silverstripe-externallinks/pull/119
- https://github.com/silverstripe/silverstripe-graphql/pull/570
- https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/97
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/98
- https://github.com/silverstripe/silverstripe-iframe/pull/79
- https://github.com/silverstripe/silverstripe-installer/pull/365
- https://github.com/silverstripe/silverstripe-ldap/pull/69
- https://github.com/silverstripe/silverstripe-lumberjack/pull/139
- https://github.com/silverstripe/silverstripe-mimevalidator/pull/71
- https://github.com/silverstripe/silverstripe-realme/pull/130
- https://github.com/silverstripe/silverstripe-session-manager/pull/180
- https://github.com/silverstripe/recipe-authoring-tools/pull/32
- https://github.com/silverstripe/recipe-blog/pull/48
- https://github.com/silverstripe/recipe-cms/pull/81
- https://github.com/silverstripe/recipe-collaboration/pull/28
- https://github.com/silverstripe/recipe-content-blocks/pull/37
- https://github.com/silverstripe/recipe-core/pull/91
- https://github.com/silverstripe/recipe-form-building/pull/31
- https://github.com/silverstripe/recipe-plugin/pull/38
- https://github.com/silverstripe/recipe-reporting-tools/pull/40
- https://github.com/silverstripe/recipe-services/pull/31
- https://github.com/silverstripe/silverstripe-registry/pull/92
- https://github.com/silverstripe/silverstripe-reports/pull/174
- https://github.com/silverstripe/silverstripe-restfulserver/pull/118
- https://github.com/silverstripe/silverstripe-securityreport/pull/74
- https://github.com/silverstripe/silverstripe-segment-field/pull/97
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/224
- https://github.com/silverstripe/silverstripe-siteconfig/pull/154
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/80
- https://github.com/silverstripe/silverstripe-spamprotection/pull/110
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/184
- https://github.com/silverstripe/silverstripe-subsites/pull/556
- https://github.com/silverstripe/silverstripe-tagfield/pull/279
- https://github.com/silverstripe/silverstripe-taxonomy/pull/104
- https://github.com/silverstripe/silverstripe-textextraction/pull/88
- https://github.com/silverstripe/silverstripe-userforms/pull/1264
- https://github.com/silverstripe/vendor-plugin/pull/73
- https://github.com/silverstripe/silverstripe-versioned/pull/433
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/321
- https://github.com/silverstripe/silverstripe-versionfeed/pull/98
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/518
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/380
- https://github.com/symbiote/silverstripe-multivaluefield/pull/102
- https://github.com/symbiote/silverstripe-queuedjobs/pull/418
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/821
- https://github.com/silverstripe/silverstripe-mfa/pull/526
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/144
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/168
- https://github.com/silverstripe/silverstripe-login-forms/pull/164
- https://github.com/silverstripe/silverstripe-dynamodb/pull/59
- https://github.com/silverstripe/gha-ci/pull/103
- https://github.com/silverstripe/markdown-php-codesniffer/pull/7
- https://github.com/silverstripe/silverstripe-standards/pull/3

**Comment by GuySartorelli** [comment]
In order for the types to correctly resolve with PHPStan analysis of the existing `@method` annotations, we need generics in place. This is necessary to double check that the existing annotations are correct.

**Comment by GuySartorelli** [comment]
@emteknetnz seems like you're reviewing this so assigning to you
