### ISSUE TITLE
api.silverstripe.org is down

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#179]
<img width="957" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2VrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63b02aae70b7f9e3fb30330c6a9c5c8cdf93107c/image.png" alt="image.png" />

**Comment by GuySartorelli** [comment]
Did a full deployment and it's fixed.
