### ISSUE TITLE
Handle CVE-less security issue

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#18]
We will occasionally have to deal with a security issue for which we can't request a CVE.

We [can't request CVE on behalf of third parties](https://www.cve.org/ResourcesSupport/AllResources/CNARules#section_7-2_how_many_vulnerabilities). This will affect us where we bundle those dependencies in our own modules directly.

## Acceptance criteria
- We establish a reasonable criteria for releasing security notice that we inherit directly from the third party
- The criteria should consider how to handle vulnerabilities for which the third party has issued CVE and has NOT issued a CVE.
- We should still preserve the ability to apply our own Silverstripe CMS CVSS score
- Criteria should be documented in our official doc.
- COW should be updated to be able to register security commits without a CVE.

## Notes
The following pages in our doc will need to be updated:
- [Release process](https://docs.silverstripe.org/en/4/contributing/release_process/)
- [Managing Security issue](https://docs.silverstripe.org/en/4/contributing/managing_security_issues/)
- [Commit messages](https://docs.silverstripe.org/en/4/contributing/code/#commit-messages)

There may be more.

**Comment by GuySartorelli** [comment]
We decided that these should be given an `SS` code, e.g. `SS-2023-001`.
The relevant documentation still needs to be updated.

**Comment by GuySartorelli** [comment]
Docs updated as part of the contributing docs work.
