### ISSUE TITLE
Move php extension config to yml

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#185]
While peer reviewing https://github.com/silverstripe/silverstripe-framework/issues/11066 I noticed that the vast majority of extension config is in yml, will a small amount in php using `private static $extensions`.

It would be preferable to if ALL extension config was in a single place rather than two possible places.  This make it easier to search for extensions e.g. filter by yml files in vscode

We should standarise putting it all in yml because:
- The vast majority of it is already there
- We'll never be able to use PHP only, because many extensions are in optional modules which can only be added via yml i.e. the class having the extension added to it isn't aware of the optional module.

**Comment by GuySartorelli** [comment]
I disagree with this.

I think that extension config that is _inherently necessary for a class to function as expected_ should be in the class itself.
e.g. `SiteTree` is _always_ expected to be versioned, so we have the versioned extension declared in the class directly.

This implies those extensions should never be removed - whereas extensions added via yaml should be allowed to be removed without negative impacts.

**Comment by madmatt** [comment]
Do we need to document this pseudo-rule somewhere so it becomes more standard? I think I tend to agree with you Guy but it only makes sense if it's accurate.

**Comment by emteknetnz** [comment]
I've spun up a new issue https://github.com/silverstripe/.github/issues/186 - I've put it into our internal backlog so at some point we'll decide if we want to do this.
