### ISSUE TITLE
Broken Builds and failed merge-ups

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#195]
Rhino shows some [broken builds](https://rhino.silverstripe.org/?t=builds) and [failed mergeups](https://rhino.silverstripe.org/?t=merged-prs).
Some may just be intermittent behat failures, but some might be legitimate.

1. https://github.com/silverstripe/recipe-core/actions/runs/7854511547/job/21501300422
    > ```
    > 1) SilverStripe\Forms\Tests\HTMLEditor\HTMLEditorFieldTest::testGetAttributes
    > Exception: If the silverstripe/admin module is not installed you must set the TinyMCE path in SilverStripe\Forms\HTMLEditor\TinyMCEConfig.base_dir
    > ```

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11136
- https://github.com/silverstripe/silverstripe-admin/pull/1679

**Comment by GuySartorelli** [comment]
Merge-ups resolved.
Most of the CI failures were just intermittent behat silliness but there were a couple of real ones.

**Comment by emteknetnz** [comment]
Have merged PRs, assigned back to confirm that builds are passing

**Comment by GuySartorelli** [comment]
All passing
