### ISSUE TITLE
Remove supported badges from unsupported repos

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#197]
Because module standardiser will only update supported repos, it fail to remove supported badges from the README.md of unsupported repos because it won't run script on it

Ckan registry still has a supported badge on it despite it [not being supported for cms 5](https://github.com/silverstripe/supported-modules/blob/5/modules.json), though it is [supported for cms 4](https://github.com/silverstripe/supported-modules/blob/4/modules.json)

## To decide

First we need to clarify that we indeed should not display the supported badge on things that are only supported for cms 4. If we do still want a badge then it should be a different badge IMO that says supported for security only

## Acceptance criteria
- [ ] Update module-standardiser to remove the supported badge from unsupported modules.
- [ ] Only the CMS 5 branches should be updated.
- [ ] All modules that lost their supported status in CMS 5 should loose their badge.

## PRs
- https://github.com/silverstripe/module-standardiser/pull/58
- https://github.com/silverstripe/cwp/pull/338
- https://github.com/silverstripe/cwp-core/pull/132
- https://github.com/silverstripe/cwp-search/pull/62
- https://github.com/silverstripe/silverstripe-akismet/pull/49
- https://github.com/silverstripe/silverstripe-ckan-registry/pull/312
- https://github.com/silverstripe/comment-notifications/pull/58
- https://github.com/silverstripe/silverstripe-comments/pull/389
- https://github.com/silverstripe/silverstripe-content-widget/pull/39
- https://github.com/silverstripe/silverstripe-crontask/pull/90
- https://github.com/silverstripe/silverstripe-fulltextsearch/pull/358
- https://github.com/silverstripe/silverstripe-graphql-devtools/pull/54
- https://github.com/silverstripe/silverstripe-postgresql/pull/151
- https://github.com/silverstripe/silverstripe-sqlite3/pull/76
- https://github.com/silverstripe/sspak/pull/97
- https://github.com/silverstripe/silverstripe-widgets/pull/212

**Comment by maxime-rainville** [comment]
I'm happy to remove badges once support is dropped by the latest major.

I guess if we want to be especially formal about this, we could remove the badge from the default branch, but keep it on the branches where the module was supported.

**Comment by GuySartorelli** [comment]
PRs merged
