### ISSUE TITLE
Apply branch protection to our repos

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#198]
## Acceptance criteria

- Branch protections are applied to patch release branch, minor release branches and major release branches.
- Ability to manually tag releases is restricted.
- Ability for CI to auto-merge up and auto-tag patch releases is retained.
- Ability for COW to tag releases is retained and release process is updated accordingly.
- Module standardiser is updated so it can set up branch protection.
- Documentation about repository management is updated to reflect these changes

## Notes (already decided)
- Who should have manual tagging access?
    - People doing releases (aka Guy and Steve)
- Which rules are included in "branch protections"?
    - See screenshot below
 
## Related card
- https://github.com/silverstripe/.github/issues/196
- https://github.com/silverstripe/.github/issues/143

## PRs
- https://github.com/silverstripe/module-standardiser/pull/53
- https://github.com/silverstripe/developer-docs/pull/522

**Comment by maxime-rainville** [comment]
Still need to identify exactly what branch protection we need and to which groups  they should apply.

**Comment by maxime-rainville** [comment]
We concluded those are the branch and tag protection that should be enabled on all our supported repos.

## Branch protection
![image](https://github.com/silverstripe/.github/assets/1168676/8b85a9be-8faf-4a25-863a-3cff29de2331)

## Tag protection
![image](https://github.com/silverstripe/.github/assets/1168676/0838119f-73cb-4322-b23e-0df2e0ef754e)

**Comment by emteknetnz** [comment]
github-actions seems to be pretty easy to handle, it seems like have the "Organisation admin" role meaning we can use that (or the lower "Repository admin", "Maintain", or "Write" roles) as a bypass for any rulesets

I tested this by using the gha-tag-release action on a test repo on my personal account that has a tag ruleset applied to it. Without the bypass I got a 422, though with the "Organisation admin" role as a bypass the github-actions user was able to do its thing

**Comment by emteknetnz** [comment]
I've created a PR to update module standardiser to update the rulesets, though I haven't run it yet since we probably need to update all the users first

Once we run the new module-standardariser ruleset command, PRs will now requires to 2 approvers to merge unless your role has enough permissions to bypass

**Comment by GuySartorelli** [comment]
Looks like @maxime-rainville probably needs to take a look and decide whether the core committer stuff should be removed from this card (probably handle it in silverstripeltd/product-issues#842 instead).

We don't want to do part of a card, and then move the card into refinement.

**Comment by maxime-rainville** [comment]
Can core commiter still approved and merge things with branch protection on? Do they need to a second approver?

**Comment by GuySartorelli** [comment]
Right now core committers are owners, so they can do whatever the heck they want. 😅

**Comment by maxime-rainville** [comment]
Me satisfied.

**Comment by maxime-rainville** [comment]
Actually lets apply branch protection first.

**Comment by emteknetnz** [comment]
Having a second look, there's also the "regular branch protection" that's already on all the supported repos - e.g. https://github.com/silverstripe/silverstripe-admin/settings/branches

I think this should remain as is with the the existing pattern match to prevent accidental deletion of existing 2 / 2.1 style branches. If we don't keep it then admins can accidentally delete the branches despite the new branch rulesset that restricts deletion because admins will have bypass permissions.

Even without the checking the tickbox "Do not allow bypassing the above settings - The above settings will apply to administrators and custom roles with the "bypass branch protections" permission.", I was unable to delete a `1` branch on a test repo that I setup on my personal account where I would have been an admin. On that repo I had a new branch ruleset that restricted deletions though it had a bypass for "Repository admin"

**Comment by GuySartorelli** [comment]
Yup, I think the implication is that this card is just to add _additional_ branch protection on top of whatever is already there.

**Comment by emteknetnz** [comment]
Annoyingly there isn't a REST api endpoint available to update the old fashioned branch protection using an fnmatch pattern, you can only update it for existing branches.

I've gone and manually checked and updated branch protection for the list of supported modules in repositories.json (all 138 of them) and ensured there is branch protection.  However I was unable to access the repo settings to do this for all o f the non-silverstripe account repos such as symbiote, so presumably we probably also won't be able to add the branch/tag rulesets for them via the API either

**Comment by GuySartorelli** [comment]
@emteknetnz I'm confused about the status of this now - there's a PR but you can't automate it and have already applied the branch protection manually?

> Annoyingly there isn't a REST api endpoint available to update the old fashioned branch protection using an fnmatch pattern, you can only update it for existing branches.

Does this mean we can't automate applying branch protection rules at all?

> However I was unable to access the repo settings to do this for all o f the non-silverstripe account repos such as symbiote, so presumably we probably also won't be able to add the branch/tag rulesets for them via the API either

So are all of the branch protection rules applied now?

**Comment by emteknetnz** [comment]
There are two types of branch protection

1) Regular branch protection, which is what we have now e.g. https://github.com/silverstripe/silverstripe-framework/settings/branches - these are what I just manually updated
2) Branch protection rulesets - which is what module-standardiser will update via the REST API - it's what the PR is for - it will add the rulesets for branches and tags here https://github.com/silverstripe/silverstripe-framework/settings/rules

**Comment by GuySartorelli** [comment]
Reassigning to Steve to run the new command in standardiser

**Comment by emteknetnz** [comment]
Have run module-standariser, went smoothly
