### ISSUE TITLE
Update gha repos and rhino for CMS 6

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#199]
Spun off from https://github.com/silverstripe/.github/issues/191

## Acceptance criteria
- [x] gha-ci uses installer 6.x-dev for CMS 6 branches
- [x] gha-dispatch-ci runs triggers CI runs on 4.13 and 5, and not 6
- [x] gha-merge-up merges up up correctly from 4.13 all the way to 6
- [x] Rhino shows builds from 4.13 up to 6
- [x] Rhino shows merge-ups from 4.13 up to 6
- [ ] CI for all commercially supported modules passes on the next major branch for all commercially supported modules - EXCEPT for any failures that are already happening on the CMS 5 branch.

## Notes
- We shouldn't need a PR for gha-merge-up because based on [this existing unit test](https://github.com/silverstripe/gha-merge-up/blob/1/tests/BranchesTest.php#L39) it should merge-up to CMS 6 already

## PRs
- https://github.com/silverstripe/rhino/pull/12
- https://github.com/silverstripe/gha-generate-matrix/pull/81
- https://github.com/silverstripe/gha-dispatch-ci/pull/12
- https://github.com/silverstripe/gha-generate-matrix/pull/82
- https://github.com/silverstripe/gha-ci/pull/109
- https://github.com/silverstripe/recipe-testing/pull/17
- https://github.com/silverstripe/recipe-blog/pull/50
- https://github.com/dnadesign/silverstripe-elemental-userforms/pull/90
- https://github.com/silverstripe/silverstripe-graphql/pull/576
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/136
- https://github.com/silverstripe/recipe-content-blocks/pull/39
- https://github.com/silverstripe/silverstripe-installer/pull/367
- https://github.com/silverstripe/silverstripe-auditor/pull/71
- https://github.com/silverstripe/recipe-kitchen-sink/pull/54
- https://github.com/silverstripe/silverstripe-blog/pull/746
- https://github.com/silverstripe/silverstripe-versionfeed/pull/101
- https://github.com/silverstripe/recipe-kitchen-sink/pull/55

**Comment by GuySartorelli** [comment]
Deploying rhino changes to production now (I've checked they're good in UAT).
After that's deployed I'll rerun the jobs for two affected tabs.

**Comment by GuySartorelli** [comment]
Rhino deployment to production was successful and the tabs are up to date with the new functionality.

**Comment by GuySartorelli** [comment]
Assigning back to steve to check everything's working as expected

**Comment by GuySartorelli** [comment]
More PRs merged. Assigning back to steve to check everything's working as expected
