### ISSUE TITLE
Update the contents of the README.md files with the information corresponding to the current version of CMS5

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/.github#20]
## Description
Content of README.md doesn't provided correct information corresponding to the current version CMS5

## AC's
- [x] Update instruction how to install module
- [x] Update links to the Silverstripe Documentation v5
- [x] remove Requirements section, if exist (those details are in composer.json)
- [ ] All modules have been updated to mention CMS5
- [ ] Modules who have outside maintainers list those maintainers.

## NOTE FOR PEER REVIEW

Don't just check the changes for this one - also double check that there hasn't been any accidentally duplicated information, or information that needs to be updated which was missed.

## PRs
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/195
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/72
- https://github.com/colymba/GridFieldBulkEditingTools/pull/233
- https://github.com/silverstripe/cwp-agencyextensions/pull/91
- https://github.com/silverstripe/cwp/pull/329
- https://github.com/silverstripe/cwp-core/pull/124
- https://github.com/silverstripe/cwp-search/pull/61
- https://github.com/silverstripe/cwp-starter-theme/pull/222
- https://github.com/silverstripe/cwp-watea-theme/pull/164
- https://github.com/silverstripe/silverstripe-elemental/pull/1053
- https://github.com/dnadesign/silverstripe-elemental-userforms/pull/72
- https://github.com/lekoala/silverstripe-debugbar/pull/149
- https://github.com/silverstripe/silverstripe-admin/pull/1502
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1350
- https://github.com/silverstripe/silverstripe-assets/pull/548
- https://github.com/silverstripe/silverstripe-auditor/pull/52
- https://github.com/silverstripe/silverstripe-comments/pull/368
- https://github.com/silverstripe/silverstripe-config/pull/85
- https://github.com/silverstripe/silverstripe-content-widget/pull/38
- https://github.com/silverstripe/silverstripe-contentreview/pull/196
- https://github.com/silverstripe/silverstripe-documentconverter/pull/44
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/106
- https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/38
- https://github.com/silverstripe/silverstripe-environmentcheck/pull/88
- https://github.com/silverstripe/silverstripe-errorpage/pull/83
- https://github.com/silverstripe/silverstripe-externallinks/pull/100
- https://github.com/silverstripe/silverstripe-behat-extension/pull/240
- https://github.com/silverstripe/silverstripe-blog/pull/707
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/264
- https://github.com/silverstripe/silverstripe-ckan-registry/pull/291
- https://github.com/silverstripe/silverstripe-cms/pull/2850
- https://github.com/silverstripe/comment-notifications/pull/56
- https://github.com/silverstripe/silverstripe-framework/pull/10758
- https://github.com/silverstripe/silverstripe-fulltextsearch/pull/347
- https://github.com/silverstripe/silverstripe-graphql/pull/532
- https://github.com/silverstripe/silverstripe-graphql-devtools/pull/49
- https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/77
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/91
- https://github.com/silverstripe/silverstripe-iframe/pull/70
- https://github.com/silverstripe/silverstripe-installer/pull/353
- https://github.com/silverstripe/silverstripe-ldap/pull/55
- https://github.com/silverstripe/silverstripe-lumberjack/pull/121
- https://github.com/silverstripe/silverstripe-mimevalidator/pull/65
- https://github.com/silverstripe/silverstripe-postgresql/pull/147
- https://github.com/silverstripe/silverstripe-realme/pull/99
- https://github.com/silverstripe/silverstripe-session-manager/pull/143
- https://github.com/silverstripe/recipe-authoring-tools/pull/27
- https://github.com/silverstripe/recipe-blog/pull/41
- https://github.com/silverstripe/recipe-ccl/pull/9
- https://github.com/silverstripe/recipe-collaboration/pull/23
- https://github.com/silverstripe/recipe-content-blocks/pull/32
- https://github.com/silverstripe/recipe-form-building/pull/26
- https://github.com/silverstripe/recipe-plugin/pull/33
- https://github.com/silverstripe/recipe-reporting-tools/pull/35
- https://github.com/silverstripe/recipe-services/pull/26
- https://github.com/silverstripe/recipe-solr-search/pull/19
- https://github.com/silverstripe/silverstripe-registry/pull/83
- https://github.com/silverstripe/silverstripe-reports/pull/162
- https://github.com/silverstripe/silverstripe-restfulserver/pull/108
- https://github.com/silverstripe/silverstripe-securityreport/pull/65
- https://github.com/silverstripe/silverstripe-segment-field/pull/80
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/194
- https://github.com/silverstripe/silverstripe-siteconfig/pull/139
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/64
- https://github.com/silverstripe/silverstripe-spamprotection/pull/96
- https://github.com/silverstripe/silverstripe-sqlite3/pull/72
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/169
- https://github.com/silverstripe/silverstripe-subsites/pull/521
- https://github.com/silverstripe/silverstripe-tagfield/pull/239
- https://github.com/silverstripe/silverstripe-taxonomy/pull/91
- https://github.com/silverstripe/silverstripe-textextraction/pull/82
- https://github.com/silverstripe/silverstripe-userforms/pull/1204
- https://github.com/silverstripe/vendor-plugin/pull/67
- https://github.com/silverstripe/silverstripe-versioned/pull/404
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/284
- https://github.com/silverstripe/silverstripe-versionfeed/pull/84
- https://github.com/silverstripe/silverstripe-widgets/pull/200
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/487
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/362
- https://github.com/symbiote/silverstripe-multivaluefield/pull/95
- https://github.com/symbiote/silverstripe-queuedjobs/pull/403
- https://github.com/tractorcow/classproxy/pull/6
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/794
- https://github.com/silverstripe/silverstripe-mfa/pull/495
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/118
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/135
- https://github.com/silverstripe/silverstripe-login-forms/pull/138

**Comment by GuySartorelli** [comment]
The PRs for this issue were automatically generated using the below script. Some were then manually modified to resolve problems that couldn't be caught by the automation.

The script was put at the root of a silverstripe CMS 5.0 project.

```php
<?php

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} else {
    throw new LogicException("autoload.php not found");
}

use Symfony\Component\Filesystem\Path;


function print_pr_urls($pr_urls) {
    echo "\rPR urls:\n";
    foreach ($pr_urls as $pr_url) {
        $pr_url = str_replace('api.github.com/repos', 'github.com', $pr_url);
        $pr_url = str_replace('/pulls/', '/pull/', $pr_url);
        echo "- $pr_url\n";
    }
}

function create_ch($url, $post_body = '')
{
    $github_token = 'YOUR_TOKEN_HERE';
    $github_user = cmd('echo $(git config --list | grep user.name) | sed -e "s/user.name=//"');
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        'Accept: application/vnd.github.v3+json',
        "Authorization: token $github_token",
        "User-Agent: $github_user"
    ]);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    if ($post_body) {
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $post_body);
    }
    return $ch;
}

function cmd($cmds)
{
    if (!is_array($cmds)) {
        $cmds = [$cmds];
    }
    return trim(shell_exec(implode(' && ', $cmds)));
}


// supported-modules.json comes from
// https://raw.githubusercontent.com/silverstripe/supported-modules/gh-pages/modules.json
// with anything we've dropped for CMS 5 removed
$modules = json_decode(file_get_contents('supported-modules.json'), true);

$parent_issue = 'https://github.com/silverstripe/.github/issues/20';
$pr_title = 'DOC Update README.md for CMS 5';
$pr_branch = 'pulls/*/cms5-readme';
$create_pr = true; // set to false to dry-run
$pr_urls = [];
$failed = [];

foreach ($modules as $module) {
    // echo 'Looking at ' . $module['composer'] . PHP_EOL;
    $moduleName = $module['composer'];
    list($account, $repo) = explode('/', $module['github']);

    // Get path to module dir
    $modulePath = Path::join(__DIR__, 'vendor', $moduleName);
    if (!is_dir($modulePath)) {
        $modulePath = Path::join(__DIR__, 'themes', str_replace('-theme', '', explode('/', $moduleName)[1]));
        if (!is_dir($modulePath)) {
            $failed[$moduleName] = "Not installed";
            continue;
        }
    }

    // Get path to readme
    $readmePath = Path::join($modulePath, 'README.md');
    if (!is_file($readmePath)) {
        $readmePath = Path::join($modulePath, 'readme.md');
        if (!is_file($readmePath)) {
            $failed[$moduleName] = 'README.md missing';
            continue;
        }
    }
    $readmeContent = $origContent = file_get_contents($readmePath);

    // Check for opening title
    if (!preg_match('/^#+\h+\w+[\h\w]+/', $readmeContent)) {
        $failed[$moduleName] = 'Title missing';
    }

    // Add or update installation section
    $installationInstructions = <<<INSTALL
        ## Installation

        ```sh
        composer require {$moduleName}
        ```\n\n
        INSTALL;
    if (preg_match('/^#+\h+Installation\h*$/m', $readmeContent)) {
        $readmeContent = preg_replace('/^#+\h+Installation\h*\v[\w\W]*?^(?=#)/m', $installationInstructions, $readmeContent);
    } else {
        $readmeContent = preg_replace('/^#+\h+\w+[\h\w]+\v[\w\W]*?^(?=#)/m', '$0' . $installationInstructions, $readmeContent, 1);
    }

    // Remove requirements section
    if (preg_match('/^#+\h+Requirements?\h*$/m', $readmeContent)) {
        $readmeContent = preg_replace('/^#+\h+Requirementss?\h*\v[\w\W]*?^(?=#)/m', '', $readmeContent);
    }

    // Check for mentions of versions section
    if (preg_match('/(\d\.x|cms \d|silverstripe \d)/mi', $readmeContent)) {
        $failed[$moduleName] = 'Version mentioned';
    }

    // Fix doc links to be version agnostic
    $linkRegex = '#(https://(userhelp|docs)\.silverstripe\.org/en)/\d#m';
    $readmeContent = preg_replace($linkRegex, '$1', $readmeContent);

    if ($readmeContent !== $origContent) {
        // echo 'Some change happened' . PHP_EOL;
        file_put_contents($readmePath, $readmeContent);
    }

    if (!$create_pr) {
        continue;
    }

    $diff = cmd([
        "cd $modulePath",
        "git add " . basename($readmePath),
        "git diff --cached",
        "cd - > /dev/null"
    ]);

    if ($diff == '') {
        echo "No diff for $moduleName, continuing\n";
        continue;
    }

    $current_branch = cmd([
        "cd $modulePath",
        'git rev-parse --abbrev-ref HEAD',
        "cd - > /dev/null"
    ]);
    if (strpos($current_branch, '/') !== false) {
        $failed[$moduleName] = 'On a non-default branch';
        continue;
    }
    $new_branch = str_replace('*', $current_branch, $pr_branch);

    cmd([
        "cd $modulePath",
        "git checkout -b $new_branch",
        "git commit -m '$pr_title'",
        "git remote add ccs git@github.com:creative-commoners/$repo",
        "git push ccs $new_branch",
        "cd - > /dev/null"
    ]);

    $url_new_branch = urlencode($new_branch);
    // https://docs.github.com/en/rest/pulls/pulls#create-a-pull-request
    $body = implode("\\r\\n\\r\\n", [
        '## Issue', "- $parent_issue",
    ]);
    $post_body = <<<EOT
    {
        "title": "$pr_title",
        "body": "$body",
        "head": "creative-commoners:$new_branch",
        "base": "$current_branch"
    }
    EOT;
    $ch = create_ch("https://api.github.com/repos/$account/$repo/pulls", $post_body);
    $result = curl_exec($ch);
    $resp_code = curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
    curl_close($ch);
    if ($resp_code != 201) {
        echo "FAILURE - did not create pull-request for $moduleName - response code was $resp_code\n";
        echo $result;
        print_pr_urls($pr_urls);
        asort($failed);
        if (!empty($failed)) {
            var_dump('The following modules had issues:', $failed);
        }
        die();
    }
    if ($result) {
        $pr_urls[] = json_decode($result)->url;
    }
}

print_pr_urls($pr_urls);
asort($failed);
if (!empty($failed)) {
    var_dump('The following modules had issues:', $failed);
}
```

**Comment by GuySartorelli** [comment]
All PRs merged
