### ISSUE TITLE
Loosen constraint on recipe-ccl and recipe-solr-search

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#201]
[Recipe-ccl](https://github.com/silverstripe/recipe-ccl/) and [recipe-solr-search](https://github.com/silverstripe/recipe-solr-search/tree/3) should still be installable on the latest version of Silverstripe CMS 5.

However, we didn't removed the lock step on them, so you are block from installing on CMS 5.1 and above.

## Acceptance criteria
- recipe-ccl and recipe-solr-search can be installed on any version of Silverstripe CMS 5.
- A new minor release of both modules is tagged.
- The supported tag badge is removed from both modules.
- Make it explicit in the readme that these recipe are not lockstepd anymore.

## Note
- In theory, we could update `dependency-constraint` in the `.cow.json` file to `semver` ... in case we ever wanted to retag those recipe with cow. That seems kind of pointless.

## PRs
- https://github.com/silverstripe/recipe-ccl/pull/14
- https://github.com/silverstripe/recipe-solr-search/pull/21

**Comment by GuySartorelli** [comment]
PRs merged. Assigning to @emteknetnz to ensure they are installable and to tag them.

**Comment by emteknetnz** [comment]
Have tagged 3.1.0 of each module and confirmed they will install with silverstripe/installer 5.1

**Comment by emteknetnz** [comment]
Have tagged 3.1.0 of each module and confirmed they will install with silverstripe/installer 5.1
