### ISSUE TITLE
Move documentation linting to its own repository

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#206]
We're [pulling linkfield docs](https://github.com/silverstripe/silverstripe-linkfield/issues/27) in from that repository, and aim to pull more in going forward:
- https://github.com/silverstripe/silverstripe-elemental/issues/985
- https://github.com/silverstripe/silverstripe-userforms/issues/1266
- https://github.com/silverstripe/silverstripe-mfa/issues/531

We should pull the documentation linting stuff into its own repository that can be shared across all relevant repos.

## Acceptance criteria
- [x] Linting configuration (i.e. declaring what linting rules are applied) is in the new repository
- [x] All dependencies (npm and composer) are handled in the new repository
- [x] Repositories with documentation don't need any configuration beyond indicating where their documentation lives
- [x] Documentation can be linted using a command that gets added to `vendor/bin/`
- [x] Documentation can be linted both when the repository with documentation is the root dir (i.e. CI) and when it is in vendor (i.e. locally)
- [x] developer docs itself has the new linting repo as a dev dependency
- [x] Other repositories with documentation list the new repository as a composer dev dependency
- [x] All repositories currently pulling documentation into the developer docs site have the new linting applied
- [x] Docs linting is added as a regular part of CI for all relevant repositories
- [x] All cards for pulling new documentation in from additional repositories are updated so that adding linting is in the ACs
- [x] New repo is in packagist
- [x] New repo has appropriate branch protection rule
- [x] New repo is added to zenhub board
- [x] New repo is added to module standardiser
- [x] New repo is added to rhino
- [x] New repo is added to elvis

## Note
- We'll exclude userhelp linting for now, but we'll create a follow card for applying linting to userhelp

## PRs
CI showing developer-docs happy: https://github.com/silverstripe/developer-docs/actions/runs/8532499473?pr=489
CI showing the changes to the `gha-*` repos work as expected: https://github.com/GuySartorelli/silverstripe-linkfield/actions/runs/8545963893/job/23415708351
- https://github.com/silverstripe/documentation-lint/pull/1
- https://github.com/silverstripe/rhino/pull/18
- https://github.com/silverstripe/github-issue-search-client/pull/135
- https://github.com/silverstripe/module-standardiser/pull/41
- https://github.com/silverstripe/developer-docs/pull/489
- https://github.com/silverstripe/gha-ci/pull/112
- https://github.com/silverstripe/gha-generate-matrix/pull/84
- https://github.com/silverstripe/gha-run-tests/pull/23
Do not merge anything below this line until the CI PRs have been merged and has been rerun on the below PRs.
- https://github.com/silverstripe/silverstripe-linkfield/pull/271

After everything is merged, reassign to Guy so they can add to packagist and run standardiser across the new repo.

**Comment by GuySartorelli** [comment]
New repo is at https://github.com/silverstripe/documentation-lint

**Comment by emteknetnz** [comment]
Assigning back to @GuySartorelli so sort out packagist and ensure things are working as expected. You'll no doubt want to rerun builds for linkfield and developer docs

**Comment by GuySartorelli** [comment]
Turns out I don't have access to the machine user we use to add packages to packagist. Can you please do that step and then reassign to me?

**Comment by GuySartorelli** [comment]
new doc linting CI passing in both linkfield and dev docs
