### ISSUE TITLE
broken builds

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#207]
Anything that requires frameworktest in the `5` or equivalent branch is failing CI.

https://github.com/silverstripe/silverstripe-installer/actions/runs/8131709640
```text
PHP Fatal error:  Uncaught Error: Class "DNADesign\Elemental\Models\BaseElement" not found in /home/runner/work/silverstripe-installer/silverstripe-installer/vendor/silverstripe/frameworktest/code/linkfield/Blocks/LinkFieldTestBlock.php:7
```

## PR
- https://github.com/silverstripe/silverstripe-frameworktest/pull/168
- https://github.com/silverstripe/silverstripe-framework/pull/11166
- https://github.com/silverstripe/silverstripe-userforms/pull/1271

**Comment by GuySartorelli** [comment]
PR merged. Assigning back to Steve to check it fixes the builds.

**Comment by maxime-rainville** [comment]
The builds are all fixed.
