### ISSUE TITLE
Broken merged (March 12)

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#209]
The following module have broken merge ups:
- [silverstripe/admin](https://github.com/silverstripe/silverstripe-admin/actions/workflows/merge-up.yml?query=branch%3A2+-event%3Apull_request)
- [silverstripe/frameworktest](https://github.com/silverstripe/silverstripe-frameworktest/actions/workflows/merge-up.yml?query=branch%3A1+-event%3Apull_request)
- [webpack-config](https://github.com/silverstripe/webpack-config/actions/workflows/merge-up.yml?query=branch%3A2+-event%3Apull_request)

## PRs
- https://github.com/silverstripe/silverstripe-frameworktest/pull/170

**Comment by GuySartorelli** [comment]
PR merged, reassigned to Steve to check it works.
