### ISSUE TITLE
Update supported modules repo

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#22]
The [supported-modules](https://github.com/silverstripe/supported-modules) still only lists the CMS4 supported modules. We need to add a CMS5 version.

## Acceptance Criteria
- Supported modules repo has separate branches for CMS 4 and CMS 5.
- Modules/Tools that we know for sure relies on this repo are called out in the README.
- Modules/Tools are updated accordingly.

## Notes
- I'd be keen to come up with a more robust way of doing this and provide formal doc on how to use it. My inclination would be to do the bare minimum to get this working until we have a better approach.
- Tools that are known to use this repo:
    - tx-translator tool
    - bringyourownideas/silverstripe-maintenance

## PRs
- https://github.com/silverstripe/silverstripe-tx-translator/pull/6
- (bringyouownideas/silverstripe-maintenance being handled on [this issue](https://github.com/silverstripe/cwp/issues/320) instead)
- (Have manually updated readme on https://github.com/silverstripe/supported-modules & created 4 + 5 branches)
- https://github.com/silverstripe/supported-modules/pull/21

**Comment by GuySartorelli** [comment]
While it wasn't an excplicit acceptance criteria, updating the cms 5 version of the list is definitely in scope for this card, I would think.
The list of CMS5 supported modules is https://docs.silverstripe.org/en/5/project_governance/supported_modules - please update the json file to include only these for the 5 branch

**Comment by emteknetnz** [comment]
@GuySartorelli Have created PR https://github.com/silverstripe/supported-modules/pull/21

**Comment by GuySartorelli** [comment]
All merged
