### ISSUE TITLE
Add a `type/i18n` tag

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#220]
S2Hub has recently expressed a desire to better track issue related to localisation and internationalisation.

## Acceptance criteria
- [Label doc is updated](https://docs.silverstripe.org/en/5/contributing/issues_and_bugs/#labels) and provided a clear description of how and when to use the label.
- Label is added to all our repos.
- Module standardiser is updated so the label is automatically added to all future repos.

## PRs
- https://github.com/silverstripe/developer-docs/pull/497
- https://github.com/silverstripe/module-standardiser/pull/43

**Comment by maxime-rainville** [comment]
While we are looking at this, any other label we would be keen to add?

I'm thinking `type/governance` could be useful?

**Comment by emteknetnz** [comment]
type/i18n label has been added to all repos using module-standardiser

**Comment by GuySartorelli** [comment]
PRs merged
