### ISSUE TITLE
Remove stylelint warnings 

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/.github#228]
## Description
After sass-lint was replaced by stylelint, it became necessary to bring existing code into compliance with the new rules so that all style files adhered to the basic rules.

Mostly this is a deviation from the rules in the writing and use of the color name instead of the hex code, indents before blocks and at the beginning of the file, empty comments. You need to go through all the modules from the list and run a lint check. Any warnings that occur must be corrected or removed from the list of rules in the `.stylelintrc.yml` file if they are not appropriate.

## Acceptance criteria
- [x] There are no stylelint warnings on any supported modules
- [x] The `'defaultSeverity': 'warning'` line is removed from `.stylelintrc.js` in the shared lint config
- [x] Paths being ignored are evaluated - stop ignoring "legacy" code, since we're still maintaining it.

## PRs
This PR must be merged first so I can update the yarn deps for all the other repos, or else the linting in CI for the PRs will be using the outdated rules.
- https://github.com/silverstripe/eslint-config/pull/26

## Lint fixing PRs
Reassign to Guy if these are still draft - but make sure you merge the above PR first!
- https://github.com/silverstripe/silverstripe-admin/pull/1774
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/148
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1468
- https://github.com/silverstripe/silverstripe-cms/pull/2957
- https://github.com/silverstripe/silverstripe-blog/pull/762
- https://github.com/silverstripe/silverstripe-contentreview/pull/238
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/309
- https://github.com/silverstripe/silverstripe-login-forms/pull/182
- https://github.com/silverstripe/silverstripe-segment-field/pull/111
- https://github.com/silverstripe/silverstripe-linkfield/pull/296
- https://github.com/silverstripe/silverstripe-userforms/pull/1302
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/239
- https://github.com/silverstripe/silverstripe-elemental/pull/1202
- https://github.com/silverstripe/silverstripe-mfa/pull/546
- https://github.com/silverstripe/silverstripe-session-manager/pull/199
- https://github.com/silverstripe/silverstripe-tagfield/pull/292
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/161
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/184
- https://github.com/silverstripe/silverstripe-externallinks/pull/130
- https://github.com/silverstripe/silverstripe-frameworktest/pull/184
- https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/110
- https://github.com/silverstripe/silverstripe-lumberjack/pull/153
- https://github.com/silverstripe/silverstripe-realme/pull/145
- https://github.com/silverstripe/silverstripe-subsites/pull/576
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/228
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/862
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/538
- https://github.com/symbiote/silverstripe-multivaluefield/pull/113
- https://github.com/colymba/GridFieldBulkEditingTools/pull/289
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/93
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/345

**Comment by emteknetnz** [comment]
Have merged first PR, assigning back to Guy to create 1.3.0 eslint-config release
