### ISSUE TITLE
CI doesn't work with beta1 tags

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#23]
https://github.com/silverstripe/silverstripe-framework/actions/runs/4381048197

Need to get COMPOSER_ROOT_VERSION to not be `4.13.0-beta1`

### PRs
- https://github.com/silverstripe/gha-ci/pull/62
- https://github.com/silverstripe/gha-ci/pull/63
- https://github.com/silverstripe/gha-generate-matrix/pull/50
- https://github.com/silverstripe/gha-generate-matrix/pull/51
- https://github.com/silverstripe/gha-ci/pull/64

**Comment by GuySartorelli** [comment]
PR merged.
Rerunning [4.13.0-beta1 on framework](https://github.com/silverstripe/silverstripe-framework/actions/runs/4381048197) and [1.12.3 on admin](https://github.com/silverstripe/silverstripe-admin/actions/runs/4359349658) to check it worked

**Comment by GuySartorelli** [comment]
@emteknetnz The stable tag worked, but the beta tag failed still.

**Comment by GuySartorelli** [comment]
New PRs merged. Rerunnning [4.13.0-beta1 on framework](https://github.com/silverstripe/silverstripe-framework/actions/runs/4381048197) to check it worked

**Comment by GuySartorelli** [comment]
@emteknetnz Beta failed again. The composer.json of framework beta has some beta constraints in it: https://github.com/silverstripe/silverstripe-framework/blob/4.13.0-beta1/composer.json
This means we need to install using the beta tag of installer, I think.

**Comment by GuySartorelli** [comment]
Rerunning the beta jobs again: https://github.com/silverstripe/silverstripe-framework/actions/runs/4381048197

**Comment by GuySartorelli** [comment]
And again: https://github.com/silverstripe/silverstripe-framework/actions/runs/4381048197

**Comment by emteknetnz** [comment]
Works now
