### ISSUE TITLE
Turn off 4.13 ci cron + resolve red builds

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#235]
CMS 4.13 is now in the "Security fix only" phase. The need for keeping the builds green there has been considerably reduced.

## Acceptance criteria
- [x] PR to turn off the ci cron for 4.13 builds - see dispatch-ci
- [x] Resolve any outstanding broken builds on 4.13
- [x] Update security release process to manually re-run ci on 4.13 builds that may be affected by high impact patch on the day or release
- [x] Update security fix section in regular release process

## PRs
- https://github.com/silverstripe/gha-dispatch-ci/pull/14
- https://github.com/silverstripe/silverstripe-admin/pull/1739
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/186
- https://github.com/colymba/GridFieldBulkEditingTools/pull/282
- https://github.com/silverstripe/gha-run-tests/pull/28
- https://github.com/silverstripe/silverstripe-admin/pull/1744
- https://github.com/silverstripe/gha-dispatch-ci/pull/16

**Comment by GuySartorelli** [comment]
PRs merged, reassigning to Steve 'cause Rhino doesn't look happy still

**Comment by GuySartorelli** [comment]
PRs merged. Reassigning to Steve to check if Rhino is happy.

**Comment by GuySartorelli** [comment]
Reopening - The CMS 4 CI is still being dispatched. See https://github.com/silverstripe/silverstripe-blog/actions/runs/9281371462/job/25537243483 as an example

It does output the message to say it's skipping it
> Workflow is configured to not dispatch workflow for branches on previous major. Exiting.

But then it still continues processing anyway
>  branch is 3.12

**Comment by emteknetnz** [comment]
Assigning back to Guy to confirm all is working correctly

**Comment by GuySartorelli** [comment]
I'll green-ify the remaining 4.13 CI builds once we can see that the cron has stopped running. That will require https://github.com/silverstripe/.github/issues/267 to be resolved.

**Comment by GuySartorelli** [comment]
That was merged - now need to wait for the weekend to see if cron runs.

**Comment by GuySartorelli** [comment]
Crons now skipping CMS 4 as expected. I'll tidy up the remaining CI failures.
