### ISSUE TITLE
Manual merge-ups required

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#240]
Rhino shows a lot of repositories which don't have a merge-up workflow that need to have commits merged up.
https://rhino.silverstripe.org/?t=merge-ups

For recipes, if at all possible, run the cow merge up command (see [the release process](https://silverstripe.atlassian.net/wiki/spaces/CMS/pages/655458662/Silverstripe+CMS+Release+Process#SilverstripeCMSReleaseProcess-5.4Publishtherelease)) as that was missed during the 5.2 release

For modules that aren't supported in CMS 5 but got a CMS 5 compatible release, do the merge-up if it's trivial, but if something will be tricky just make a comment in here - and _maybe_ update rhino to not report it.

If there's anything that doesn't have a merge-up workflow but should, run module-standardiser (we're due for a run anyway) and make sure it gets added.

**Comment by emteknetnz** [comment]
I've manually merged up all the things that don't have a merge-up workflow from the current patch to next-minor to CMS 6

I was careful with the recipes to ensure that dependencies were not changed on merge-up from minor branch to next-minor branch

**Comment by emteknetnz** [comment]
Not doing module-standardiser because we'd first need to update module-standardiser with updated [workflow permissions](https://github.com/silverstripe/silverstripe-framework/issues/10510) -

**Comment by GuySartorelli** [comment]
Reopening - rhino is still reporting a lot of merge-ups required.

**Comment by emteknetnz** [comment]
I've dealt with the recipes. For all the other I'll open a new issue to run module-standardiser to ensure that all the modules have merge-ups workflows, and block it on the github permissions card
