### ISSUE TITLE
Run module-standardiser

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#242]
A bunch of modules in https://rhino.silverstripe.org/?t=merge-ups do not have merge-up workflow on the repo

## Notes
- The cron time on ALL repos will change for all cron based worfklows - this is expected for this run and will not happen in subsequent runs
- This will be the first time standardiser has been run after updating it to use the new `silverstripe/supported-modules` set of repositories.
    - If any repos in that list should _not_ be included in standardiser for some reason, add an exclusion list to module-standardiser somewhere, and update the [docs for setting up a new repo](https://silverstripe.atlassian.net/wiki/spaces/CMS/pages/3030679981/Setting+up+a+new+GitHub+repository).

## Acceptance criteria
- [ ] Run module-standardiser across all repos
- [ ] Ensure that the merge-ups are added to all non-recipes on repos that follow standard branching conventions i.e. 1/1.0/2/2.0 style - note - there's a [separate card](https://github.com/silverstripe/.github/issues/249) to handle non-silverstripe repos on the wrong default branch
- [ ] Ensure that the auto-tag workflow is on all workflow repos (note that regular tagging happens in ci.yml and action-ci.yml)
- [ ] Ensure that all relevant workflow files have the correct permissions added - see https://github.com/silverstripe/silverstripe-framework/issues/10510

## Module standardiser PR
- https://github.com/silverstripe/module-standardiser/pull/49
- https://github.com/silverstripe/module-standardiser/pull/50
- https://github.com/silverstripe/module-standardiser/pull/51
- https://github.com/silverstripe/supported-modules/pull/33

## PRs
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/221
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/85
- https://github.com/colymba/GridFieldBulkEditingTools/pull/283
- https://github.com/silverstripe/cwp-agencyextensions/pull/119
- https://github.com/silverstripe/cwp-starter-theme/pull/251
- https://github.com/silverstripe/cwp-watea-theme/pull/186
- https://github.com/silverstripe/developer-docs/pull/513
- https://github.com/silverstripe/silverstripe-elemental/pull/1189
- https://github.com/dnadesign/silverstripe-elemental-userforms/pull/92
- https://github.com/silverstripe/silverstripe-admin/pull/1748
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1460
- https://github.com/silverstripe/silverstripe-assets/pull/604
- https://github.com/silverstripe/silverstripe-auditor/pull/78
- https://github.com/silverstripe/silverstripe-blog/pull/756
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/304
- https://github.com/silverstripe/silverstripe-cms/pull/2941
- https://github.com/silverstripe/silverstripe-config/pull/112
- https://github.com/silverstripe/silverstripe-contentreview/pull/232
- https://github.com/silverstripe/silverstripe-documentconverter/pull/78
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/144
- https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/52
- https://github.com/silverstripe/silverstripe-environmentcheck/pull/101
- https://github.com/silverstripe/silverstripe-errorpage/pull/106
- https://github.com/silverstripe/silverstripe-externallinks/pull/125
- https://github.com/silverstripe/silverstripe-framework/pull/11239
- https://github.com/silverstripe/silverstripe-graphql/pull/585
- https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/105
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/103
- https://github.com/silverstripe/silverstripe-iframe/pull/85
- https://github.com/silverstripe/silverstripe-installer/pull/371
- https://github.com/silverstripe/silverstripe-ldap/pull/75
- https://github.com/silverstripe/silverstripe-linkfield/pull/286
- https://github.com/silverstripe/silverstripe-lumberjack/pull/147
- https://github.com/silverstripe/silverstripe-mimevalidator/pull/75
- https://github.com/silverstripe/silverstripe-realme/pull/140
- https://github.com/silverstripe/silverstripe-session-manager/pull/193
- https://github.com/silverstripe/recipe-authoring-tools/pull/35
- https://github.com/silverstripe/recipe-blog/pull/52
- https://github.com/silverstripe/recipe-cms/pull/84
- https://github.com/silverstripe/recipe-collaboration/pull/31
- https://github.com/silverstripe/recipe-content-blocks/pull/41
- https://github.com/silverstripe/recipe-core/pull/94
- https://github.com/silverstripe/recipe-form-building/pull/34
- https://github.com/silverstripe/recipe-plugin/pull/40
- https://github.com/silverstripe/recipe-reporting-tools/pull/43
- https://github.com/silverstripe/recipe-services/pull/34
- https://github.com/silverstripe/recipe-kitchen-sink/pull/60
- https://github.com/silverstripe/silverstripe-registry/pull/96
- https://github.com/silverstripe/silverstripe-reports/pull/181
- https://github.com/silverstripe/silverstripe-restfulserver/pull/121
- https://github.com/silverstripe/silverstripe-securityreport/pull/78
- https://github.com/silverstripe/silverstripe-segment-field/pull/107
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/233
- https://github.com/silverstripe/silverstripe-siteconfig/pull/161
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/86
- https://github.com/silverstripe/silverstripe-spamprotection/pull/114
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/188
- https://github.com/silverstripe/silverstripe-subsites/pull/570
- https://github.com/silverstripe/silverstripe-tagfield/pull/287
- https://github.com/silverstripe/silverstripe-taxonomy/pull/111
- https://github.com/silverstripe/silverstripe-textextraction/pull/91
- https://github.com/silverstripe/silverstripe-userforms/pull/1287
- https://github.com/silverstripe/vendor-plugin/pull/75
- https://github.com/silverstripe/silverstripe-versioned/pull/444
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/339
- https://github.com/silverstripe/silverstripe-versionfeed/pull/107
- https://github.com/silverstripe/silverstripe-simple/pull/80
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/530
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/390
- https://github.com/symbiote/silverstripe-multivaluefield/pull/108
- https://github.com/symbiote/silverstripe-queuedjobs/pull/426
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/849
- https://github.com/silverstripe/silverstripe-mfa/pull/539
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/156
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/179
- https://github.com/silverstripe/silverstripe-login-forms/pull/176
- https://github.com/silverstripe/silverstripe-dynamodb/pull/62

## Follow up PRs to fix crons

- https://github.com/bringyourownideas/silverstripe-maintenance/pull/222
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/87
- https://github.com/colymba/GridFieldBulkEditingTools/pull/284
- https://github.com/silverstripe/cwp-agencyextensions/pull/120
- https://github.com/silverstripe/cwp-starter-theme/pull/252
- https://github.com/silverstripe/cwp-watea-theme/pull/187
- https://github.com/silverstripe/developer-docs/pull/515
- https://github.com/silverstripe/silverstripe-elemental/pull/1191
- https://github.com/dnadesign/silverstripe-elemental-userforms/pull/93
- https://github.com/silverstripe/silverstripe-admin/pull/1750
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1462
- https://github.com/silverstripe/silverstripe-assets/pull/606
- https://github.com/silverstripe/silverstripe-auditor/pull/80
- https://github.com/silverstripe/silverstripe-blog/pull/758
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/306
- https://github.com/silverstripe/silverstripe-cms/pull/2943
- https://github.com/silverstripe/silverstripe-config/pull/113
- https://github.com/silverstripe/silverstripe-contentreview/pull/234
- https://github.com/silverstripe/silverstripe-documentconverter/pull/80
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/145
- https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/53
- https://github.com/silverstripe/silverstripe-environmentcheck/pull/102
- https://github.com/silverstripe/silverstripe-errorpage/pull/108
- https://github.com/silverstripe/silverstripe-externallinks/pull/126
- https://github.com/silverstripe/silverstripe-framework/pull/11248
- https://github.com/silverstripe/silverstripe-graphql/pull/587
- https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/107
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/104
- https://github.com/silverstripe/silverstripe-iframe/pull/86
- https://github.com/silverstripe/silverstripe-installer/pull/372
- https://github.com/silverstripe/silverstripe-ldap/pull/77
- https://github.com/silverstripe/silverstripe-linkfield/pull/288
- https://github.com/silverstripe/silverstripe-lumberjack/pull/149
- https://github.com/silverstripe/silverstripe-mimevalidator/pull/76
- https://github.com/silverstripe/silverstripe-realme/pull/141
- https://github.com/silverstripe/silverstripe-session-manager/pull/195
- https://github.com/silverstripe/recipe-authoring-tools/pull/36
- https://github.com/silverstripe/recipe-blog/pull/53
- https://github.com/silverstripe/recipe-cms/pull/85
- https://github.com/silverstripe/recipe-collaboration/pull/32
- https://github.com/silverstripe/recipe-content-blocks/pull/42
- https://github.com/silverstripe/recipe-core/pull/95
- https://github.com/silverstripe/recipe-form-building/pull/35
- https://github.com/silverstripe/recipe-plugin/pull/41
- https://github.com/silverstripe/recipe-reporting-tools/pull/44
- https://github.com/silverstripe/recipe-services/pull/35
- https://github.com/silverstripe/recipe-kitchen-sink/pull/61
- https://github.com/silverstripe/silverstripe-registry/pull/97
- https://github.com/silverstripe/silverstripe-reports/pull/182
- https://github.com/silverstripe/silverstripe-restfulserver/pull/122
- https://github.com/silverstripe/silverstripe-securityreport/pull/79
- https://github.com/silverstripe/silverstripe-segment-field/pull/108
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/235
- https://github.com/silverstripe/silverstripe-siteconfig/pull/162
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/88
- https://github.com/silverstripe/silverstripe-spamprotection/pull/115
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/190
- https://github.com/silverstripe/silverstripe-subsites/pull/572
- https://github.com/silverstripe/silverstripe-tagfield/pull/288
- https://github.com/silverstripe/silverstripe-taxonomy/pull/112
- https://github.com/silverstripe/silverstripe-textextraction/pull/92
- https://github.com/silverstripe/silverstripe-userforms/pull/1289
- https://github.com/silverstripe/vendor-plugin/pull/76
- https://github.com/silverstripe/silverstripe-versioned/pull/446
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/341
- https://github.com/silverstripe/silverstripe-versionfeed/pull/109
- https://github.com/silverstripe/silverstripe-simple/pull/81
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/532
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/392
- https://github.com/symbiote/silverstripe-multivaluefield/pull/109
- https://github.com/symbiote/silverstripe-queuedjobs/pull/428
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/851
- https://github.com/silverstripe/silverstripe-mfa/pull/541
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/157
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/180
- https://github.com/silverstripe/silverstripe-login-forms/pull/178
- https://github.com/silverstripe/silverstripe-dynamodb/pull/63

## PRs for tooling / workflow / misc repos
- https://github.com/silverstripe/gha-action-ci/pull/9
- https://github.com/silverstripe/gha-auto-tag/pull/19
- https://github.com/silverstripe/gha-ci/pull/128
- https://github.com/silverstripe/gha-dispatch-ci/pull/15
- https://github.com/silverstripe/gha-gauge-release/pull/11
- https://github.com/silverstripe/gha-generate-matrix/pull/92
- https://github.com/silverstripe/gha-issue/pull/12
- https://github.com/silverstripe/gha-keepalive/pull/14
- https://github.com/silverstripe/gha-merge-up/pull/36
- https://github.com/silverstripe/gha-pull-request/pull/14
- https://github.com/silverstripe/gha-run-tests/pull/29
- https://github.com/silverstripe/gha-tag-release/pull/24
- https://github.com/silverstripe/gha-trigger-ci/pull/8
- https://github.com/silverstripe/gha-update-js/pull/28
- https://github.com/silverstripe/recipe-testing/pull/18
- https://github.com/silverstripe/silverstripe-behat-extension/pull/270
- https://github.com/silverstripe/MinkFacebookWebDriver/pull/26
- https://github.com/silverstripe/cow/pull/256
- https://github.com/silverstripe/rhino/pull/27
- https://github.com/silverstripe/github-issue-search-client/pull/137
- https://github.com/silverstripe/module-standardiser/pull/52
- https://github.com/silverstripe/silverstripe-tx-translator/pull/31
- https://github.com/silverstripe/markdown-php-codesniffer/pull/9
- https://github.com/silverstripe/silverstripe-standards/pull/7
- https://github.com/silverstripe/documentation-lint/pull/4
- https://github.com/silverstripe/supported-modules/pull/32
- https://github.com/silverstripe/eslint-config/pull/25
- https://github.com/silverstripe/webpack-config/pull/73
- https://github.com/silverstripe/.github/pull/250
- https://github.com/silverstripe/api.silverstripe.org/pull/118
- https://github.com/silverstripe/doc.silverstripe.org/pull/297
- https://github.com/silverstripe/silverstripe-userhelp-content/pull/182
- https://github.com/silverstripe/demo.silverstripe.org/pull/68
- https://github.com/silverstripe/silverstripe-frameworktest/pull/178
- https://github.com/silverstripe/silverstripe-module/pull/43

**Comment by GuySartorelli** [comment]
There's no PR for https://github.com/silverstripe/documentation-lint, and probably others that also need them.

**Comment by GuySartorelli** [comment]
Just one PR needs attention: https://github.com/silverstripe/documentation-lint/pull/4

**Comment by GuySartorelli** [comment]
PRs merged
