### ISSUE TITLE
Create a workflow to create an issue linking to broken builds and broken merge-ups on a weekly cron

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#243]
## PRs
- https://github.com/silverstripe/gha-issue/pull/10
- https://github.com/silverstripe/.github/pull/245
- https://github.com/silverstripe/gha-issue/pull/11

**Comment by GuySartorelli** [comment]
PRs merged.
Manually ran the new workflow to see if it works and [it broke](https://github.com/silverstripe/.github/actions/runs/9071576835/job/24925560561)

**Comment by GuySartorelli** [comment]
PR merged. Ran twice - works great, auto-deletion of pre-existing issue works as expected.
