### ISSUE TITLE
Get rid of the CMS5 branches for modules that won't be compatible with CMS5

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#25]
There's a bunch of modules that will not be made CMS 5 compatible, but we created CMS5 branches for the anyway.

Those branches should be removed.

## Acceptance criteria
- [ ] Module that will not be made CMS5 compatible don't have a CMS 5 branch
- [x] Validate that the Readme for these module explicitly say that they will not have a CMS 5 branch and suggest alternatives where appropriate.

## Notes
- The [CMS 5.0 changelog ](https://docs.silverstripe.org/en/5/changelogs/5.0.0/#modules-not-supported-going-forward)contains a list of modules that got dropped for CMS 5. Module that work with CMS 5 but are not officially supported should still have a CMS 5 branch. 

## PRs
- https://github.com/bringyourownideas/silverstripe-composer-security-checker/pull/60
- https://github.com/silverstripe/cwp-pdfexport/pull/33
- https://github.com/dnadesign/silverstripe-elemental-subsites/pull/14
- https://github.com/silverstripe/silverstripe-akismet/pull/47
- https://github.com/silverstripe/silverstripe-html5/pull/42
- https://github.com/silverstripe/silverstripe-security-extensions/pull/56
- https://github.com/silverstripe/silverstripe-spellcheck/pull/59
- https://github.com/silverstripe/developer-docs/pull/286

**Comment by michalkleiner** [comment]
@maxime-rainville the image didn't upload correctly.

**Comment by sabina-talipova** [comment]
I went through the list provided in [this list](https://docs.silverstripe.org/en/5/changelogs/5.0.0/#modules-not-supported-going-forward). Almost all modules in this list with the "Dropped" / "Folded back in core" status do not have branches compatible with CMS5.
Repos don't have CMS5 branches:
- silverstripe/composer-security-checker;
- silverstripe/cwp-theme-default;
- silverstripe/cwp-pdfexport
- hafriedlander/phockito
- hafriedlander/silverstripe-phockito
- silverstripe/activedirectory
- silverstripe/akismet
- silverstripe/html5
- silverstripe/security-extensions
- silverstripe/spellcheck
- tijsverkoyen/akismet
- undefinedoffset/sortablegridfield
- silverstripe/html5
- silverstripe/security-extensions

Repos have CMS5 branches:
- [dnadesign/silverstripe-elemental-subsites](https://github.com/dnadesign/silverstripe-elemental-subsites/tree/4)
@maxime-rainville, could you, please, remove [branch 4](https://github.com/dnadesign/silverstripe-elemental-subsites/branches/all) for dnadesign/silverstripe-elemental-subsites

**Comment by maxime-rainville** [comment]
All done.
