### ISSUE TITLE
Bypass permissions still required to merge a pull-request after 2 approvals

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#258]
After getting two approvals on a PR, bypass permissions were still required to merge [this PR](https://github.com/silverstripe/silverstripe-framework/pull/11263)

The branch protection rulesets were added on https://github.com/silverstripe/.github/issues/198

![image](https://github.com/silverstripe/.github/assets/4809037/bf8cc6d8-d8fe-4771-9111-77a150514f78)

Clicking on "View rules" and "Silverstripe CMS branch ruleset"

![image](https://github.com/silverstripe/.github/assets/4809037/0ccb1c54-270a-499f-9db9-5e3de903f079)

I suspect that the issue is **"Restrict updates"** since we're updating an existing branch

When resolving get 2x developers to try approving a dummy PR on a test repo with the branch ruleset applied

Note this may be resolved after [merging this](https://github.com/silverstripe/.github/issues/264)

**Comment by GuySartorelli** [comment]
That rule got reverted and won't be reinstated. See https://github.com/silverstripe/.github/issues/260
