### ISSUE TITLE
Automatic patch release tagging broken

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#259]
Tag rulesets were added in this issue https://github.com/silverstripe/.github/issues/198

Automatic patch tagging is broken in gha-ci e.g.
- https://github.com/silverstripe/silverstripe-framework/actions/runs/9310253996/job/25627638607
- https://github.com/silverstripe/silverstripe-userforms/actions/runs/9296099134/job/25584233072

```
Unable to create release for tag 5.2.10 - HTTP response code was 422
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Release",
      "code": "custom",
      "field": "pre_receive",
      "message": "pre_receive Repository rule violations found\n\nCannot create ref due to create name restrictions.\n\n"
    },
    {
      "resource": "Release",
      "code": "custom",
      "message": "Published releases must have a valid tag"
    }
  ],
  "documentation_url": "https://docs.github.com/rest/releases/releases#create-a-release"
}
```

### Notes
- Github docs on [tag protection rules](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules#about-tag-protection-rules)
- Gihut docs on [assigning permissions to jobs](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs)
- The github-actions user has `contents: write` permissions in this context https://github.com/silverstripe/gha-ci/blob/1/.github/workflows/ci.yml#L1010 which was working prior to the tag ruleset being added
- When testing the [github-actions bypass permissions](https://github.com/silverstripe/module-standardiser/pull/53/files#diff-03a8c9b327b85160db18ac239dee51b8c4b744d95b7c21532a836b1deb9531b8R70) for module-standardiser [this workflow](https://github.com/emteknetnz/test-thing/blob/f8f2ccdcd2bd5149e80af496c6a9149fd38c7ac2/.github/workflows/test.yml) was tested that uses gha-tag-release

### New issues created
- https://github.com/silverstripe/.github/issues/260

### PR
- https://github.com/silverstripe/module-standardiser/pull/55

**Comment by emteknetnz** [comment]
I suspect I did faulty testing originally to validate that the github-actions user has bypass permissions, I've retested and looks like it actually has no bypass permissions at all, not even `write` despite it have `contents: write` permission on the workflow

I've tested that unticking the "tag creation" check allows the gha-tag-release to create tags and releases, so in the short-term we'll need to update module-standardiser to apply that rule

**Comment by GuySartorelli** [comment]
Reassigning to Steve to run standardiser

**Comment by emteknetnz** [comment]
Have updated, and also re-run ci workflows in issue description, things are working correclty
