### ISSUE TITLE
Update CI deprecated set-output and set-state commands

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#26]
We use set-output and set-state to save data between jobs. It is now deprecated and replaced with new environment files.  set-output and set-state will stop working about mid way through 2023

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

![image.png](https://images.zenhubusercontent.com/5dcb6f9e3c55460001028c42/3bbfac14-a569-4ffb-8dd4-634978433748)

## PRs
- https://github.com/silverstripe/gha-update-js/pull/9
- https://github.com/silverstripe/gha-generate-matrix/pull/54
- https://github.com/silverstripe/gha-auto-tag/pull/4
- https://github.com/silverstripe/gha-ci/pull/65
- https://github.com/silverstripe/gha-update-js/pull/10
- https://github.com/silverstripe/gha-generate-matrix/pull/55

**Comment by GuySartorelli** [comment]
Related: https://github.com/silverstripe/gha-ci/issues/56

**Comment by emteknetnz** [comment]
I've merged the PRs. Keep an eye on the output of future CI runs to see if issue was resolved / we caused regressions

**Comment by GuySartorelli** [comment]
Still got lots of deprecation warnings in https://github.com/silverstripe/silverstripe-siteconfig/actions/runs/4815761974
My guess is its from downstream workflows. Will chase it down.

**Comment by emteknetnz** [comment]
All merged

**Comment by GuySartorelli** [comment]
https://github.com/silverstripe/silverstripe-siteconfig/actions/runs/4824702419 shows no more of these deprecation warnings. Ignore the node ones - there's another card for that.
