### ISSUE TITLE
Github action merge-ups broken because of new ruleset

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#264]
Github action merge-ups isn't working because of the new branch protection ruleset that was added in this [issue](https://github.com/silverstripe/.github/issues/198)

That added level of branch protections has broken the automated merge-ups e.g. https://github.com/silverstripe/silverstripe-framework/actions/runs/9336983354/job/25698267548

Unticking the 'update ref' checkbox for the branch protection rulesets should resolve this

## New issues created
- https://github.com/silverstripe/.github/issues/265

## Acceptance criteria
- [ ] The update check on the branch protection ruleset (or another check if appropriate) is updated on all modules
- [ ] The branch protection ruleset on module standardiser is updated
- [ ] Module standardiser is used to update all repository branch protection rulesets

## PRs
- https://github.com/silverstripe/module-standardiser/pull/56

**Comment by GuySartorelli** [comment]
PR merged, reassigning to Steve to run the standardiser

**Comment by emteknetnz** [comment]
Done. Have re-run merge-up workflows, has resolved issie
