### ISSUE TITLE
gha-auto-tag can't delete existing `v1` tag in order to recreate it

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#267]
gha-auto-tag needs to delete the existing `v1` tag in order to recreate it. We use this in lieu of caret semver constraints, since GitHub Actions doesn't have that concept built-in.

See https://github.com/silverstripe/gha-dispatch-ci/actions/runs/9375095280/job/25812539717

## PRs
- https://github.com/silverstripe/module-standardiser/pull/57

**Comment by GuySartorelli** [comment]
Reassigning to Steve to rerun standardiser

**Comment by emteknetnz** [comment]
Done
