### ISSUE TITLE
Meta repo doesn't have a readme

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#27]
I noticed there was nothing at all on this repo when creating an issue earlier. So I thought it would be worthwhile adding a quick readme in there. It's just for this repo, not the organisation one.

## PRs
- https://github.com/silverstripe/.github/pull/28

**Comment by GuySartorelli** [comment]
This is a duplicate of https://github.com/silverstripe/.github/issues/1
It also has no description, and hasn't got a PR linked in the description? Not sure what I'm meant to peer review and what the acceptance criteria are here?

**Comment by GuySartorelli** [comment]
Is this just meant to be a readme for the repo, or is it meant to be the meta readme?

**Comment by maxime-rainville** [comment]
Just for that repo. I noticed there was nothing at all on this repo when creating an issue earlier. So I thought it would be worthwhile adding a quick readme in there.

**Comment by GuySartorelli** [comment]
Fair enough. In the future can you please add that to the issue description to avoid confusion about what is expected?

**Comment by GuySartorelli** [comment]
Merged
