### ISSUE TITLE
Replace "Triage" group

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#270]
There's a @silverstripe/triage group that is only used for ZenHub users. The name could lead to confusion with other group.

## Acceptance criteria
- A new ZenHub group is created and the permissions are tailored to the needs of users that need to interact with ZenHub but don't require wide ranging access.
- All users currently in the triage group are added to the new ZenHub group.
- ZenHub group is added to all repositories we have in the ZenHub board (presuming that's necessary)
- Triage group is deleted.
- Update "new repo" confluence page.

**Comment by emteknetnz** [comment]
Should be able to just update the team via the API, which weirdly you cannot do via the GUI

https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#update-a-team

**Comment by emteknetnz** [comment]
All done
