### ISSUE TITLE
Broken behat tests when running kitchen sink

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#272]
When doing a special run of kitchen-sink in CI that includes all behat tests, some of the behat tests fail due to integration failures with other modules

We don't normally run behat on all modules during kitchen sink runs, though we do sometimes when testing PR's the may have a wide ranging impact

It seems like there are issues with the following jobs:
- endtoend blog
- endtoend cms
- endtoend siteconfig
- endtoend subsites
- endtoend versioned-admin

## Acceptance criteria
- Fix the integration issues so that behat tests pass

## PRs
- https://github.com/silverstripe/silverstripe-blog/pull/763
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/861
- https://github.com/silverstripe/silverstripe-siteconfig/pull/165
- https://github.com/silverstripe/silverstripe-cms/pull/2959
- https://github.com/silverstripe/cwp/pull/339
- https://github.com/silverstripe/silverstripe-frameworktest/pull/185

**Comment by GuySartorelli** [comment]
PRs merged. Reassigning to Steve to check sink behat is happy now.

**Comment by GuySartorelli** [comment]
PRs merged, reassigning to steve to check behat is green now

**Comment by emteknetnz** [comment]
Green on rerun
