### ISSUE TITLE
Broken CMS 4.13 builds

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#29]
The following builds are broken in CMS 4.13.
 | Modules | Builds |
| -- | -- |
| Session-manager | [![CI](https://github.com/silverstripe/silverstripe-session-manager/actions/workflows/ci.yml/badge.svg?branch=1.5)](https://github.com/silverstripe/silverstripe-session-manager/actions/workflows/ci.yml?query=branch%3A1.5) |
| CW Starter Theme | [![CI](https://github.com/silverstripe/cwp-starter-theme/actions/workflows/ci.yml/badge.svg?branch=3.3)](https://github.com/silverstripe/cwp-starter-theme/actions/workflows/ci.yml?query=branch%3A3.3) |
| recipe-kitchen-sink | [![CI](https://github.com/silverstripe/recipe-kitchen-sink/actions/workflows/ci.yml/badge.svg?branch=4.13)](https://github.com/silverstripe/recipe-kitchen-sink/actions/workflows/ci.yml?query=branch%3A4.13) |

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10730

**Comment by GuySartorelli** [comment]
PR merged

**Comment by GuySartorelli** [comment]
Reopening - assigning to @emteknetnz to validate the builds are fixed now
