### ISSUE TITLE
Upgrade to symfony 7 for CMS 6

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#296]
As per our [major support policy](https://docs.silverstripe.org/en/5/project_governance/major_release_policy/#symfony-support-commitments)
> At launch, Silverstripe CMS major releases track the latest stable major version of Symfony dependencies.

For CMS 6, this means upgrading from symfony 6 to symfony 7.

## kitchen-sink ci
- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/10660288256

## PRs
- https://github.com/silverstripe/silverstripe-assets/pull/636
- https://github.com/silverstripe/silverstripe-behat-extension/pull/283
- https://github.com/silverstripe/silverstripe-config/pull/122
- https://github.com/silverstripe/silverstripe-event-dispatcher/pull/28
- https://github.com/silverstripe/silverstripe-framework/pull/11356
- https://github.com/silverstripe/silverstripe-graphql-devtools/pull/57
- https://github.com/silverstripe/recipe-testing/pull/26
- https://github.com/silverstripe/silverstripe-session-manager/pull/218
- https://github.com/silverstripe/silverstripe-versioned/pull/470
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/551
- https://github.com/silverstripe/developer-docs/pull/574

**Comment by GuySartorelli** [comment]
@emteknetnz Please add an entry to the changelog about this, and double check if any other docs need to be updated.

**Comment by emteknetnz** [comment]
Done https://github.com/silverstripe/developer-docs/pull/574

**Comment by GuySartorelli** [comment]
Changes required in https://github.com/silverstripe/silverstripe-framework/pull/11356

**Comment by GuySartorelli** [comment]
PRs merged
