### ISSUE TITLE
Upgrade to PHPUnit 11

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#305]
## Acceptance criteria
- [x] Upgrade to PHPUnit 11 for CMS 6
- [x] Ensure any deprecation warnings in PHPUnit 9 have been resolved e.g. [`Expecting E_DEPRECATED and E_USER_DEPRECATED is deprecated and will no longer be possible in PHPUnit 10.`](https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/10660288256/job/29545322517#step:12:118)

## Notes
- Used https://github.com/emteknetnz/phpunit11-writer to automatically update tests
- Also manually did updates to fix some tests
- dataProviders are now static functions
- annotations converted to attributes, most notably dataProvider
- old code coverage annotations were removed rather than converted
- addMethods() changed to onlyMethods()
- ->will($this->returnValue(...)) manually changed to ->willReturn(...)
- ->will($this->returnCallback(...)) manually changed to ->willReturnCallback(...)
- ->withConsecutive(...) manually changed to a willReturnCallback(...) solution
- abstract tests are no longer allowed (presumably only if in /tests/ dir, because SapphireTest + FunctionalTest are OK)
- keys in dataProvider data must now match param names
- expectNotice() / expectWarning() / expectStrict() / expectDeprecation() have all been removed

## CMS 5 PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11376

## Recipe sink CI CMS 6
- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/10914242453

## CMS 6 PRs (ensure CMS 5 PRs are merged, merged-up and rebased on before merging these)
- https://github.com/silverstripe/gha-run-tests/pull/38
- https://github.com/silverstripe/gha-run-tests/pull/39
- https://github.com/silverstripe/recipe-testing/pull/27
- https://github.com/silverstripe/silverstripe-framework/pull/11361
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/96
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/238
- https://github.com/silverstripe/silverstripe-elemental/pull/1253
- https://github.com/silverstripe/silverstripe-admin/pull/1822
- https://github.com/silverstripe/silverstripe-assets/pull/638
- https://github.com/silverstripe/silverstripe-auditor/pull/91
- https://github.com/silverstripe/silverstripe-behat-extension/pull/284
- https://github.com/silverstripe/silverstripe-blog/pull/784
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/329
- https://github.com/silverstripe/silverstripe-cms/pull/3000
- https://github.com/silverstripe/silverstripe-config/pull/123
- https://github.com/silverstripe/silverstripe-crontask/pull/92
- https://github.com/silverstripe/silverstripe-documentconverter/pull/98
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1494
- https://github.com/silverstripe/silverstripe-dynamodb/pull/69
- https://github.com/silverstripe/silverstripe-environmentcheck/pull/111
- https://github.com/silverstripe/silverstripe-errorpage/pull/121
- https://github.com/silverstripe/silverstripe-event-dispatcher/pull/29
- https://github.com/silverstripe/silverstripe-externallinks/pull/146
- https://github.com/silverstripe/silverstripe-graphql/pull/601
- https://github.com/silverstripe/silverstripe-graphql-devtools/pull/59
- https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/124
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/112
- https://github.com/silverstripe/silverstripe-iframe/pull/97
- https://github.com/silverstripe/silverstripe-installer/pull/378
- https://github.com/silverstripe/silverstripe-ldap/pull/90
- https://github.com/silverstripe/silverstripe-linkfield/pull/330
- https://github.com/silverstripe/silverstripe-login-forms/pull/200
- https://github.com/silverstripe/silverstripe-lumberjack/pull/171
- https://github.com/silverstripe/silverstripe-mfa/pull/565
- https://github.com/silverstripe/silverstripe-mimevalidator/pull/83
- https://github.com/silverstripe/silverstripe-realme/pull/161
- https://github.com/silverstripe/recipe-authoring-tools/pull/41
- https://github.com/silverstripe/recipe-blog/pull/59
- https://github.com/silverstripe/recipe-cms/pull/91
- https://github.com/silverstripe/recipe-collaboration/pull/37
- https://github.com/silverstripe/recipe-content-blocks/pull/47
- https://github.com/silverstripe/recipe-core/pull/100
- https://github.com/silverstripe/recipe-form-building/pull/40
- https://github.com/silverstripe/recipe-reporting-tools/pull/49
- https://github.com/silverstripe/recipe-services/pull/40
- https://github.com/silverstripe/silverstripe-registry/pull/106
- https://github.com/silverstripe/silverstripe-reports/pull/194
- https://github.com/silverstripe/silverstripe-restfulserver/pull/134
- https://github.com/silverstripe/silverstripe-securityreport/pull/88
- https://github.com/silverstripe/silverstripe-segment-field/pull/125
- https://github.com/silverstripe/silverstripe-session-manager/pull/219
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/260
- https://github.com/silverstripe/silverstripe-siteconfig/pull/175
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/106
- https://github.com/silverstripe/silverstripe-spamprotection/pull/126
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/202
- https://github.com/silverstripe/silverstripe-subsites/pull/598
- https://github.com/silverstripe/silverstripe-tagfield/pull/306
- https://github.com/silverstripe/silverstripe-taxonomy/pull/122
- https://github.com/silverstripe/silverstripe-textextraction/pull/102
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/174
- https://github.com/silverstripe/silverstripe-userforms/pull/1326
- https://github.com/silverstripe/vendor-plugin/pull/81
- https://github.com/silverstripe/silverstripe-versioned/pull/473
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/362
- https://github.com/silverstripe/silverstripe-versionfeed/pull/120
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/198
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/553
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/416
- https://github.com/symbiote/silverstripe-multivaluefield/pull/119
- https://github.com/symbiote/silverstripe-queuedjobs/pull/446
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/885
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/886
- https://github.com/silverstripe/silverstripe-contentreview/pull/256
- https://github.com/dnadesign/silverstripe-elemental-userforms/pull/100
- https://github.com/silverstripe/closure/pull/3
- https://github.com/silverstripe/markdown-php-codesniffer/pull/13
- https://github.com/silverstripe/developer-docs/pull/583

# Follow up PRs
- https://github.com/silverstripe/silverstripe-mfa/pull/567
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/244

**Comment by GuySartorelli** [comment]
CMS 5 PR merged. Reassigning to Steve for CMS 6 PR prep

**Comment by GuySartorelli** [comment]
I do note "Ensure any deprecation warnings in PHPUnit 9 have been resolved" has been ticked though it seems not enough CMS 5 PRs to actually achieve that?

**Comment by GuySartorelli** [comment]
Changes required or questions asked in
- https://github.com/silverstripe/silverstripe-contentreview/pull/256
- https://github.com/silverstripe/closure/pull/3
- https://github.com/silverstripe/developer-docs/pull/583

Some PRs also need a rebase.

**Comment by GuySartorelli** [comment]
PRs merged. I still don't think "Ensure any deprecation warnings in PHPUnit 9 have been resolved" is done? Reassigning to Steve to check that.

**Comment by GuySartorelli** [comment]
New PRs merged.

Reassigning to Steve because "Ensure any deprecation warnings in PHPUnit 9 have been resolved" still doesn't seem to have been done. The branches that are still running PHPUnit 9 still seem to have deprecation warnings.

**Comment by emteknetnz** [comment]
The AC of fixing phpunit 9 warnings meant fix it for CMS 6, not for CMS 5. I should have spelt that out clearer in the initial ACs.

Projects aren't going to be running our unit-tests so it does matters at all if we have a bunch of warnings about phpunit 10 in our CMS 5 builds, we've had them for probably well over a year at this point
