### ISSUE TITLE
Prefer lowest builds failing on Deprecation::withSuppressedNotice()

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#314]
We renamed Deprecation::withNoReplacement() to Deprecation::withSuppressedNotice() [recently](https://github.com/silverstripe/silverstripe-framework/issues/11382)

However now a number of builds are failing on prefer-lowest as they don't have the necessary new API, which will be first available in framework 5.4.0

## Acceptance criteria
- [x] Bump minimum version of silverstripe/framework to ^5.4 on modules that use Deprecation::withSuppressedNotice()

## PRs
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/245
- https://github.com/silverstripe/silverstripe-elemental/pull/1256
- https://github.com/silverstripe/silverstripe-admin/pull/1828
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1498
- https://github.com/silverstripe/silverstripe-auditor/pull/95
- https://github.com/silverstripe/silverstripe-blog/pull/787
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/332
- https://github.com/silverstripe/silverstripe-cms/pull/3008
- https://github.com/silverstripe/silverstripe-contentreview/pull/260
- https://github.com/silverstripe/silverstripe-crontask/pull/96
- https://github.com/silverstripe/silverstripe-externallinks/pull/150
- https://github.com/silverstripe/silverstripe-graphql/pull/608
- https://github.com/silverstripe/silverstripe-graphql-devtools/pull/63
- https://github.com/silverstripe/silverstripe-ldap/pull/94
- https://github.com/silverstripe/silverstripe-realme/pull/166
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/263
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/206
- https://github.com/silverstripe/silverstripe-subsites/pull/602
- https://github.com/silverstripe/silverstripe-versioned/pull/477
- https://github.com/symbiote/silverstripe-queuedjobs/pull/450
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/893

**Comment by GuySartorelli** [comment]
Oh, good point.
We may want to do it for all modules before we release 5.4 but I won't keep the card open just for that.

**Comment by GuySartorelli** [comment]
PRs merged
