### ISSUE TITLE
Sake task failures

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#315]
Noticed there's a couple of the new sake tasks that cause issues on a default install of recipe-kitchen-sink for CMS 6

**sake tasks:content-review-emails**

ERROR [Emergency]: Uncaught TypeError: SilverStripe\ContentReview\Tasks\ContentReviewEmails::isValidEmail(): Argument #1 ($email) must be of type ?string, array given, called in /var/www/vendor/silverstripe/contentreview/src/Tasks/ContentReviewEmails.php on line 37
IN

**sake tasks:userforms-column-clean**

  [SilverStripe\ORM\Connect\DatabaseException]                                         
  Couldn't run query:                                                                  
                                                                                       
  SHOW COLUMNS                                                                         
  FROM SilverStripe\UserForms\Model\EditableFormField                                  
                                                                                       
  You have an error in your SQL syntax; check the manual that corresponds to your Mar  
  iaDB server version for the right syntax to use near '\UserForms\Model\EditableForm  
  Field' at line 1

**Comment by GuySartorelli** [comment]
`ContentReviewEmails::isValidEmail()` is being removed in https://github.com/silverstripe/.github/issues/193 so that one should take care of itself.

**Comment by emteknetnz** [comment]
https://github.com/silverstripe/silverstripe-userforms/issues/1340 is removing userform-column-clean, so we likely don't need this card, so will close
