### ISSUE TITLE
Add "Affects/v6" label to issues

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#321]
Now that we're a fair way into working on CMS 6, some issues we create will be for bugs or new features that only apply to CMS 6 branches of the various repositories.

The changes for these issues may not be API breaking changes in themselves, so the `type/api-break` label no longer covers all our bases for CMS 6 work.

## Acceptance criteria
- A "affects/v6" label is added to module standardiser
- The new label is applied to all commercially supported repositories

## PR
- https://github.com/silverstripe/module-standardiser/pull/73

**Comment by emteknetnz** [comment]
Have run module-standardiser using PR branch and added affects/v6 label to all supported modules

**Comment by GuySartorelli** [comment]
PR merged
