### ISSUE TITLE
Unable to upload artifact in CI

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#323]
https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/11336876147/job/31527560455

Run actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
With the provided path, there will be 2 files uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

Probably broke after something merged in https://github.com/silverstripe/.github/issues/316

## PR
- https://github.com/silverstripe/gha-generate-matrix/pull/111

**Comment by GuySartorelli** [comment]
PR merged
