### ISSUE TITLE
CMS6: Don't rely on `$_GET['flush']` to see if cache should be flushed

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#324]
There are a few places in core and supported modules relying on `$_GET['flush']` to see if cache should be flushed.

This isn't reliable in CMS 6 because sake doesn't set it.

We should also check for other similar attempts at getting at flush such as `$request->getVar('flush')`

## Acceptance criteria
- `Injector::inst()->get(Kernel::class)->isFlushed()` is used to check if we are flushing, instead of checking for get vars

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11440
- https://github.com/silverstripe/silverstripe-versionfeed/pull/122

**Comment by emteknetnz** [comment]
Yeah I did, forgot to push and create PR :-) Have linked in description

**Comment by GuySartorelli** [comment]
PRs merged - if there's no more, feel free to close
