### ISSUE TITLE
Cow - work out why non-recipes ended up with new deps

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#33]
Investigate why cow did this to admin

https://github.com/silverstripe/silverstripe-admin/commit/dceb3e8e9e4e17132f957a4d142020319711be23

It shouldn't have - was reverted in this PR - https://github.com/silverstripe/silverstripe-admin/pull/1480

~~Note only did this for 4.13-beta1, haven't seen this happen for anything else including 5.0.0-beta1, so this is low priority~~
This happened to most if not all non-recipes and will result in a bad constraint on stable if we don't fix it now.

There's a list of affected modules in a comment below. When reviewing, make sure each affected module has a PR (in case I missed one)

## PRs
- https://github.com/silverstripe/cow/pull/242
- https://github.com/silverstripe/silverstripe-cms/pull/2844
- https://github.com/silverstripe/silverstripe-errorpage/pull/81
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/103
- https://github.com/silverstripe/silverstripe-reports/pull/161
- https://github.com/silverstripe/cwp-watea-theme/pull/163
- https://github.com/silverstripe/silverstripe-subsites/pull/519
- https://github.com/silverstripe/silverstripe-elemental/pull/1048
- https://github.com/silverstripe/silverstripe-framework/pull/10739
- https://github.com/silverstripe/silverstripe-assets/pull/547
- https://github.com/silverstripe/silverstripe-config/pull/84
- https://github.com/silverstripe/silverstripe-mimevalidator/pull/64
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1341
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/260
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/279
- https://github.com/silverstripe/silverstripe-siteconfig/pull/138
- https://github.com/silverstripe/silverstripe-versioned/pull/401
- https://github.com/silverstripe/silverstripe-session-manager/pull/139
- https://github.com/silverstripe/silverstripe-login-forms/pull/134
- https://github.com/silverstripe/silverstripe-documentconverter/pull/42
- https://github.com/silverstripe/silverstripe-iframe/pull/69
- https://github.com/silverstripe/silverstripe-spellcheck/pull/58
- https://github.com/silverstripe/silverstripe-tagfield/pull/236
- https://github.com/silverstripe/silverstripe-taxonomy/pull/90
- https://github.com/silverstripe/silverstripe-blog/pull/704
- https://github.com/silverstripe/silverstripe-widgets/pull/198
- https://github.com/silverstripe/silverstripe-spamprotection/pull/95
- https://github.com/silverstripe/silverstripe-akismet/pull/46
- https://github.com/silverstripe/silverstripe-comments/pull/365
- https://github.com/silverstripe/comment-notifications/pull/55
- https://github.com/silverstripe/silverstripe-contentreview/pull/191
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/484
- https://github.com/silverstripe/silverstripe-segment-field/pull/77
- https://github.com/silverstripe/silverstripe-userforms/pull/1200
- https://github.com/silverstripe/silverstripe-externallinks/pull/98
- https://github.com/silverstripe/silverstripe-securityreport/pull/64
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/62
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/193
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/70
- https://github.com/silverstripe/silverstripe-restfulserver/pull/107
- https://github.com/silverstripe/silverstripe-versionfeed/pull/83
- https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/37
- https://github.com/silverstripe/cwp-search/pull/60
- https://github.com/silverstripe/silverstripe-fulltextsearch/pull/346
- https://github.com/symbiote/silverstripe-queuedjobs/pull/402
- https://github.com/silverstripe/cwp-core/pull/122
- https://github.com/silverstripe/silverstripe-auditor/pull/51
- https://github.com/silverstripe/silverstripe-environmentcheck/pull/87
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/89
- https://github.com/silverstripe/silverstripe-registry/pull/82
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/115
- https://github.com/silverstripe/silverstripe-mfa/pull/490
- https://github.com/silverstripe/silverstripe-crontask/pull/78
- https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/74
- https://github.com/silverstripe/silverstripe-ldap/pull/54
- https://github.com/silverstripe/silverstripe-textextraction/pull/81
- https://github.com/silverstripe/silverstripe-realme/pull/97
- https://github.com/silverstripe/silverstripe-ckan-registry/pull/287
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/132
- https://github.com/silverstripe/silverstripe-security-extensions/pull/54
- https://github.com/silverstripe/cwp/pull/326
- https://github.com/silverstripe/cwp-pdfexport/pull/31
- https://github.com/dnadesign/silverstripe-elemental-userforms/pull/70
- https://github.com/symbiote/silverstripe-multivaluefield/pull/93
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/190
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/71
- https://github.com/silverstripe/cwp-starter-theme/pull/221

**Comment by GuySartorelli** [comment]
The following modules were affected. When reviewing this work, make sure there's a PR for each of these:

- silverstripe/assets
- silverstripe/config
- silverstripe/mimevalidator
- silverstripe/asset-admin
- silverstripe/campaign-admin
- silverstripe/versioned-admin
- silverstripe/siteconfig
- silverstripe/versioned
- silverstripe/session-manager
- silverstripe/login-forms
- silverstripe/documentconverter
- silverstripe/iframe
- silverstripe/spellcheck
- silverstripe/tagfield
- silverstripe/taxonomy
- silverstripe/blog
- silverstripe/widgets
- silverstripe/spamprotection
- silverstripe/akismet
- silverstripe/comments
- silverstripe/comment-notifications
- silverstripe/contentreview
- silverstripe/sharedraftcontent
- symbiote/silverstripe-advancedworkflow
- silverstripe/segment-field
- silverstripe/userforms
- silverstripe/externallinks
- silverstripe/securityreport
- silverstripe/sitewidecontent-report
- bringyourownideas/silverstripe-maintenance
- bringyourownideas/silverstripe-composer-update-checker
- silverstripe/restfulserver
- silverstripe/versionfeed
- silverstripe/elemental-fileblock
- cwp/cwp-search
- silverstripe/fulltextsearch
- symbiote/silverstripe-queuedjobs
- cwp/cwp-core
- silverstripe/auditor
- silverstripe/environmentcheck
- silverstripe/hybridsessions
- silverstripe/registry
- silverstripe/totp-authenticator
- silverstripe/mfa
- silverstripe/crontask
- silverstripe/gridfieldqueuedexport
- silverstripe/ldap
- silverstripe/textextraction
- silverstripe/realme
- silverstripe/ckan-registry
- silverstripe/webauthn-authenticator
- silverstripe/security-extensions
- cwp/cwp
- cwp/cwp-pdfexport
- dnadesign/silverstripe-elemental-userforms
- symbiote/silverstripe-multivaluefieldsilverstripe/cms
- silverstripe/errorpage
- silverstripe/reports
- silverstripe/subsites
- silverstripe/elemental-bannerblock
- cwp/starter-theme

**Comment by GuySartorelli** [comment]
All PRs merged
