### ISSUE TITLE
PHP 8.4 support (after 21 November)

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#331]
PHP 8.4 [releases on 21 November](https://wiki.php.net/todo/php84#timetable).

The [major release policy](https://docs.silverstripe.org/en/5/project_governance/major_release_policy/#php-support-commitments) states
> At launch, a Silverstripe CMS major release supports all PHP versions in full support.

~And~
~> Following the initial launch of a Silverstripe CMS major release, the development team aims to add forward compatibility for the next PHP release. e.g: Silverstripe CMS 5 at launch will support PHP 8.1 and PHP 8.2. CMS 5 should receive official support for an eventual PHP 8.3 in early 2024.~

## Acceptance criteria
- [x] All CMS 6 supported modules are compatible with PHP 8.4 with no deprecation warnings
- [ ] ~All CMS 5.4 supported modules are compatible with PHP 8.4 with no deprecation warnings~

## New issues created
- https://github.com/silverstripe/.github/issues/351

## CI PRs
- https://github.com/silverstripe/supported-modules/pull/47
- https://github.com/silverstripe/gha-generate-matrix/pull/113
- https://github.com/silverstripe/gha-generate-matrix/pull/114

After merging CI PRs, re-trigger with force push PRs below to get PHP 8.4 jobs in matrix

## Kitchen sink CI
- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/12115320472

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11480
- https://github.com/silverstripe/silverstripe-elemental/pull/1285
- https://github.com/silverstripe/silverstripe-admin/pull/1863
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1518
- https://github.com/silverstripe/silverstripe-assets/pull/662
- https://github.com/silverstripe/silverstripe-blog/pull/797
- https://github.com/silverstripe/silverstripe-cms/pull/3032
- https://github.com/silverstripe/silverstripe-graphql/pull/614
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/115
- https://github.com/silverstripe/silverstripe-linkfield/pull/353
- https://github.com/silverstripe/silverstripe-lumberjack/pull/178
- https://github.com/silverstripe/silverstripe-realme/pull/171
- https://github.com/silverstripe/silverstripe-session-manager/pull/227
- https://github.com/silverstripe/silverstripe-siteconfig/pull/182
- https://github.com/silverstripe/silverstripe-subsites/pull/617
- https://github.com/silverstripe/silverstripe-userforms/pull/1352
- https://github.com/silverstripe/vendor-plugin/pull/87
- https://github.com/silverstripe/silverstripe-versioned/pull/483
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/374
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/563
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/423
- https://github.com/symbiote/silverstripe-queuedjobs/pull/453
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/911
- https://github.com/silverstripe/closure/pull/4
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/202
- https://github.com/silverstripe/silverstripe-behat-extension/pull/291
- https://github.com/silverstripe/silverstripe-event-dispatcher/pull/30
- https://github.com/silverstripe/MinkFacebookWebDriver/pull/29
- https://github.com/silverstripe/silverstripe-textextraction/pull/103
- https://github.com/silverstripe/developer-docs/pull/643

**Comment by GuySartorelli** [comment]
@emteknetnz We don't add PHP 8.4 support. The quote you added is about adding PHP 8.3 support to CMS 5.

Similarly we'll add 8.5 to CMS 6 when it releases, and not 8.6 to CMS 6. 

Similarly for CMS 4 we added PHP 8.1 support but not 8.2 or 8.3

**Comment by emteknetnz** [comment]
Have updated description to remove from CMS 5

**Comment by emteknetnz** [comment]
The following script was used to make changes

```php
<?php

include 'vendor/autoload.php';

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

# https://github.com/silverstripe/supported-modules/blob/44e741b156b6ab8aeed2db6d1093dc5c48a06cc8/repositories.json
$json = json_decode(file_get_contents('repositories.json'), true);

$modules = [];

foreach ($json["supportedModules"] as $module) {
    [$vendor, $dir] = explode('/', $module["packagist"]);
    $supported = isset($module["majorVersionMapping"]["6"]);
    $modules[$vendor] ??= [];
    $modules[$vendor][$dir] = $supported;
}

$vendors = [
    'silverstripe',
    'symbiote',
    'tractorcow',
    'dnadesign',
    'colymba',
];

$in = [];
foreach ($vendors as $vendor) {
    foreach ($modules[$vendor] as $dir => $value) {
        if (!$modules[$vendor][$dir]) {
            continue;
        }
        $path = __DIR__ . '/vendor/' . $vendor . '/' . $dir;
        if (str_contains($path, 'recipe-kitchen-sink')) {
            continue;
        }
        $in[] = $path;
    }
}

$finder = Finder::create()
    ->in($in)
    ->name('*.php');

return (new Config())
    ->setFinder($finder)
    ->setRules([
        'nullable_type_declaration_for_default_null_value' => true,
    ]);

```

**Comment by GuySartorelli** [comment]
Note that docs also need to be updated - both with a changelog entry and make sure any references to supported PHP versions includes PHP 8.4

**Comment by GuySartorelli** [comment]
Code changes merged.
Still need docs PR

**Comment by emteknetnz** [comment]
Done

**Comment by GuySartorelli** [comment]
Looking at the framework CI runs, there's still some PHP 8.4 deprecations warnings in our dependencies. Previously we've considered these to be part of PHP compatibility IIRC.

There's likely other deps with similar problems, these were just what I spied from looking at the below CI runs:

https://github.com/silverstripe/silverstripe-framework/actions/runs/12131524771/job/33823951169

> PHP Deprecated:  SensioLabs\AnsiConverter\AnsiToHtmlConverter::__construct(): Implicitly marking parameter $theme as nullable is deprecated, the explicit nullable type must be used instead in /home/runner/work/silverstripe-framework/silverstripe-framework/vendor/sensiolabs/ansi-to-html/SensioLabs/AnsiConverter/AnsiToHtmlConverter.php on line 27

https://github.com/silverstripe/silverstripe-framework/actions/runs/12131524771/job/33823950784

>  Deprecated: Embed\QueryResult::url(): Implicitly marking parameter $attribute as nullable is deprecated, the explicit nullable type must be used instead in /home/runner/work/silverstripe-framework/silverstripe-framework/vendor/embed/embed/src/QueryResult.php on line 82

and various others from the `Embed\` namespace

>  PHP Deprecated:  ML\JsonLD\Processor::listToRdf(): Implicitly marking parameter $graph as nullable is deprecated, the explicit nullable type must be used instead in /home/runner/work/silverstripe-framework/silverstripe-framework/vendor/ml/json-ld/Processor.php on line 2235

and various others from the `ML\JsonLD\` namespace

**Comment by emteknetnz** [comment]
They're third party deprecation notices, there's not a whole lot we can do about those. They should get fixed over time as people release php 8.4 support for their modules.

The sensio labs one does have a fix [committed](https://github.com/sensiolabs/ansi-to-html/commit/0cf4a7e50057723f6a0772d74acd96dc14fbad5f), just not tagged

**Comment by GuySartorelli** [comment]
We can't say Silverstripe CMS 6 is PHP 8.4 compatible while there are lots of PHP deprecation warnings being thrown from _our_ dependencies that projects can't opt out of.

In the past we have submitting pull requests providing PHP compatibility where it's missing in our dependencies. We have also previously forked dependencies that refused to update (see https://github.com/silverstripe/closure/ as an example).

We should do the following:
- Submit PRs to repos to provide PHP 8.4 support where no PR has yet been submitted
- Open a new card to review the deprecation warnings before we release 6.0.0-rc1 in case we need to do some forking or replace a dependency, or at the very least so that we can provide appropriate comms to indicate that while _our_ codebase has been updated, some upstream dependencies are known to not have done so yet.

**Comment by emteknetnz** [comment]
Done https://github.com/silverstripe/.github/issues/351

I think we can now close this issue
