### ISSUE TITLE
Upgrade JS deps - Redux

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#333]
Split from https://github.com/silverstripe/.github/issues/308

Upgrade redux to ^5 and react-redux to ^9 in the following modules
- silverstripe/admin
- silverstripe/asset-admin
- ~silverstripe/campaign-admin~
- silverstripe/cms
- ~silverstripe/contentreview~
- silverstripe/frameworktest
- silverstripe/linkfield
- silverstripe/mfa
- silverstripe/session-manager
- silverstripe/versioned-admin
- dnadesign/silverstripe-elemental

Upgrade redux-thunk to ^3 in the following modules
- silverstripe/admin
- silverstripe/asset-admin
- ~silverstripe/campaign-admin~
- silverstripe/frameworktest
- silverstripe/linkfield

## Notes
- If redux upgrade causes problems with redux-form, we can't upgrade it - try a few majors just in case
  - In that case open a card to re-investigate replacing redux-form for CMS 7

## Acceptance criteria
- [x] redux, react-redux and redux-thunk are upgraded to their latest major versions

## Kitchen-sink CI
- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/12346815149

^ test failures are existing - [elemental](https://github.com/silverstripe/silverstripe-elemental/actions/runs/12342587285/job/34442697226#step:12:258) - [framework](https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/12342589564/job/34442714305#step:12:153)

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1876
- https://github.com/silverstripe/silverstripe-elemental/pull/1299
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1526
- https://github.com/silverstripe/silverstripe-cms/pull/3040
- https://github.com/silverstripe/silverstripe-frameworktest/pull/219
- https://github.com/silverstripe/silverstripe-linkfield/pull/358
- https://github.com/silverstripe/silverstripe-mfa/pull/582
- https://github.com/silverstripe/silverstripe-session-manager/pull/229
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/380

**Comment by GuySartorelli** [comment]
PRs merged
