### ISSUE TITLE
CMS 5 mergeups + broken builds

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#34]
### New issues created
- https://github.com/silverstripe/silverstripe-asset-admin/issues/1345 (manage-files.feature behat failure)

### PRs
- https://github.com/silverstripe/gha-generate-matrix/pull/53
- https://github.com/silverstripe/silverstripe-admin/pull/1491
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/90
- https://github.com/silverstripe/cwp-core/pull/123

**Comment by maxime-rainville** [comment]
All done.
