### ISSUE TITLE
Release CMS 6 alpha

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#340]
## Acceptance criteria
- A alpha version of CMS 6 is released
- The release excludes modules [that lost commercial support](https://github.com/silverstripe/.github/issues/342) unless otherwise explicitly specified in the linked issue
- The changelog includes an automatically generated list of API changes, similar to CMS 5.0.0's changelog
- API docs include CMS 6
- A blog post is published which calls out the release and:
  - [x] Reiterates the release timeline for CMS 6 (when the beta, RC, and stable releases will be)
  - [x] Explains the purpose of the alpha and points out we're still making more breaking changes
  - [x] Highlights the change to supported modules
  - [x] Calls for community members to email us if they want to maintain modules we're dropping support for
  - [x] Calls for community members to explicitly try out the release and open issues (with "CMS 6 REGRESSION" in the title) for new bugs and unexpected breaking changes
  - [x] Highlights a few of the changes we expect could be fairly disruptive (e.g. DBField and form field validation, SiteTree form field scaffolding)
  - [x] Points out if there are any known issues (e.g. https://github.com/silverstripe/silverstripe-framework/issues/11453)
  - [x] Indicates that future alpha releases may happen for select modules in isolation, rather than a full alpha2 of all supported modules
    - in that event there would not be an alpha2 changelog to accompany those changes, but changes would be reflected in the "releases" section in GitHub for the affected repos
  - [x] Points out that there is currently no upgrade tool, though we will considering looking into one if there is sufficient community demand for one.
- The normal comms we do for releases are done (slack messages, forum post, etc)

## PRs
- https://github.com/silverstripe/doc.silverstripe.org/pull/316
- https://github.com/silverstripe/developer-docs/pull/648
- https://github.com/silverstripe/recipe-kitchen-sink/pull/77
- https://github.com/silverstripe/developer-docs/pull/649

**Comment by GuySartorelli** [comment]
Release exists and is installable.
Sink has the wrong constraint for `colymba/gridfield-bulk-editing-tools` (has `5.x-dev` but should have `5.0.0-alpha1`) - @emteknetnz do we care about that? I'm on the fence. We could delete the tag for sink, commit a fix to the composer deps, and re-tag it before doing comms? Or we could just leave it pointing at the wrong place.
The beta onwards won't have this problem, I've got a linked PR above to fix it.

I figure nobody uses the sink other than us and we won't be referencing the alpha tag, so probably not worth resolving?

**Comment by GuySartorelli** [comment]
Docs will be deployed once the linked PRs have been merged.
Still gotta do comms - pending https://github.com/silverstripe/api.silverstripe.org/issues/122 (because otherwise the links in the changelog will 404)

**Comment by emteknetnz** [comment]
Just leave the sink alpha alone, we only ever use x.dev

**Comment by GuySartorelli** [comment]
Sweet.
I'll leave this open as a reminder that comms aren't done yet - but otherwise this is complete.

**Comment by GuySartorelli** [comment]
Done! Released with comms. API docs site will take some more work and is being handled separately - we've added a banner to the changelog pointing out those links won't work in the meantime.
