### ISSUE TITLE
Update supported modules list for CMS 6

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#342]
Original issue (private) https://github.com/silverstripeltd/product-issues/issues/884

The list of modules losing commercial support was decided internally within Silverstripe Ltd

Note: At the time this issue is created this list isn't 100% final, though it's unlikely to deviate too much from what's listed here

## Modules losing support though will release a 6.0.0 version with CMS 6 then remove from sink
- silverstripe/blog
- silverstripe/subsites
- silverstripe/crontask

## Modules losing support
- bringyourownideas/silverstripe-composer-update-checker
- bringyourownideas/silverstripe-maintenance
- cwp/agency-extensions
- cwp/starter-theme
- cwp/watea-theme
- silverstripe/recipe-authoring-tools
- silverstripe/recipe-blog
- silverstripe/recipe-collaboration
- silverstripe/recipe-content-blocks
- silverstripe/recipe-form-building
- silverstripe/recipe-reporting-tools
- silverstripe/recipe-services
- silverstripe/campaign-admin
- silverstripe/auditor
- silverstripe/contentreview
- silverstripe/documentconverter
- silverstripe/elemental-bannerblock
- silverstripe/elemental-fileblock
- silverstripe/environmentcheck
- silverstripe/externallinks
- silverstripe/iframe
- silverstripe/ldap
- silverstripe/registry
- silverstripe/restfulserver
- silverstripe/security-report
- silverstripe/sitewidecontent-report
- silverstripe/versionfeed
- silverstripe/webauthn-authenticator
- symbiote/silverstripe-multivaluefield

## Modules to be copied into silverstripe/reports
- silverstripe/externallinks
- silverstripe/security-report
- silverstripe/sitewide-content-report

## New issues created
- https://github.com/silverstripeltd/product-issues/issues/887 (private)
- https://github.com/silverstripeltd/product-issues/issues/888 (private)

## Acceptance criteria:
- [x] Notes in the CMS 6 docs or changelogs referencing the modules which won't be CMS 6 compatible are removed
- [x] silverstripe/supported-modules is updated
- [x] silverstripe/recipe-kitchen-sink is updated
- [x] https://docs.silverstripe.org/en/6/project_governance/supported_modules/ (CMS 6 version of page) is updated
- [x] 6.0.0 changelog calls out which modules are losing support
- [x] Existing CMS 6 branches are retained (excluding if being copied into silverstripe/reports)
- [x] Relevant code is copied into silverstripe/reports and has its namespaces updated
- [x] 6.0.0 changelogs call out modules copied to silverstripe/reports and updated namespaces 
- [x] Supported badges are removed from README.md on the CMS 6 branches
- [x] Rhino does not display CI status for CMS 6 branches
- [x] Ensure that CI crons stop running for unsupported CMS 6 branches when CMS 6 is released ([new issue](https://github.com/silverstripeltd/product-issues/issues/888))
- [ ] ~Automatic merge-ups no longer merge-up to unsupported branches~
- [ ] ~Rhino does not display merge-up status for CMS 6 branches~
- [x] Modules not losing support until CMS 6 are still released with CMS 6
- [x] Create a [new issue](https://github.com/silverstripeltd/product-issues/issues/887) to remove support for modules not losing support until CMS 6 when CMS 6 has been released

## CMS 5 PRs
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1514
- https://github.com/silverstripe/silverstripe-cms/pull/3028
- https://github.com/silverstripe/developer-docs/pull/635
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1517
- https://github.com/silverstripe/silverstripe-assets/pull/661
- https://github.com/silverstripe/silverstripe-elemental/pull/1284

## Kitchen sink CI
- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/12059755150

## CMS 6 PRs
- https://github.com/silverstripe/supported-modules/pull/46
- https://github.com/silverstripe/recipe-cms/pull/93
- https://github.com/silverstripe/recipe-kitchen-sink/pull/76
- https://github.com/silverstripe/silverstripe-cms/pull/3027
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1512
- https://github.com/silverstripe/silverstripe-admin/pull/1857
- https://github.com/silverstripe/developer-docs/pull/633
- https://github.com/silverstripe/silverstripe-reports/pull/204
- https://github.com/silverstripe/silverstripe-graphql-devtools/pull/65
- https://github.com/symbiote/silverstripe-queuedjobs/pull/452
- https://github.com/silverstripe/silverstripe-mfa/pull/577
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/177
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/98
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/249
- https://github.com/silverstripe/silverstripe-auditor/pull/96
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/342
- https://github.com/silverstripe/silverstripe-contentreview/pull/269
- https://github.com/silverstripe/silverstripe-documentconverter/pull/101
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/168
- https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/60
- https://github.com/silverstripe/silverstripe-environmentcheck/pull/115
- https://github.com/silverstripe/silverstripe-iframe/pull/103
- https://github.com/silverstripe/silverstripe-ldap/pull/96
- https://github.com/silverstripe/recipe-authoring-tools/pull/43
- https://github.com/silverstripe/recipe-blog/pull/61
- https://github.com/silverstripe/recipe-collaboration/pull/39
- https://github.com/silverstripe/recipe-content-blocks/pull/52
- https://github.com/silverstripe/recipe-form-building/pull/42
- https://github.com/silverstripe/recipe-reporting-tools/pull/51
- https://github.com/silverstripe/recipe-services/pull/42
- https://github.com/silverstripe/silverstripe-registry/pull/112
- https://github.com/silverstripe/silverstripe-restfulserver/pull/140
- https://github.com/silverstripe/silverstripe-versionfeed/pull/124
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/200
- https://github.com/symbiote/silverstripe-multivaluefield/pull/122
- https://github.com/silverstripe/silverstripe-externallinks/pull/155
- https://github.com/silverstripe/silverstripe-securityreport/pull/90
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/110
- https://github.com/silverstripe/doc.silverstripe.org/pull/312
- https://github.com/silverstripe/recipe-plugin/pull/48
- https://github.com/silverstripe/silverstripe-assets/pull/660
- https://github.com/silverstripe/silverstripe-installer/pull/381
- https://github.com/silverstripe/silverstripe-versioned/pull/482
- https://github.com/silverstripe/silverstripe-elemental/pull/1283

**Comment by emteknetnz** [comment]
@GuySartorelli I missed some asset-admin CMS 5 deprecations the first time around

**Comment by GuySartorelli** [comment]
Need a PR to remove the supported badge from:
- https://github.com/silverstripe/silverstripe-externallinks
- https://github.com/silverstripe/silverstripe-securityreport
- https://github.com/silverstripe/silverstripe-sitewidecontent-report

**Comment by GuySartorelli** [comment]
Need to remove unsupported modules from the `sources-*.js` files in https://github.com/silverstripe/doc.silverstripe.org

**Comment by GuySartorelli** [comment]
Still need to remove references to these modules from docs. E.g. `You can also keep track of new releases through the CMS UI by installing the [maintenance module](https://github.com/bringyourownideas/silverstripe-maintenance),` in https://docs.silverstripe.org/en/6/contributing/release_process/#keeping-track, recipe-blog mentioned in the recipes page, campaign admin mentioned in a few places.... and that's just the few I checked.

**Comment by GuySartorelli** [comment]
silverstripe/assets has a `hide_in_campaigns` config in the `SilverStripe\Assets\Shortcodes\FileLink` class that needs to be removed. Check for any other references to that config as well.

There's also a reference to campaign admin in the readme of `recipe-plugin`

The `SilverStripe\Versioned\ChangeSet` model has a bunch of references to campaigns.
- Change the singular and plural name to "Changeset" and "Changesets"
- Remove the `CMS_ACCESS_CampaignAdmin` permission
- Update phpdocs that refer to campaigns
- Evaluate if there's a quick win way to remove changesets, though they're so heavily embedded in recursive publishing my suspicion is we can't do that easily enough to be worth the effort.

**Comment by GuySartorelli** [comment]
> Could we perhaps split this one off as a separate card? It's dead code though it doesn't block removing support. Means we can get the sink + alpha sorted quicker

I think removing campaign-admin related stuff is explicitly part of this card.

**Comment by emteknetnz** [comment]
Actually doesn't look too bad will do in this card

**Comment by GuySartorelli** [comment]
Don't know how I missed this last time but:

NEed to remove `hide_in_campaigns` config from `DNADesign\Elemental\Models\ElementalArea`

**Comment by GuySartorelli** [comment]
PRs merged. Reassigning to Steve to check Rhino merge-ups and broken builds tabs display what we expect.

**Comment by emteknetnz** [comment]
Shiny new sink is [green](https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/12061590834), I think I'll just close this one and we'll deal with broken builds etc as they come up. We've merged lots of CMS 6 things recently so broken things could be because of something else that's been merged

**Comment by GuySartorelli** [comment]
> Rhino does not display CI status for CMS 6 branches

This is the AC I wanted you to check in rhino. @emteknetnz Can you please check that?
