### ISSUE TITLE
Replace `silverstripe/closure` with `laravel/serializable-closure`

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#350]
https://github.com/silverstripe/closure/ was forked from https://github.com/opis/closure to address PHP compatibility concerns.

https://github.com/laravel/serializable-closure is a fork of the same repo, which is well maintained. It was a recommended replacement in https://github.com/opis/closure/pull/145#issuecomment-2515011518

We should swap to using laravel/serializable-closure

Since they're both forks of the same package I think this could be sensibly done in a minor release.

## Acceptance Criteria
- [x] Anywhere using `silverstripe/closure` as a dependency uses `laravel/serializable-closure` instead
- [x] `silverstripe/closure` is archived in GitHub
- [x] `silverstripe/closure` is marked abandoned in Packagist with the recommendation to use `laravel/serializable-closure` instead

## PRs
- https://github.com/silverstripe/supported-modules/pull/49
- https://github.com/silverstripe/gha-generate-matrix/pull/115
- https://github.com/silverstripe/doorman/pull/49
- https://github.com/symbiote/silverstripe-queuedjobs/pull/454
- https://github.com/silverstripe/closure/pull/5

**Comment by emteknetnz** [comment]
The doorman runner in queuedjobs was the only place in sink that I could find usage of silverstripe/closure

**Comment by GuySartorelli** [comment]
Assigning back to Steve to tag doorman

**Comment by GuySartorelli** [comment]
PRs merged. Reassigning to Steve for any other ACs that need to be done

**Comment by emteknetnz** [comment]
All done
