### ISSUE TITLE
Failing CMS 5.0 builds

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#39]
- Recipe CCL [![CI](https://github.com/silverstripe/recipe-ccl/actions/workflows/ci.yml/badge.svg?branch=3.0)](https://github.com/silverstripe/recipe-ccl/actions/workflows/ci.yml?query=branch%3A3.0)
  - Looks like some mismatched with the signature of hybrid session
- GraphQL [![CI](https://github.com/silverstripe/silverstripe-graphql/actions/workflows/ci.yml/badge.svg?branch=5.0)](https://github.com/silverstripe/silverstripe-graphql/actions/workflows/ci.yml)
  - Looks like an overly strict array comparison
  - Failing Recipe CMS build as well and sink

Issue
- https://github.com/silverstripe/silverstripe-graphql/pull/533
- https://github.com/silverstripe/recipe-ccl/pull/10

**Comment by sabina-talipova** [comment]
@emteknetnz, could you, please, open PR with [this changes](silverstripe/silverstripe-graphql#533) for CMS 4.
See my comment [here](https://github.com/silverstripe/silverstripe-graphql/pull/533#issuecomment-1522727869)

**Comment by emteknetnz** [comment]
Will close issue for now - have replied https://github.com/silverstripe/silverstripe-graphql/pull/533#issuecomment-1522771754
