### ISSUE TITLE
CMS5: tractorcow/silverstripe-proxy-db update

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#4]
## Acceptance criteria
- Our fork of proxyDB is merged back into the tractorcow repo
- Any module that is currently using our fork is updated to point back at the original packages

## Notes
- Revert the fork to the old name before opening the PR.

**Comment by GuySartorelli** [comment]
Duplicate of https://github.com/silverstripeltd/product-issues/issues/658 which is already in awaiting column
