### ISSUE TITLE
Retarget old PRs

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#41]
PRs which were targetting CMS 4 branches must now target CMS 5 branches if they introduce new API or features.
We also need to decide if we'll rebase the PRs or just ask the original reporter to rebase.
We should _also_ decide if there's some criteria (e.g. not touched in 6 months) that we can use to close stale PRs at this stage.

**Comment by maxime-rainville** [comment]
We've discussed this. Our conclusion is that this is symptomatic of a wider issue and that addressing this in isolation would not be valuable. We will create a more wide ranging card to address the bigger problem.
