### ISSUE TITLE
docs.silverstripe.org - links between major versions

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#45]
Split off from https://github.com/silverstripeltd/product-issues/issues/694

Re docs.silverstripe.com:
- Do we want to include a link to v5 from v4 or not? e.g. v3 has a link that says "Go to documentation for the most recent stable version."
- If we do want to do this, we will need to create a new "status" - currently we only have EOL, supported, and pre-stable.

I think we should create a link from v4 to v5, and make the v4 status light blue, while keeping the v5 stable green

## Acceptance criteria
- People browsing the CMS 4 doc are aware that CMS 5 is the latest stable version.
- The CMS 4 banner nudges people to look at the CMS 5 doc and has a distinctive style.

## PR
- https://github.com/silverstripe/doc.silverstripe.org/pull/265

**Comment by GuySartorelli** [comment]
Looks great!
