### ISSUE TITLE
Broken builds in 5.0

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#47]
## `dnadesign/silverstripe-elemental`
https://github.com/silverstripe/silverstripe-elemental/actions/runs/4997726484/jobs/8952788887

> And a "page" "Blocks Page" with a "Alice's Block" content element with "original content" content                                        # DNADesign\Elemental\Tests\Behat\Context\FixtureContext::theHasAContentElementWithContent()
      Page is invalid (SilverStripe\ORM\ValidationException)

Basically, the configuration that applies `ValidationFailedExtension` to `Page` in the previous scenario either isn't being removed _or_ a flush isn't being conducted after it is removed. This is a change from CMS 4 where that test passes fine.

Tag the module after this is fixed.

## PR
- https://github.com/silverstripe/silverstripe-behat-extension/pull/241

**Comment by GuySartorelli** [comment]
git bisect says this was caused by https://github.com/silverstripe/silverstripe-elemental/pull/1032
Most likely because of the base class change for fixture context.

**Comment by GuySartorelli** [comment]
In [`SilverStripe\BehatExtension\Context\FixtureContext::iAddAnExtensionToTheClass()`](https://github.com/silverstripe/silverstripe-behat-extension/blob/b93e20e9a45db3e467dc5ffb6668db37d5ab5080/src/Context/FixtureContext.php#L651), the extension is added to the context running in the browser by adding a file to `_config`, which gets cleared out after the scenario ends - but the extension is _also_ added to the context running the tests via `::add_extension()`, which was not being cleared.

This was fine in the past, because features that would have been affected were in one of two camps:
1. Weren't adding an extension in a scenario - only in a background
2. Fixtures were being created in the browser context or in a way that didn't trigger errors from extensions

[This change](https://github.com/silverstripe/silverstripe-elemental/pull/1032/files#r1072993603) swapped the context for the creation of `SiteTree` records in elemental features. This caused the new validation failed extension from https://github.com/silverstripe/silverstripe-elemental/pull/930 to cause an error when a new `SiteTree` record was created.

We just need to clear the extensions from the test context after each scenario.

**Comment by emteknetnz** [comment]
Merged and released as [5.0.1](https://github.com/silverstripe/silverstripe-behat-extension/releases/tag/5.0.1)
