### ISSUE TITLE
Review how other OSS projects managed their issues

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#49]
We want to get better idea of how other OSS projects manage issues and PRs.

## Acceptance criteria
- Identify ~5 projects of a similar size to Silverstripe CMS that hosts their issues on GitHub.
- Identify how they triage their issues and pull requests
- Identify how they handle issues/PRs that have gone stale.
- If they explicitly document their process, summarise it.
- List any automation they use to manage issues and PRs.

## Note
- The output of this card could be an RFC if there's "controversial" points to discuss or if there's some obvious next steps, we can just go through the "creating a bot" phase.
- For best results, actually reach out to the maintainers and ask them questions about their process

**Comment by emteknetnz** [comment]
Closing and using https://github.com/silverstripeltd/product-issues/issues/759 instead
