### ISSUE TITLE
Broken builds for CMS 5.x

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#5]
### PRs
- https://github.com/silverstripe/recipe-cms/pull/70
- https://github.com/silverstripe/silverstripe-registry/pull/80
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/111

# OLD (ignore)

The following builds are broken for the CMS 5.x. FYI They are not actually broken for CMS 5.0.x.

## Broken builds
- Registry [![CI](https://github.com/silverstripe/silverstripe-registry/actions/workflows/ci.yml/badge.svg?branch=3)](https://github.com/silverstripe/silverstripe-registry/actions/workflows/ci.yml)
- Sink [![CI](https://github.com/silverstripe/recipe-kitchen-sink/actions/workflows/ci.yml/badge.svg?branch=5)](https://github.com/silverstripe/recipe-kitchen-sink/actions/workflows/ci.yml)
- Session manager [![CI](https://github.com/silverstripe/silverstripe-session-manager/actions/workflows/ci.yml/badge.svg?branch=2)](https://github.com/silverstripe/silverstripe-session-manager/actions/workflows/ci.yml)
- Installer [![CI](https://github.com/silverstripe/silverstripe-installer/actions/workflows/ci.yml/badge.svg?branch=5)](https://github.com/silverstripe/silverstripe-installer/actions/workflows/ci.yml)
- GraphQL [![CI](https://github.com/silverstripe/silverstripe-graphql/actions/workflows/ci.yml/badge.svg?branch=5)](https://github.com/silverstripe/silverstripe-graphql/actions/workflows/ci.yml)
- CMS [![CI](https://github.com/silverstripe/silverstripe-cms/actions/workflows/ci.yml/badge.svg?branch=5)](https://github.com/silverstripe/silverstripe-cms/actions/workflows/ci.yml)
- Campaign admin [![CI](https://github.com/silverstripe/silverstripe-campaign-admin/actions/workflows/ci.yml/badge.svg?branch=2)](https://github.com/silverstripe/silverstripe-campaign-admin/actions/workflows/ci.yml)
- asset-admin [![CI](https://github.com/silverstripe/silverstripe-asset-admin/actions/workflows/ci.yml/badge.svg?branch=2)](https://github.com/silverstripe/silverstripe-asset-admin/actions/workflows/ci.yml)
- versionned-admin [![CI](https://github.com/silverstripe/silverstripe-versioned-admin/actions/workflows/ci.yml/badge.svg?branch=2)](https://github.com/silverstripe/silverstripe-versioned-admin/actions/workflows/ci.yml)

**Comment by maxime-rainville** [comment]
I think the problem here might just be that the build haven't been run in a while. I just triggered a bunch of them.

**Comment by maxime-rainville** [comment]
I think the problem here might just be that the build haven't been run in a while. I just triggered a bunch of them.

**Comment by maxime-rainville** [comment]
GraphQL is green now, but everything else is red.

**Comment by GuySartorelli** [comment]
All merged, assigning to @emteknetnz to check if this solved all the things
