### ISSUE TITLE
Run translations

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#50]
Using https://github.com/silverstripe/silverstripe-tx-translator run translation on Kitchen Sink CMS 4.13 and then merge-up

- https://github.com/colymba/GridFieldBulkEditingTools/pull/236
- https://github.com/silverstripe/cwp-agencyextensions/pull/93
- https://github.com/dnadesign/silverstripe-elemental-userforms/pull/73
- https://github.com/silverstripe/silverstripe-assets/pull/552
- https://github.com/silverstripe/silverstripe-blog/pull/711
- https://github.com/silverstripe/silverstripe-cms/pull/2857
- https://github.com/silverstripe/silverstripe-crontask/pull/79
- https://github.com/silverstripe/silverstripe-framework/pull/10793
- https://github.com/silverstripe/silverstripe-fulltextsearch/pull/350
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/92
- https://github.com/silverstripe/silverstripe-lumberjack/pull/122
- https://github.com/silverstripe/silverstripe-realme/pull/103
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/198
- https://github.com/silverstripe/silverstripe-userforms/pull/1213
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/364

**Comment by sabina-talipova** [comment]
All PRs have been merged. Close this ticket.
