### ISSUE TITLE
Github action on a cron to create a Run Translation issue every 3 months

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#51]
Now that translations are no longer part of releases, we be running https://github.com/silverstripe/silverstripe-tx-translator every few months.

Since this is easy to forget, it would be ideal to have an automatically create an issue in the .github account that reminds us to run translations

### Acceptance criteria
- Github action is created to automatically open issues
- It is on a cron that runs every 3 months
- The https://github.com/silverstripe/gha-keepalive action is active to ensure the actions stays alive
- The opened issues provides a link to the tx-translator module
- Thde issue tells us to run it on 4.13 of kitchen-sink using TX_PULL=1 TX_PUSH=0
- This will create lots of PRs. After these are all merged, merge them up all the way to 5
- The run tx-translator a second time on a fresh 5 install of kitchen-sink and run a second time using TX_PULL=0 TX_PUSH=1
- Once the cut off for 4.13 full support has passed, automatically update it to say use a 5.0 install of kitchen-sink for the first run
- The issue instructs CMS squad to move it straight to the "Ready" column on our internal zenhub board
- The issue instructs CMS squad to patch release every module that has new translations, for each currently supported major
 
### Notes
- Stretch Goal, see if the ZenHub API allows is to move the issue straight in the ready. (Consider potential security implication)
 
### Related card
- #52

### PRs
- https://github.com/silverstripe/gha-issue/pull/1
- https://github.com/silverstripe/.github/pull/59
- https://github.com/silverstripe/gha-pull-request/pull/3

**Comment by emteknetnz** [comment]
I'm not going to attempt the stretch goal (zenhub api integration) - we don't have an existing model to manage 3rd party API keys and I don't feel that "move an issue to a different column in zenhub" warrants establishing a new model for this.

**Comment by GuySartorelli** [comment]
All PRs merged, see you in August
