### ISSUE TITLE
Github action on a cron to create issues to look at JS PRs every 3 months

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#52]
Similar to https://github.com/silverstripe/.github/issues/51, we should have an automatically created issue in the .github account that reminds us to look at the open "DEP Update JS dependencies" PRs that are automatically created via https://github.com/silverstripe/gha-update-js

### Acceptance criteria
- A github action is created on the .github account that creates a new issue
- The cron runs every 3 months
- It is kept alive by the https://github.com/silverstripe/gha-keepalive action
- It automatically finds all of the relevant open pull-requests title "DEP Update JS dependencies"  via the github api and lists them on the opened issue
- If there are no open pull-requests, a new issue is still created and simply says there were no open pull-requests, this is so that we retain a record that it was run
- It also lists all open dependabot pull-requests that should be handled AFTER the "DEP Update JS dependencies" PRs since those will probably resolve the dependabot PRs
- The issue instructs CMS squad to move it straight to the "Ready" column on our internal zenhub board
- 

### Related 
- #51
- https://github.com/silverstripe/gha-update-js/issues/8

### PRs
- https://github.com/silverstripe/.github/pull/60

**Comment by GuySartorelli** [comment]
PR is merged. Closing.
