### ISSUE TITLE
Broken builds on 5 branches

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#56]
- [recipe-core](https://github.com/silverstripe/recipe-core/actions/workflows/ci.yml?query=branch%3A5)

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10800

**Comment by sabina-talipova** [comment]
[Issue was fixed](https://github.com/silverstripe/recipe-core/actions/runs/5163374916).
Close.
