### ISSUE TITLE
CMS 4 broken builds

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#6]
The following builds are broken for CMS 4.x

## Broken builds 4.x
- Sink [![CI](https://github.com/silverstripe/recipe-kitchen-sink/actions/workflows/ci.yml/badge.svg?branch=4)](https://github.com/silverstripe/recipe-kitchen-sink/actions/workflows/ci.yml?query=branch%3A4) - Done
- Admin [![CI](https://github.com/silverstripe/silverstripe-admin/actions/workflows/ci.yml/badge.svg?branch=1)](https://github.com/silverstripe/silverstripe-admin/actions/workflows/ci.yml?query=branch%3A1) - Done
- Graphql [![CI](https://github.com/silverstripe/silverstripe-graphql/actions/workflows/ci.yml/badge.svg?branch=4)](https://github.com/silverstripe/silverstripe-graphql/actions/workflows/ci.yml?query=branch%3A4) - Done
- Elemental [![CI](https://github.com/silverstripe/silverstripe-elemental/actions/workflows/ci.yml/badge.svg?branch=4)](https://github.com/silverstripe/silverstripe-elemental/actions/workflows/ci.yml?query=branch%3A4) - Done
- recipe-solr-search [![CI](https://github.com/silverstripe/recipe-solr-search/actions/workflows/ci.yml/badge.svg?branch=2)](https://github.com/silverstripe/recipe-solr-search/actions/workflows/ci.yml?query=branch%3A2) - Done

## Broken in 4.12.x
- Graphql [![CI](https://github.com/silverstripe/silverstripe-graphql/actions/workflows/ci.yml/badge.svg?branch=4.2)](https://github.com/silverstripe/silverstripe-graphql/actions/workflows/ci.yml?query=branch%3A4.2) - leaving this broken for now. There's no clean way to resolve this problem without changing the constraints for recipe-core 4.12 branch's dependency on graphql to be `3.8.x-dev || 4.1.x-dev || 4.2.x-dev` which is gross. There is no effective difference between `4` and `4.2` in graphql right now anyway, so if 4 is fine then 4.2 is fine. When we release recipe-core 4.13 we'll test graphql 4.2 against that.
- Admin [![CI](https://github.com/silverstripe/silverstripe-admin/actions/workflows/ci.yml/badge.svg?branch=1.12)](https://github.com/silverstripe/silverstripe-admin/actions/workflows/ci.yml?query=branch%3A1.12) - Done

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1462
- https://github.com/silverstripe/gha-run-tests/pull/12
- https://github.com/silverstripe/gha-ci/pull/61
- https://github.com/silverstripe/gha-generate-matrix/pull/45
- https://github.com/silverstripe/recipe-kitchen-sink/pull/37
- https://github.com/silverstripe/gha-generate-matrix/pull/48

**Comment by emteknetnz** [comment]
@GuySartorelli I've merged things and released new versions of the gha things and re-run things

I'll re-assigned back to you so you can check to see if all the things are green

**Comment by emteknetnz** [comment]
Linked PRs have been merged
