### ISSUE TITLE
gha-update-js workflow isn't working correctly

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#61]
The pull-requests being created by the gha-update-js workflow only include a change yarn.lock file, they should also include updated bundle.js files

One thing I've noticed is that `1` branch of silverstripe-admin is being checked out instead of the `2` branch of silverstripe-admin

### ACs
- Update the branch of silverstripe-admin to `2`
- Manually run this on a module at least once to validate this was the issue
- Close without merging the "DEP Update JS dependencies" PRs - https://emtek.net.nz/rhino/tables?t=open-prs&filters={%22title%22%3A%22DEP%20Update%20JS%20dependencies%22}

### PRs
- https://github.com/silverstripe/gha-update-js/pull/12
- https://github.com/silverstripe/gha-update-js/pull/13

**Comment by GuySartorelli** [comment]
Should it not be done on the relevant CMS 4 compatible branch as well? It's probably not a good idea to leave the js deps for cms 4 untouched for 2 years...

**Comment by emteknetnz** [comment]
This process is not run CMS 4 - this is done as part of a github action via a cron which only runs on default branches

If we want to update CMS 4 js deps, it'll either need to be done manually (would take a few hours), or we'd need to look at doing something with dual support as opposed to default branch similar to https://github.com/silverstripe/gha-dispatch-ci - though that's well outside the scope of this particular bugfix issue

**Comment by GuySartorelli** [comment]
> we'd need to look at doing something with dual support as opposed to default branch

Yes. I believe we've discussed that before because we decided it _does_ need to be done against both majors.

> well outside the scope of this particular bugfix issue

I disagree - the bug is "this is against the wrong branch", yeah? So the fix should be to make sure it runs against the correct branch _or branches_. This is something that would have been discussed in refinement - probably this should go into the backlog to be refined properly.

**Comment by emteknetnz** [comment]
Scope of this **bugfix** issue is "current system is broken" - system is currently spitting out incomplete PRs e.g. [this](https://github.com/silverstripe/silverstripe-asset-admin/pull/1346)

"Upgrade system to dual support" would be a separate **enhancement** card

**Comment by maxime-rainville** [comment]
Historically, we've only went back and updated JS dependencies in minor releases. I'm not sure what that would look like as patch releases for CMS4 module or if we should do regression testing for it.

My instinct would be to only do JS updates on CMS4 if there's a security implications or a specific bug that needs fixing for the next year. Once the "Security fix only" phases kicks in, we would only do JS updates for security issues.

I want us to be more proactive about upgrading JS dependencies in CMS 5. CMS 4 is water under the bridge and should be handled differently ... if at all. I'd say merge this PR as-is and raised a separate card to talk about CMS 4 dependencies.

**Comment by GuySartorelli** [comment]
I don't have to agree to click merge ;p
Pr merged and no further action required for this card. Closing.
