### ISSUE TITLE
gha-ci installing dev-master version of fluent instead of 7.x-dev

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#62]
On the 'next-minor' CI run, fluent dev-master is being installed instead of 7.x-dev.  This is because of a [branch alias in fluent](https://github.com/tractorcow-farm/silverstripe-fluent/blob/7/composer.json#L49).

Rather than argue about whether a branch alias should be there or not in a repository not on the silverstripe account, instead I think it's easier to simply conflict dev-master

### ACs
- composer conflict fluent dev-msater when using recipe-kitchen-sink

### PRs
- https://github.com/silverstripe/gha-ci/pull/69

**Comment by GuySartorelli** [comment]
Merged and tagged.
