### ISSUE TITLE
Duplicate yaml key causing all builds to fail

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#64]
Happened as part of merging up translations

https://github.com/silverstripe/silverstripe-versioned/actions/runs/5284283053/jobs/9561554180#step:10:639

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10823
- https://github.com/silverstripe/silverstripe-admin/pull/1527
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/295
- https://github.com/silverstripe/silverstripe-versioned/pull/409
- https://github.com/silverstripe/silverstripe-reports/pull/165
- https://github.com/silverstripe/silverstripe-mfa/pull/500
- https://github.com/silverstripe/silverstripe-realme/pull/109
- https://github.com/silverstripe/silverstripe-subsites/pull/526
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/296

**Comment by sabina-talipova** [comment]
All PRs are merged. Close issue.
