### ISSUE TITLE
Advanced workflow broken builds for 5.0

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/.github#71]
Behat build is broken for advanced workflow.

It just looks like we're expecting `<ins>` and `<del>` tags in a different orders.

https://github.com/symbiote/silverstripe-advancedworkflow/actions/runs/5453985544/jobs/9923520903

**Comment by emteknetnz** [comment]
Fixed in https://github.com/silverstripe/recipe-kitchen-sink/issues/44
