### ISSUE TITLE
Dispatch-CI workflow does not run on some non-silverstripe supported modules #779

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#72]
e.g. https://github.com/symbiote/silverstripe-advancedworkflow/actions

It's cos of the copy paste nature when originally adding the workflow https://github.com/symbiote/silverstripe-advancedworkflow/blob/5/.github/workflows/dispatch-ci.yml#L12

Check all non-silverstripe supported modules that they have the correct account name instead of 'silverstripe'

### PRs
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/74
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/199
- https://github.com/colymba/GridFieldBulkEditingTools/pull/243
- https://github.com/colymba/GridFieldBulkEditingTools/pull/242
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/495
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/368
- https://github.com/symbiote/silverstripe-multivaluefield/pull/96
- https://github.com/symbiote/silverstripe-queuedjobs/pull/408

**Comment by GuySartorelli** [comment]
All PRs merged
