### ISSUE TITLE
gha-ci - Error in regex

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#74]
https://github.com/silverstripe/gha-ci/blob/1.4/.github/workflows/ci.yml#L764 regex needs to be fixed

Meant that this failed to release on 4.13 https://github.com/silverstripe/silverstripe-framework/actions/runs/5482590957

### PRs
- https://github.com/silverstripe/gha-ci/pull/73

**Comment by GuySartorelli** [comment]
PR merged. Rerunning CI on framework

**Comment by GuySartorelli** [comment]
That ran fine and got merged. Closing.
