### ISSUE TITLE
Trial issue and PR templates to see what works best for us

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#79]
## Issue templates
We get quite a few issues that don't say what version of the module or of CMS is affected, don't provide a clear description, and don't include reproduction steps.

This is less of an issue on the framework repo, which _does_ have a template. So we know issue templates do alleviate this problem. But we want to also experiment with a more prescriptive template that _requires_ some information to be included, and see how they compare in effectiveness.

## PR templates
We get quite a few PRs that don't clearly explain what they intend to do, and/or don't link back to an issue.

Even the framework repo, which does have a template for PRs, has this problem. We should replace the framework template with one that more clearly outlines the required information - minimally with a description and a link to an issue (and a note to create a new issue if one doesn't yet exist).

Looking at the docs, there isn't currently a way to have prescriptive PR templates with required fields.

## Acceptance Criteria
- [x] The issue template on the framework repo is evaluated, and if clear improvements to wording or structure are identified, those improvements are made
- [x] Prescriptive form fields are considered. If a prescriptive form is adopted, these sub-ACs will apply:
    - [x] Members of the CMS Squad and core committers must be able to remove required fields from individual issues, as we sometimes need to create issues that have cross-cutting concerns
    - [x] "Affected Version(s)" is required - the template makes this clear that we expect the specific module version to be reported (as opposed to the Recipe-CMS version) and provided guidance on how to retrieve that information.
    - [x] A "Description" is required
    - [x] A "Type" is required, which is either a bug or an enhancement (OR alternatively have two templates - one for bug reports and one for feature suggestions)
    - [x] "Steps to Reproduce" is required if the type is bug
- [x] All issue templates encourage the reporter to create a pull request to fix their own bug or implement the feature themselves.
- [x] The framework pull request template is changed to have clear headings and a explanation of what is required for each heading section
    - [x] A "Description" heading is added, and the explanation encourages people to briefly explain what problem their PR solves
    - [x] A "Testing Steps" or similar heading is added
    - [x] A "Issue" or similar heading is added, and the explanation makes it clear that they should either link to an existing issue, or create a new issue to link to if one doesn't already exist
    - [x] Consider adding the [PR merge checklist](https://docs.silverstripe.org/en/5/contributing/triage_resources/#merge-checklist) to the template, but only if we agree that we will tick the boxes during peer review
- [x] The team agrees about the templates before they are rolled to every repo.

## Notes
- See [Configuring issue templates for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) for information about creating issue templates
  - The one currently on framework uses the [legacy workflow](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)
- See [Creating a pull request template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) for information about creating PR templates
- The templates used by [symfony](https://github.com/symfony/symfony/) might be a really good starting point

## TO REVIEW
Note that everything is up for grabs - the PR merge checklist is included to see what it would be like - but if we don't all agree to actually use it, we shouldn't include it.
- https://github.com/GuySartorelli/issue-template-playground
- [x] bug report issue template
- [x] feature request issue template
- [x] links when creating a new issue (for directing people who need support or want to report a security vulnerability)
- [x] pull request template

## PRs
- https://github.com/silverstripe/module-standardiser/pull/28

**NOTE: These should be adding identical templates, except for the docs repos which are different**
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/208
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/78
- https://github.com/colymba/GridFieldBulkEditingTools/pull/262
- https://github.com/silverstripe/cwp-agencyextensions/pull/108
- https://github.com/silverstripe/cwp-starter-theme/pull/236
- https://github.com/silverstripe/developer-docs/pull/429
- https://github.com/silverstripe/cwp-watea-theme/pull/175
- https://github.com/silverstripe/silverstripe-elemental/pull/1127
- https://github.com/dnadesign/silverstripe-elemental-userforms/pull/85
- https://github.com/silverstripe/silverstripe-admin/pull/1638
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1429
- https://github.com/silverstripe/silverstripe-assets/pull/583
- https://github.com/silverstripe/silverstripe-auditor/pull/64
- https://github.com/silverstripe/silverstripe-blog/pull/737
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/289
- https://github.com/silverstripe/silverstripe-cms/pull/2911
- https://github.com/silverstripe/silverstripe-config/pull/106
- https://github.com/silverstripe/silverstripe-contentreview/pull/218
- https://github.com/silverstripe/silverstripe-crontask/pull/83
- https://github.com/silverstripe/silverstripe-documentconverter/pull/65
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/130
- https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/47
- https://github.com/silverstripe/silverstripe-environmentcheck/pull/96
- https://github.com/silverstripe/silverstripe-errorpage/pull/94
- https://github.com/silverstripe/eslint-config/pull/21
- https://github.com/silverstripe/silverstripe-externallinks/pull/115
- https://github.com/silverstripe/silverstripe-framework/pull/11102
- https://github.com/silverstripe/silverstripe-graphql/pull/566
- https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/92
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/96
- https://github.com/silverstripe/silverstripe-iframe/pull/76
- https://github.com/silverstripe/silverstripe-installer/pull/363
- https://github.com/silverstripe/silverstripe-ldap/pull/66
- https://github.com/silverstripe/silverstripe-lumberjack/pull/135
- https://github.com/silverstripe/silverstripe-mimevalidator/pull/69
- https://github.com/silverstripe/silverstripe-realme/pull/126
- https://github.com/silverstripe/silverstripe-session-manager/pull/175
- https://github.com/silverstripe/recipe-authoring-tools/pull/30
- https://github.com/silverstripe/recipe-blog/pull/46
- https://github.com/silverstripe/recipe-cms/pull/78
- https://github.com/silverstripe/recipe-collaboration/pull/26
- https://github.com/silverstripe/recipe-content-blocks/pull/35
- https://github.com/silverstripe/recipe-core/pull/89
- https://github.com/silverstripe/recipe-form-building/pull/29
- https://github.com/silverstripe/recipe-plugin/pull/36
- https://github.com/silverstripe/recipe-reporting-tools/pull/38
- https://github.com/silverstripe/recipe-services/pull/29
- https://github.com/silverstripe/silverstripe-registry/pull/89
- https://github.com/silverstripe/silverstripe-reports/pull/171
- https://github.com/silverstripe/silverstripe-restfulserver/pull/116
- https://github.com/silverstripe/silverstripe-securityreport/pull/71
- https://github.com/silverstripe/silverstripe-segment-field/pull/94
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/219
- https://github.com/silverstripe/silverstripe-siteconfig/pull/151
- https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/74
- https://github.com/silverstripe/silverstripe-spamprotection/pull/107
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/181
- https://github.com/silverstripe/silverstripe-subsites/pull/552
- https://github.com/silverstripe/silverstripe-tagfield/pull/273
- https://github.com/silverstripe/silverstripe-taxonomy/pull/100
- https://github.com/silverstripe/silverstripe-textextraction/pull/85
- https://github.com/silverstripe/silverstripe-userforms/pull/1259
- https://github.com/silverstripe/vendor-plugin/pull/71
- https://github.com/silverstripe/silverstripe-versioned/pull/430
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/317
- https://github.com/silverstripe/silverstripe-versionfeed/pull/93
- https://github.com/silverstripe/webpack-config/pull/65
- https://github.com/silverstripe/silverstripe-simple/pull/78
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/510
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/377
- https://github.com/symbiote/silverstripe-multivaluefield/pull/100
- https://github.com/symbiote/silverstripe-queuedjobs/pull/414
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/816
- https://github.com/silverstripe/silverstripe-mfa/pull/522
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/141
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/165
- https://github.com/silverstripe/silverstripe-login-forms/pull/159
- https://github.com/silverstripe/silverstripe-dynamodb/pull/57
- https://github.com/silverstripe/gha-ci/pull/96
- https://github.com/silverstripe/gha-run-tests/pull/20
- https://github.com/silverstripe/gha-generate-matrix/pull/75
- https://github.com/silverstripe/gha-auto-tag/pull/17
- https://github.com/silverstripe/gha-pull-request/pull/12
- https://github.com/silverstripe/gha-tag-release/pull/22
- https://github.com/silverstripe/gha-update-js/pull/26
- https://github.com/silverstripe/gha-keepalive/pull/12
- https://github.com/silverstripe/gha-dispatch-ci/pull/10
- https://github.com/silverstripe/gha-issue/pull/8
- https://github.com/silverstripe/gha-merge-up/pull/30
- https://github.com/silverstripe/gha-action-ci/pull/7
- https://github.com/silverstripe/gha-gauge-release/pull/8
- https://github.com/silverstripe/gha-trigger-ci/pull/6
- https://github.com/silverstripe/markdown-php-codesniffer/pull/5

**Comment by n8-dev** [comment]
Informational update.

There is now a way to have a somewhat 
> prescriptive PR templates with required fields.

As in using the Form syntax and multiple templates feature of github, thus people are prompted to fill in the associated details
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

Form syntax: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms


You can also add links on the create page that can offer comments like where to asking questions, where to review security policy etc which definitely help improve the developer experience and help new people into contributing


Here's some real world examples.
Live Examples:
https://github.com/carloscuesta/gitmoji/issues/new/choose
https://github.com/wagtail/wagtail/issues/new/choose (Note: the please go here for questions links, and report vulnerability process)
https://github.com/actions/toolkit/issues/new/choose


I especially markdown around form inputs. (see the second input field below as an example)

Example image:
![image](https://github.com/silverstripe/.github/assets/11827838/09dd8861-65de-4100-8158-99c3353f9b8e)

**Comment by emteknetnz** [comment]
https://github.com/GuySartorelli/issue-template-playground seems good

**Comment by sabina-talipova** [comment]
All looks good to me, but there are couple small question:
- Could we provide small example [here](https://github.com/GuySartorelli/issue-template-playground/blob/855c0957a40b2c039707a446211381a1b5f5f2ce/.github/ISSUE_TEMPLATE/1_bug_report.yml?plain=1#L12-L14), like `e.g 5.1.0 or 5.0 or 5`.
- If we will have a wiki page, could we provide a small template of "Steps to reproduce" there.  I would personally prefer "cucumber" style, but probably there is another best way.

**Comment by GuySartorelli** [comment]
> Could we provide small example [here](https://github.com/GuySartorelli/issue-template-playground/blob/855c0957a40b2c039707a446211381a1b5f5f2ce/.github/ISSUE_TEMPLATE/1_bug_report.yml?plain=1#L12-L14), like e.g 5.1.0 or 5.0 or 5.

Is the `x.y.z` in the placeholder enough? Or would you rather change that placeholder to "e.g. 5.1.0"?
Note that `5.1` and `5` wouldn't really be as useful as exact patch numbers (e.g. 5.1.3) so I don't want to provide those as suggested values.

> If we will have a wiki page, could we provide a small template of "Steps to reproduce" there. I would personally prefer "cucumber" style, but probably there is another best way.

Since we have a whole docs site I don't think it would make sense to have a GitHub wiki. Especially since (afaik) those are per repository, so we'd need to add an identical wiki on each repository which gets a bit messy.

We could certainly add an example to the documentation, and link to that page from the template. Though frankly at this point _any_ reproduction steps would be better than what we currently get :p

**Comment by maxime-rainville** [comment]
This is bloody awesome!!!

I love the extra link to submit security issues and to go the community resource.

On the bug template, do we want to include a link to Elvis on the "Check that there isn't already an issue that reports the same bug" checkbox?

**Comment by GuySartorelli** [comment]
> On the bug template, do we want to include a link to Elvis on the "Check that there isn't already an issue that reports the same bug" checkbox?

We can do - but I'd rather wait until elvis has a proper domain (see https://github.com/silverstripe/github-issue-search-client/issues/121). I don't like the links we have to it in the docs as is because of this problem.

**Comment by emteknetnz** [comment]
Have merged all PRs except fluent

**Comment by GuySartorelli** [comment]
Fluent got merged
