### ISSUE TITLE
merge-up's not triggering ci

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#80]
https://github.com/silverstripe/silverstripe-framework/commit/4d8d5c04a53e5d7266be45ccc42bd9ce64ab02b4 should have triggered a CI run but it did not. This has ramifications for auto-tagging patches, since those are done off the back off CI.

Slack convo
https://silverstripeltd.slack.com/archives/GNHGJT5G8/p1689889075629419

This is one possible solution - but may require a separate token
https://github.com/orgs/community/discussions/25702#discussioncomment-6313966

A seemingly better solution would be to manually trigger CI builds from the gha-merge-up workflow after changes were detected, similar to what gha-dispatch-ci does

### PRs
- https://github.com/silverstripe/gha-merge-up/pull/5

**Comment by GuySartorelli** [comment]
PR merged and tagged
