### ISSUE TITLE
Add workflow_dispatch to ci trigger for patch release

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#81]
gha-chi `gaugerelease:` has this condition

`if: ${{ github.repository == 'silverstripe/silverstripe-framework' && github.repository_owner == 'silverstripe' && (github.event_name == 'push' ||  github.event_name == 'schedule') }`

Need to add `workflow_dispatch` to it so that manually running CI builds can trigger patch releases

### PRs
- https://github.com/silverstripe/gha-ci/pull/75

**Comment by GuySartorelli** [comment]
Merged and tagged
