### ISSUE TITLE
Add auto patch release functionality to gha- repos

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#85]
gha-* repos should have auto patch release functionality after PRs to minor branches are merged.

The patch release functionality is at the tail end of CI. gha-* repos don't use the CI like other modules do.

**Option A**
- move the checkgovernance and gaugerelease steps out of [ghi-ci](https://github.com/silverstripe/gha-ci/blob/1.4/.github/workflows/ci.yml#L742) and into a new action that can be shared
- This is probably overkill since we don't really care about things like not tagging for DOC commits or symbiote modules
- Also if we push an old minor we'll gha-auto-tag will mistakenly make this the `v1` tag

**Option B**
- Just make a new release every time something is pushed to a minor branch on gha-* and make sure it's restricted it to the silverstripe account
- This is much simpler and seems better
- Makes sense to have a new cutdown CI (gha-action-ci) for gha-* modules that simply runs phpunit if it's installed and then does a patch release on push event at the tail end of it

Recommend we go with option B here.

### Example runs

** Example run of new gha-action-ci running phpunit + making a patch release:**
- https://github.com/emteknetnz/gha-generate-matrix/actions/runs/5817539137

** Example of ci.yml using shared gha-gauge-release action:**
- https://github.com/emteknetnz/silverstripe-config/actions/runs/5826871653

### PRs
- https://github.com/silverstripe/gha-gauge-release/pull/1
- https://github.com/silverstripe/gha-action-ci/pull/1
- https://github.com/silverstripe/gha-ci/pull/79
- https://github.com/silverstripe/module-standardiser/pull/6
- https://github.com/silverstripe/module-standardiser/pull/11
- https://github.com/silverstripe/gha-ci/pull/81
- https://github.com/silverstripe/gha-run-tests/pull/15
- https://github.com/silverstripe/gha-generate-matrix/pull/61
- https://github.com/silverstripe/gha-auto-tag/pull/7
- https://github.com/silverstripe/gha-pull-request/pull/6
- https://github.com/silverstripe/gha-tag-release/pull/16
- https://github.com/silverstripe/gha-update-js/pull/16
- https://github.com/silverstripe/gha-keepalive/pull/8
- https://github.com/silverstripe/gha-dispatch-ci/pull/6
- https://github.com/silverstripe/gha-issue/pull/4
- https://github.com/silverstripe/gha-merge-up/pull/10
- https://github.com/silverstripe/gha-action-ci/pull/2
- https://github.com/silverstripe/gha-gauge-release/pull/2

**Comment by GuySartorelli** [comment]
I recommend option A, which is more flexible and reduces doubled-up-code. Surely we want to use the same logic in gaugerelease for GHA as well?

**Comment by emteknetnz** [comment]
Maybe a combo? - I kind of put "create a new ci for action gha-aci" in option B which seems like it's something we want since it simply make rolling this out to all the gha-* repos easier since there's no code duplication, otherwise we'd need to copy paste the patchrelease step on all the repos

The gaugerelease step makes sense to put into its own action to share since it has some good functionality e.g. ensure it's on the latest commit on a branch before tagging

The checkgovernance step probably not at this stage? for gha-* we only care if it's on the silverstripe account whereas checkgovernance was designed for modules on symbiote account etc.

**Comment by GuySartorelli** [comment]
PRs merged and tagged.
Reassigning to @emteknetnz to apply the new gha-action-ci to relevant repositories.

**Comment by GuySartorelli** [comment]
All PRs merged.
