### ISSUE TITLE
PHP 8.3 support in CMS 5.2.0

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/.github#88]
PHP 8.3 releases in November 2023.
As per our [major release policy](https://docs.silverstripe.org/en/5/project_governance/major_release_policy/#php-support-commitments) we aim to support PHP 8.3 in early 2024 - which realistically means in Silverstripe CMS 5.2.0

We need to make sure we resolve any compatibility issues by then, make sure we update docs to indicate PHP 8.3 support, and add PHP 8.3 to our CMS 5 CI runs for 5.2.0 and up.

## Acceptance criteria
- [x] CI for CMS 5x run PHP8.3 builds
- [x] CI for CMS 4 does not run PHP 8.3 builds
- [x] Doc is updated
- [x] Create a follow up card to review build status of unsupported module for PHP 8.3

## Related
- [official release notice](https://www.php.net/releases/8.3/en.php)
- [What's new in PHP 8.3](https://php.watch/versions/8.3)
- CMS 5.1 builds may very well be green on PHP 8.3 ... or very close to. If it's easier to patch CMS 5.1 to be green on PHP 8.3, 
 feel free to do so.
- Module that lost official support with CMS 5 should get the new PHP 8.3 build automatically.

## PRs
- https://github.com/silverstripe/gha-generate-matrix/pull/74
- https://github.com/silverstripe/developer-docs/pull/403

### Follow up card
- https://github.com/silverstripe/.github/issues/172

**Comment by sabina-talipova** [comment]
Passed CI with new matrix: https://github.com/sabina-talipova/silverstripe-installer/actions/runs/6961894106

**Comment by sabina-talipova** [comment]
Final implementation requires that all third-party modules also support PHP 8.3. 
Currently, blocked at least  by `"laminas/laminas-ldap"` module, that has strict constraints `"php": "~8.0.0 || ~8.1.0 || ~8.2.0"`.

**Comment by GuySartorelli** [comment]
Given the ldap repo hasn't had any commits to its default branch in 10 months, it doesn't seem likely this will happen quickly on its own... I've opened an issue in their repo to hopefully get the ball moving: https://github.com/laminas/laminas-ldap/issues/46

**Comment by sabina-talipova** [comment]
Passed CI with new matrix:
Sink: https://github.com/sabina-talipova/recipe-kitchen-sink/actions/runs/7177998490/job/19545421461
Installer: https://github.com/sabina-talipova/silverstripe-installer/actions/runs/7186208374/job/19571116193

**Comment by GuySartorelli** [comment]
PRs merged and CI tagged. We'll see if there are any failures in rhino as the builds run, and can fix them as the need arises.
