### ISSUE TITLE
Add --prefer-lowest build to CMS 5 / 5.0 builds

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#9]
Notice there are failures here on CMS 5 PHP 8.1 --prefer-lowest where a hardcoded matrix was used here https://github.com/silverstripe/silverstripe-postgresql/actions/runs/4312749041/jobs/7523696235

After updating gha-generate matrix, will need to retrigger all the 5.0.x-dev builds to see if they pass.  If they fail, fix them then presumably they'll fix the 5.x-dev builds on merge-up too.

### PRs
- https://github.com/silverstripe/gha-generate-matrix/pull/47

**Comment by GuySartorelli** [comment]
@emteknetnz Merged the PR. Assigning to you to tag and then rerun tests as per your comment in the description.
