### ISSUE TITLE
gha-action-ci auto patch does not trigger auto-tag action

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#94]
Similar story to how gha-merge-up action did not trigger the gha-ci action, instead we needed to "manually" trigger the gha-ci via a githubaction call

We should be able to do this within the action-ci.yml workflow - just do a step to validate that the repo ~~starts with "gha-"~~ has the auto-tag.yml workflow before triggering auto-tag

--

**Example workflow run: https://github.com/emteknetnz/gha-issue/actions/runs/5887182035**

## PRs
- https://github.com/silverstripe/gha-action-ci/pull/4
- https://github.com/silverstripe/gha-tag-release/pull/18
- https://github.com/silverstripe/gha-auto-tag/pull/9

**Comment by GuySartorelli** [comment]
Still fails, because autotag needs the workflow dispatch trigger on all relevant modules:
https://github.com/silverstripe/gha-auto-tag/actions/runs/5920696909/job/16052300615
