### ISSUE TITLE
gha-update-js issue comes out 2 months after workflows run

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#95]
Align timing so that the gha-update-js workflows are all run around a similar time and the the gha-issue that's created on the .github account happens shortly after

## PRs
- https://github.com/silverstripe/.github/pull/97

**Comment by GuySartorelli** [comment]
@emteknetnz Please link any related PRs in the issue description

**Comment by emteknetnz** [comment]
Added

**Comment by GuySartorelli** [comment]
Merged PR
