### ISSUE TITLE
gha-* auto-tag.yml workflows do not have workflow_dispatch trigger

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#96]
Add workflow_dispatch trigger to all the gha-* auto-tag.yml implementations so that they can be manually triggered

Use module-standardiser to create the PRs

workflow_dispatch trigger is being added to action in this pr https://github.com/silverstripe/gha-auto-tag/pull/9

## PRs
- https://github.com/silverstripe/module-standardiser/pull/14
- https://github.com/silverstripe/gha-ci/pull/83
- https://github.com/silverstripe/gha-run-tests/pull/17
- https://github.com/silverstripe/gha-generate-matrix/pull/63
- https://github.com/silverstripe/gha-auto-tag/pull/10
- https://github.com/silverstripe/gha-pull-request/pull/10
- https://github.com/silverstripe/gha-tag-release/pull/19
- https://github.com/silverstripe/gha-update-js/pull/19
- https://github.com/silverstripe/gha-keepalive/pull/10
- https://github.com/silverstripe/gha-dispatch-ci/pull/8
- https://github.com/silverstripe/gha-issue/pull/6
- https://github.com/silverstripe/gha-merge-up/pull/16
- https://github.com/silverstripe/gha-action-ci/pull/5
- https://github.com/silverstripe/gha-gauge-release/pull/4
- https://github.com/silverstripe/gha-trigger-ci/pull/2

## PRs - next-patch
- https://github.com/silverstripe/gha-ci/pull/85
- https://github.com/silverstripe/gha-run-tests/pull/18
- https://github.com/silverstripe/gha-generate-matrix/pull/64
- https://github.com/silverstripe/gha-auto-tag/pull/11
- https://github.com/silverstripe/gha-pull-request/pull/11
- https://github.com/silverstripe/gha-tag-release/pull/20
- https://github.com/silverstripe/gha-update-js/pull/22
- https://github.com/silverstripe/gha-keepalive/pull/11
- https://github.com/silverstripe/gha-dispatch-ci/pull/9
- https://github.com/silverstripe/gha-issue/pull/7
- https://github.com/silverstripe/gha-merge-up/pull/18
- https://github.com/silverstripe/gha-action-ci/pull/6
- https://github.com/silverstripe/gha-gauge-release/pull/5
- https://github.com/silverstripe/gha-trigger-ci/pull/4

**Comment by GuySartorelli** [comment]
All PRs merged

**Comment by GuySartorelli** [comment]
These need to be backported to the most recent current minor branch (e.g. 1.0)
For reference see https://github.com/silverstripe/gha-trigger-ci/actions/runs/5934401060/job/16091259336 where the auto-tag step failed, because it was trying to trigger it on the 1.0 branch.

**Comment by GuySartorelli** [comment]
PRs merged
